### ISSUE TITLE
Create a guide for Open Liberty Tools

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#10]
Write an introductory guide for developing with Open Liberty Tools.

**Comment by yeekangc** [comment]
The draft repo for this is https://github.com/OpenLiberty/draft-guide-tools-intro.

I believe @eharris369 has a draft too.  Erin, can you please submit a PR to the repo so we at least have it there and can be worked on when help is available?

**Comment by evelinec** [comment]
The same request was made to @eharris369 previously.

**Comment by evelinec** [comment]
Checked with @eharris369, the original guide needs to be rewritten, and she will not be working on it for now.

**Comment by yeekangc** [comment]
Guide isn't the best way to cover what we have for tools.  They are best handled via built-in help or documentation plus blog posts (for latest enhancements etc).  Closing.
