### ISSUE TITLE
Develop automated scripts to verify code structures

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#101]
Write automation script(s) to verify code structures, for example: 

- [x] check start and finish directory differences

- [x] check that the folder structure is proper, refer to "Project structure" section in the "Getting started" doc.

- [x] Some of the points in the "Getting started" document can be checked: 

- Don't include the file in the start directory
- Provide the whole file in the guide instructions
- Try to always write in present tense. The only exception here is when a user is yet to do something (ex. "You will learn").
- Using "we" is allowed, but it should be used sparingly; ie. don't write from the "we" perspective.
- Using "let's" is allowed, but it should be used sparingly; ie. don't write "Next, let's implement..." over and over again.

- [x] Check "What to commit" section to make sure only those files/folder are committed

- [x] Include the script to do clean up the repo if undesirable files were committed accidentally. I have the script written to specifically clean up the .DS_Store and target folders.

**Comment by yeekangc** [comment]
Relates to #51.

**Comment by evelinec** [comment]
Other suggestion is to see if Travis CI may help.

**Comment by evelinec** [comment]
Task is completed for now.
