### ISSUE TITLE
Create a document for the new structure and styles

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#104]
- [x] Establish a document for the new structure and styles. Perhaps can revisit the current "Getting Started " document to see anything new needs to be added.

- [x] Continue to elaborate the guideline for developing guides to include anything that’s new and helpful

**Comment by evelinec** [comment]
Assign to @JunyiSun to work. Pls outline here what's needed, and we'll discuss as a team.

**Comment by yeekangc** [comment]
This shouldn't be done in isolation but along with what we already have out there, be it the template or what's on the public wikis.

Also, we should work with Sarah and Laura on this.  Tagging @sishida here in particular.

**Comment by evelinec** [comment]
Move this issue back to backlog as we're not working on it right now.

**Comment by evelinec** [comment]
The "Structure and Style" wiki page has been combined with the guide's template rep, and it's been constantly updated: https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles
