### ISSUE TITLE
Guide for HTTP sessions

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#106]
Guide on working with sessions including session persistence with JCache backed by Hazelcast.

**Comment by yeekangc** [comment]
Reconcile with https://github.com/OpenLiberty/open-liberty/issues/2159.

**Comment by alexsm82** [comment]
Hi @yeekangc, we are thinking of using this to show session caching using the new sessionCache-1.0 feature, using Hazelcast as the JCache provider. If that works for you I can put together an outline for the guide.

**Comment by yeekangc** [comment]
@alexsm82, if you and team would propose an outline, that will be great.  As you know, the focus will be on developers and what they would care about in using JCache.

**Comment by alexsm82** [comment]
Hi @yeekangc, here's an outline for what this guide could look like, although I've heard there is some question about whether we want a guide for this.

Draft Outline:

-Title
-What you’ll learn
-Getting Started
-What is session persistence
-What is JCache
-Configuring Open Liberty
-Configuring Hazelcast
-Writing an application that uses session persistence (likely something space themed persisting items in a shopping cart)
-Testing that sessions are persisted
-Great work! You’re done!

**Comment by yeekangc** [comment]
@alexsm82 and team will contribute.  @alexsm82, please add the right assignee and update the title/outline/description when ready.  Thank you.

**Comment by yeekangc** [comment]
https://github.com/OpenLiberty/draft-guide-sessions

**Comment by evelinec** [comment]
- reviewed and provided feedback for this guide
- informed @alexsm82 of the issue and he will work on it

**Comment by evelinec** [comment]
- few major issues: 
  - intro to be rearranged and perhaps more text needed
  - application focus vs microservice focus 
- worked on addressing list of general guide related issues

**Comment by gkwan-ibm** [comment]
- created an issue for the owner to address
- will ask YK and/or Laura to review

**Comment by gkwan-ibm** [comment]
- the owner created a PR and Eveline will follow it up

**Comment by gkwan-ibm** [comment]
- convert to multipane after addressing the introduction

**Comment by gkwan-ibm** [comment]
- converting to multipane
  - fixing structure and style of the content

**Comment by gkwan-ibm** [comment]
- PR is ready for all known issues
- Gilbert will review
- next step will be user testing

**Comment by gkwan-ibm** [comment]
- fixed up multipane issues and rearranged the guide
- Gilbert will review

**Comment by evelinec** [comment]
- Alex fixed the JDK11 failure for this guide, PR is merged.

**Comment by gkwan-ibm** [comment]
- addressing Gilbert's feedback

**Comment by gkwan-ibm** [comment]
- fixed Gilbert feedback
   - Gilbert will review the fixes
- having problem to show image

**Comment by yeekangc** [comment]
I don't believe we are ready.  See open issues in https://github.com/OpenLiberty/draft-guide-sessions/issues and in particular https://github.com/OpenLiberty/draft-guide-sessions/issues/18, https://github.com/OpenLiberty/draft-guide-sessions/issues/20, https://github.com/OpenLiberty/draft-guide-sessions/issues/21 and https://github.com/OpenLiberty/draft-guide-sessions/issues/23.

**Comment by evelinec** [comment]
Issue #20 had been addressed yesterday. #18 was addressed but has been pending on @gkwan-ibm to re-review all of the responses. #23 is minor, imo. #21 is new, will work on it today.

**Comment by gkwan-ibm** [comment]
- the image issue is working by UI team
- AM is working on 2 YK feedbacks

**Comment by gkwan-ibm** [comment]
- The image is submitted to the Design team
   - they will redraw it
- we need to do some research on http session vs microservice

**Comment by gkwan-ibm** [comment]
- Image is done

**Comment by gkwan-ibm** [comment]
- GK is reviewing

**Comment by gkwan-ibm** [comment]
- working on the instruction

**Comment by gkwan-ibm** [comment]
- peer review is in progress

**Comment by gkwan-ibm** [comment]
will do sme review soon

**Comment by evelinec** [comment]
- Allan Zhang is doing SME review for this guide

**Comment by gkwan-ibm** [comment]
- addressing user review

**Comment by gkwan-ibm** [comment]
- final content review in progress

**Comment by gkwan-ibm** [comment]
- final content review completed
- NG will go the end-to-end test

**Comment by evelinec** [comment]
@Charlotte-Holt This guide is ready for you to review. Here's the repo: https://github.com/OpenLiberty/draft-guide-sessions. Thank you!

**Comment by gkwan-ibm** [comment]
- end-to-end test completed
- need to address the ID feedback

**Comment by gkwan-ibm** [comment]
- GK will review the guide
- JC will do the pretest

**Comment by yeekangc** [comment]
Still need to update URL for link to Containerize guide, @justineechen @gkwan-ibm.

**Comment by gkwan-ibm** [comment]
updated

**Comment by gkwan-ibm** [comment]
- GK will publish on today

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/sessions.html.

**Comment by davidkarlsen** [comment]
I could not find any info on invalidation? We have indications that sessions pile up in hazelcast and are not removed - leading to OutOfMemoryExceptions - I would have expected them to be removed from hz when they are invalid/time out.

**Comment by gkwan-ibm** [comment]
ref: https://github.com/OpenLiberty/open-liberty/issues/9147

**Comment by davidkarlsen** [comment]
Actually we assign a stable unique cloneId via our provisioning system.
