### ISSUE TITLE
update server.xml so that the app can be run remotely

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#1078]
Add `host="*"` to the `httpEndpoint` in the following server.xml
```
 <httpEndpoint host="*"
```
- [x] ./guide-liberty-deep-dive/finish/module-jwt/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive/finish/module-kubernetes/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive/finish/module-metrics/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive/finish/module-securing/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive/finish/module-persisting-data/src/main/liberty/config/server.xml
- [x] ./guide-rest-intro/start/src/main/liberty/config/server.xml
- [x] ./guide-grpc-intro/start/system/src/main/liberty/config/server.xml
- [x] ./guide-grpc-intro/finish/system/src/main/liberty/config/server.xml
- [x] https://github.com/OpenLiberty/guide-security-intro/issues/200
  - ./guide-security-intro/start/src/main/liberty/config/server.xml
  - ./guide-security-intro/finish/src/main/liberty/config/server.xml
- [x] ./guide-arquillian-managed/start/src/main/liberty/config/server.xml
- [x] ./guide-arquillian-managed/finish/src/main/liberty/config/server.xml
- [x] ./guide-microprofile-jwt/start/frontend/src/main/liberty/config/server.xml
- [x] ./guide-microprofile-jwt/finish/frontend/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive-gradle/finish/module-jwt/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive-gradle/finish/module-kubernetes/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive-gradle/finish/module-metrics/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive-gradle/finish/module-securing/src/main/liberty/config/server.xml
- [x] ./guide-liberty-deep-dive-gradle/finish/module-persisting-data/src/main/liberty/config/server.xml
- [x] ./guide-testcontainers/start/src/main/liberty/config/server.xml
- [x] ./guide-testcontainers/finish/src/main/liberty/config/server.xml

**Comment by shin19991207** [comment]
> ./guide-rest-intro/start/src/main/liberty/config/server.xml
>  ./guide-grpc-intro/start/system/src/main/liberty/config/server.xml
> ./guide-grpc-intro/finish/system/src/main/liberty/config/server.xml

There's no ` <httpEndpoint` in these^ files.

**Comment by gkwan-ibm** [comment]
close
- listed guides were updated
