### ISSUE TITLE
Create a guide for MicroProfile Metrics

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#11]
Write a guide for MicroProfile Metrics.

**Comment by evelinec** [comment]
Adding "ID require" tag for team to plan. 
Repo link will be added when guide is ready for ID review.

**Comment by sishida** [comment]
Please include a link to the guides as soon as they are ready for ID review. I think this is the guide for review, so I will take a look at this one today: https://github.com/OpenLiberty/draft-guide-microprofile-metrics/blob/master/README.adoc

**Comment by sishida** [comment]
I have created a pull request for my ID review edits: https://github.com/OpenLiberty/draft-guide-microprofile-metrics/pull/10/files#diff-7bd4a925c695c2eb0eced3872b9b965f

**Comment by yeekangc** [comment]
https://openliberty.io/guides/microprofile-metrics.html
