### ISSUE TITLE
Design for guide introductory document

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/guides-common#112]
On 4/12 we agreed that an introductory document for a guide category would not be a guide itself, but a separate intro type document.

This issue is to track:
* designing how that intro document will look
* how it will be displayed in a guides category alongside the guides.

**Comment by megmulsy** [comment]
Template for the MicroProfile Intro is created
PNG: https://ibm.box.com/s/g2b2whi1pwlxoe80kypgua6rqgevsx5g
Redlines: https://ibm.box.com/s/2h5xsx4urjq041e5ectj9ftvhj5herut
NOTES:
-   Please take a look at how these pieces fit within the grid   Keep the left-hand nav open at all times, do not make it closeable like the other pages.
-     Images should either be left or right aligned, not centered.
-     Max size of image content is 916px across
-     Double check how this content works within the grid - if that's not viewable in the specs lemme know
-     The ‘related guides’ would be the rest of the essentials from the  all guides page, Microprofile section.   
-     Slight wording change in the left column at the bottom of the page (just for this guide)
