### ISSUE TITLE
Guide for JAX-RS 2.1 Reactive Client

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/guides-common#118]
We'll need a guide for using the Reactive Client that comes as part of the `jaxrs-2.1` feature in Liberty.

**Comment by yeekangc** [comment]
Consider if we should cover the plug-in mechanism to APIs like Akka etc.

**Comment by gkwan-ibm** [comment]
- can start the draft on today

**Comment by gkwan-ibm** [comment]
- prototyping the app
- draft the readme ASAP

**Comment by gkwan-ibm** [comment]
- dev content review in progress

**Comment by gkwan-ibm** [comment]
- can start the peer review

**Comment by gkwan-ibm** [comment]
- peer review in progress

**Comment by yeekangc** [comment]
@gkwan-ibm, please update owner for this issue.

**Comment by yeekangc** [comment]
We should illustrate the use of a third-party library.  Otherwise, it is virtually identically to the async MP Rest Client guide.  Open to SME feedback.

**Comment by evelinec** [comment]
- have some changes to consult with YK (redundancy issue)

**Comment by evelinec** [comment]
- the app and tests are working 
- working on updating the readme with the new content

**Comment by gkwan-ibm** [comment]
- peer and SME review in progress

**Comment by evelinec** [comment]
- merging with dev mode content 
- SME review still in progress

**Comment by evelinec** [comment]
- SME review still in progress

**Comment by evelinec** [comment]
- SME review is completed; feedback addressed
- Need to merge into `dev`  - Eveline
- Arrange for user review

**Comment by gkwan-ibm** [comment]
- need final content review

**Comment by evelinec** [comment]
- final content review in progress

**Comment by gkwan-ibm** [comment]
- addressing the final content review

**Comment by gkwan-ibm** [comment]
- revising the app to new design

**Comment by gkwan-ibm** [comment]
- the app and readme are ready for dev content review

**Comment by gkwan-ibm** [comment]
- dev content review in progress

**Comment by gkwan-ibm** [comment]
- dev content review completed
- peer review
  - [ ] Mac - Austin
  - [ ] Linux - Griffin
  - [ ] Win - Danny

**Comment by gkwan-ibm** [comment]
- addressed SME feedback
- next user review

**Comment by gkwan-ibm** [comment]
-user review in progress

**Comment by gkwan-ibm** [comment]
- completed the user review
- addressing more feedback from Gilbert

**Comment by gkwan-ibm** [comment]
- addressed feedback from playback demo

**Comment by gkwan-ibm** [comment]
- next is final content review after GK approval

**Comment by gkwan-ibm** [comment]
- addressing feedback from Grace

**Comment by gkwan-ibm** [comment]
- addressing final content review feedback

**Comment by gkwan-ibm** [comment]
- addressed final content review feedback and wait for approval

**Comment by gkwan-ibm** [comment]
- ready for ID review

**Comment by gkwan-ibm** [comment]
- addressing ID review

**Comment by gkwan-ibm** [comment]
- addressed ID review and wait for approval
- need SME to clarify a couple of issues

**Comment by gkwan-ibm** [comment]
- ID review completed
- Final end-to-end test (Griffin)

**Comment by yeekangc** [comment]
Thank you, team.  Let us proceed to publish.

**Comment by gkwan-ibm** [comment]
The guide was published at https://openliberty.io/guides/reactive-rest-client.html
