### ISSUE TITLE
Create a guide for consuming REST with AngularJS

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#12]
Write a guide for consuming REST services with AngularJS on Open Liberty.

**Comment by kinueng** [comment]
Hello @yeekangc @Kubik42,
Can this be closed now that we have the guide published on openliberty.io?

https://openliberty.io/guides/rest-client-angularjs.html

**Comment by yeekangc** [comment]
Yes, we should close.  Thank you, @kinueng.
