### ISSUE TITLE
Getting started with Open Liberty guide

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#120]
This is a guide to get started with Open Liberty itself (not the technologies that can run on OL).

Currently working on this here: https://github.com/lauracowen/draft-guide-gettingstarted

**Comment by lauracowen** [comment]
Now here: https://github.com/OpenLiberty/draft-guide-gettingstarted

Please could relevant people take a look, test it, review/edit it, make it match the guides guidance, get it ready to publish? (see also https://github.com/OpenLiberty/draft-guide-gettingstarted/issues/1)
@yeekangc @gcharters @NottyCode @sishida @Kubik42 @cajaygle @cbridgha 

I think it all works. I’ve stripped out as much as I can to make it a simple app. I’ve currently left in the Metrics stuff (originally based on the Try It Now app but quite a lot changed now to simplify it for GS guide) but I’m not sure it adds much (if it’s removed, need to update the web page too). Keep the webpage (it loads of user goes to localhost:9080) - again it’s stripped back a bit from original Try It Now sample. Ping me next week if any problems or questions about why something is done one way rather than another (feel free to ask or suggest alternatives).

**Comment by sishida** [comment]
Hi, Laura, I wasn't able to clone with the command, "git clone https://github.com/openliberty/guide-open-liberty.git". Do I need permissions or special access to clone because we haven't published this guide yet?

I'm able to use "git clone https://github.com/OpenLiberty/sample-getting-started.git" on the openliberty.io page.

**Comment by lauracowen** [comment]
Ah, no. Sorry, I hadn't updated the guide since moving the repo to OpenLiberty. No, the sample-getting-started.git repo is the 'Try It Now' sample from the OL.io homepage. The one you want should be the one you get from the 'draft-guide-gettingstarted' repo: https://github.com/OpenLiberty/draft-guide-gettingstarted.git

**Comment by yeekangc** [comment]
@Kubik42 will continue the reviews and move forward with this guide.

**Comment by evelinec** [comment]
@sishida This guide is ready for review. Thank you. 

Repo: https://github.com/OpenLiberty/draft-guide-gettingstarted

**Comment by sishida** [comment]
Link to pull request for ID line edits: https://github.com/OpenLiberty/draft-guide-gettingstarted/pull/13

**Comment by Kubik42** [comment]
Thanks @sishida !

**Comment by yeekangc** [comment]
Guide is published here: https://openliberty.io/guides/getting-started.html
