### ISSUE TITLE
mvnpackage.adoc gives incorrect advice

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/guides-common#121]
The  mvnpackage.adoc says "If you make changes to the code, use the Maven package goal to rebuild the application and have the running Open Liberty server pick them up automatically". I followed this advice and got the following error:

Server MVCServer package failed. It must be stopped before it can be packaged.

I ran into this while reviewing a draft guide. After I stopped the Liberty server, I was able to run the Maven package goal and start the Liberty server and access the updated application. There was nothing "automatic" about it.

**Comment by yeekangc** [comment]
@Kubik42, I thought we addressed this previously?  Can you take a look?

**Comment by Kubik42** [comment]
@cherylking Which guide was this? I also noticed this happening recently. I found that the problem is the package server goal.

**Comment by cherylking** [comment]
@Kubik42 It's a draft guide, but this file is common to all guides. Are you saying something in the guide's artifacts is causing it?

**Comment by Kubik42** [comment]
@cherylking I'm not sure, but recently I ran into this issue when I had the `package-server` goal listed in `executions`. Is the draft-guide-springboot-mvc guide affected? I can try debugging it.

**Comment by chyt** [comment]
Really what we should be suggesting is to call `mvn compile`. This will re-compile the source and update the class files in the `target` folder, which will be picked up by the loose application.

**Comment by Kubik42** [comment]
I've renamed the mvnpackage.adoc to mvncompile.adoc and changed it to use `mvn compile` instead of `mvn package`. I've changed all references of mvnpackage.adoc to mvncompile.adoc that I could find, and created PRs for others. If I missed something please let me know.

**Comment by chyt** [comment]
@Kubik42 You have a typo in the `mvncompile.adoc`. The goal is misspelled as `compiule` in the text.

**Comment by Kubik42** [comment]
@chyt Whoops, honest typo!
