### ISSUE TITLE
Guide for JSON-B/JSON-P

### ISSUE THREAD

**Issue by alexsm82** [OpenLiberty/guides-common#122]
Create a guide for the JSON-B and JSON-P features in Liberty.

**Comment by yeekangc** [comment]
@alexsm82 and team will work on/contribute this.  @alexsm82, please add the right assignee when ready.  Thank you.

**Comment by evelinec** [comment]
@sishida The JSON-B and JSON-P changes on the "Consuming REST" guide is ready for review. 

PR with readme.adoc changes: https://github.com/OpenLiberty/guide-rest-client-java/pull/20/files

**Comment by sishida** [comment]
Working on review now.

**Comment by sishida** [comment]
Review complete!

**Comment by yeekangc** [comment]
Guide has been updated to cover JSON-B: https://openliberty.io/guides/rest-client-java.html
