### ISSUE TITLE
Getting Started Guideline Review

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guides-common#124]
- **Stage 1: Setting up your computer**

These instructions seem straightforward depending on the level of the developer. If there are more introductory developers out there it might help to have a couple of sentences before these three steps outlining that Maven builds the project and Asciidoc is simply a document format that we use. 

- **Stage 3: Getting familiar with the writing style and principles**
I think it would be useful to have a high-level view of what the guide structure looks like. Something similar to:
├── draft-guide-name
    ├── finish
    ├── start
    └── README.adoc

> "Finish is a completed version of the project that the user will be working towards during the guide. Start is a directory that will include boiler plate code for the user to get started. Finally, the README.adoc is where the actual document of your guide resides."

And also include "The aim..." 

[Is there redundancy in my fix? Opinions?]

- **Stage 4: Detailed steps to start creating a new guide**

 **1. Proposing a topic (Optional)**
Perhaps this step is unnecessary because it means there are two restrictions for having a guide published: topic approval _and_  guide draft approval. However it would be helpful to have a list of topics for developers to choose from and we can ensure quality work at the guide draft approval stage (Step 4.) 

**3. Developing** 
I think this area could include more instructions. Especially what code should be removed from the finish directory to create the start directory. Perhaps there could be steps for this part:

> **A. Creating your project [Finished]**
> You will start by creating your project in the finish directory. This should be a very simple application that demonstrates the use of the topic you chose. 
> 
> **B. Separating your starter code [Start]**
> Create a copy of the finish directory and rename it Start. You will now isolate the code that you want the user to focus on and remove them from the Start directory. This would probably be whichever lines of code are essential to your topic. 
> 
> **C. Writing your guide [README.adoc]**
> This is step is when you specifically explain the parts of code that you removed from Step B and explain to the users where to copy and paste the code. It is also where you would walk through how to build the finish directory, run the tests etc. for the user to be able to run your project on their own.

**Comment by evelinec** [comment]
@justineechen This is the getting started guideline. There's another guide also named "Getting Started". Thanks.

**Comment by evelinec** [comment]
@justineechen can you review the changes made according to your feedback. We'd proceed to close this one.
