### ISSUE TITLE
Look at what guides we should have for NoSQL

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#129]
Consider what guides we should have for accessing data in NoSQL databases.

MongoDB?
CouchDB?
Both?
Others?

**Comment by yeekangc** [comment]
@gcharters, @NottyCode, @kwsutter, please chime in if you have thoughts regarding this.

**Comment by gkwan-ibm** [comment]
close
- The [Persisting data with MongoDB](https://openliberty.io/guides/mongodb-intro.html) guide was published
