### ISSUE TITLE
Create guide for contributing a guide

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#13]
Need some 'how to' info on how to contribute a guide to Open Liberty.

Maarten has suggested a JPA guide and has asked for such guidance soon: see https://twitter.com/mthmulders/status/919927099917586434 and https://twitter.com/mthmulders/status/923162136427356160

**Comment by evelinec** [comment]
We're currently reviewing the "Contributing a guide" guide.

**Comment by evelinec** [comment]
We're currently reviewing the "Contributing a guide" guide.

**Comment by evelinec** [comment]
The "Contribute a guide" guideline is in the guide's template, https://github.com/OpenLiberty/draft-guides-template.
