### ISSUE TITLE
Potential issue when importing into eclipse

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/guides-common#135]
At Eclipsecon France, someone had issues importing projects into eclipse. They did the git clone in eclipse, and did the import from the git view. Something went wrong and the project was picked up as a maven project but not as a java project (i.e. no source folders, no classpath etc.) Deleting the project and re-importing through the `File -> Import -> Maven -> Existing Maven projects` wizard worked.

I don't think it's a problem with the guide, but is there anywhere sensible we can note this potential pitfall?(as well as any others we're aware of) An FAQ or anything.

**Comment by gkwan-ibm** [comment]
close
- guides were updated to have unique artifactId. When import multiple guides to the same Eclipse workspace, different projects should be created.
