### ISSUE TITLE
Fix concurrency issue on the data model in the inventory app 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#137]
InventoryList is not thread safe. You will get ConcurrentModificationExceptions if one thread is adding hosts while another is reading them. You could also end up adding the same host twice if two threads call addtoInventoryList at the same time.

This class needs to be synchronized appropriately to make it thread safe, or it needs to be documented to be not thread safe and the rest of the code re-written to ensure it isn't used in an unsafe way.

Although this bug is tangential to the subject of the guide, it's not great to have a sample web service which will break if it has to handle requests in parallel.

**Comment by proubatsis** [comment]
Since @andrewdes is using a `HashMap` in his new model, we can simply update that to use a `ConcurrentHashMap` instead. I also brought this up in the PR: https://github.com/OpenLiberty/guide-cdi-intro/pull/48#issuecomment-398797509

**Comment by evelinec** [comment]
Resolved.
