### ISSUE TITLE
Integrate Travis with Docker to test guides that use Docker containers

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guides-common#139]

**Comment by Kubik42** [comment]
some useful material:
- https://stackoverflow.com/questions/34377017/what-are-the-differences-between-the-before-install-script-travis-yml-opti
- https://docs.travis-ci.com/user/docker

**Comment by yeekangc** [comment]
@gkwan-ibm, with MicroShed Testing, do we need this still?  If not, we can close?

**Comment by gkwan-ibm** [comment]
close:
- if possible, the guide travisTest.sh will use docker
