### ISSUE TITLE
Building the prerequisite section for the guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#143]
For more complicated guides where there are more prereq steps required, there is a new section being introduced for the guides. It's named "Prerequisites". So far, the https://github.com/OpenLiberty/draft-guide-kubernetes[Kubernetes] and https://github.com/OpenLiberty/draft-guide-istio[Istio] guides have this new section. This issue is to work out a design to display the "Prerequisites" section in the multipane.

**Comment by yeekangc** [comment]
The prereqs are captured within the flow of the guide today under a Prerequisites section for the guides with more complex dependencies so users will know they need to setup the prereqs first.

In a multi-pane design, there can be better design to make it easier for users to find out about the needed dependencies or prereqs, set them up before they venture too far down the guide or before they actually start on the guide.

@cajaygle @megmulsy, can you please look into this and see what's possible?

@steven1046 @kinueng, FYI.

**Comment by gkwan-ibm** [comment]
close
- basic prereqs are shown in the top area on the right pane
- additional prereqs are mentioned in the "Additional prerequisites" section that is before the "Getting started" section
