### ISSUE TITLE
[Interactive] [EE8] Guide for JAX-RS 2.1 Server Sent Events (SSE)

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/guides-common#150]
Interactive guide for JAX-RS 2.1 Server Sent Events (SSE).
Part of an Interactive REST track that uses a single backend app to speed up development for this set of interactive guides.

**Comment by yeekangc** [comment]
We won't be proceeding with interactive guide for this topic at the moment.  Will revisit when a need arises.
