### ISSUE TITLE
[Interactive] Guide for Kubernetes

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/guides-common#154]
Create an Interactive guide about using Kubernetes to manage Docker containers running OL servers.
This may be (TBD) like our 'traditional' interactive guides, or a new type that uses a real backend machine that we would host or we'd leverage a service/third party like Katacode.

**Comment by yeekangc** [comment]
This may map 1:1 to #98 but done interactively.

**Comment by gcharters** [comment]
Need to resolve the direction - Kube site (Kubernetes.io), katacode or traditional interactive guide.
@mbroz2 to coordinate.

**Comment by yeekangc** [comment]
We may have a way forward with static guides with Docker for Windows and Docker for Mac that include Kubernetes now -- See https://github.com/OpenLiberty/draft-guide-kubernetes/issues/25.

Sorting through the details and it may mean that we won't need interactive guide and can close the issue.

**Comment by yeekangc** [comment]
Moving forward as per https://github.com/OpenLiberty/guides-common/issues/154#issuecomment-419557314.  Closing this issue.
