### ISSUE TITLE
[Interactive] Guide for Istio

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#155]
Create an Interactive guide about using Istio on top of Kubernetes.
This may be (TBD) like our 'traditional' interactive guides, or a new type that uses a real backend machine that we would host or we'd leverage a service/third party like Katacode.

It may map 1:1 to this guide: #99

**Comment by gcharters** [comment]
Need to resolve the direction - katacode or traditional interactive guide.
@mbroz2 to coordinate.

**Comment by yeekangc** [comment]
We may have a way forward with static guides with Docker for Windows and Docker for Mac that include Kubernetes now -- See OpenLiberty/draft-guide-kubernetes#25.

Sorting through the details and it may mean that we won't need interactive guide and can close the issue.

**Comment by yeekangc** [comment]
Moving forward as per https://github.com/OpenLiberty/guides-common/issues/155#issuecomment-419557572.  Closing this issue.

**Comment by gkwan-ibm** [comment]
Publish (Gilbert)
- [ ] update the publish date
- [ ] rename the guide repo
- [ ] add the guide url in the GitHub repo description
- [ ] refresh master
