### ISSUE TITLE
All dockerfiles using the unzip plugin are broken

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guides-common#159]
The newest open-liberty image no longer has the unzip plugin, so all Dockerfiles using it will break. To fix, simply add the following lines to download the pugin:

```
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \\
```

And the following when the unzip plugin is no longer needed:

```
RUN apt-get remove -y unzip
```

(from memory) guides that have dockerfiles:

- kube
- docker
- getting started
- istio

**Comment by proubatsis** [comment]
@Kubik42 

I opened PRs for kubernetes and getting started.

Getting started and Istio do not use the `unzip` command:

https://github.com/OpenLiberty/guide-docker/blob/master/finish/Dockerfile
https://github.com/OpenLiberty/draft-guide-istio/blob/master/finish/system/Dockerfile
https://github.com/OpenLiberty/draft-guide-istio/blob/master/finish/inventory/Dockerfile

**Comment by evelinec** [comment]
@proubatsis what about the docker guide? Thanks.

**Comment by proubatsis** [comment]
That was a typo in my comment, I meant to say Docker and Istio do not use the `unzip` command. I edited the comment to reflect that. @evelinec

**Comment by Kubik42** [comment]
I think everything has been fixed. Feel free to close @proubatsis once you merge.

**Comment by proubatsis** [comment]
All the PRs have been merged.
