### ISSUE TITLE
Present common build steps more clearly

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#16]
Do you think we could remove the mention of `mvn package`? Instead just say "...installation attempts to start a server. If this happens, stop the server then try again." (or something like that to help them fix the problem but without taking them into Maven concepts when they're focused on building a REST service - or other things in the other guides). Address the issue of packaging in the Maven guide. Would that work from a technical point of view?

Also, because of the relative prominence of the highlighting in this section, my tester missed that she needed to run a separate command to start the server (eg liberty:start-server) and assumed that the two commands in the grey boxes were consecutive commands to run and that one of them would do it. Then she couldn't access the app because the server hadn't started. I think we need to explicitly call out how to start the server by giving the command (in a grey box) after the `mvn install` step (and lose the `mvn package` bit, as described above).

![image](https://user-images.githubusercontent.com/3322532/33135922-c1cd0788-cf9b-11e7-85ce-52a6700b0ad2.png)

(from usability tester feedback)

@NottyCode Please can you comment on whether you agree with this or see problems with it (before anyone implements any changes)?

NB This change would be made in the common include file so will impact on *all* static guides so they should all be checked against the change to make sure they all make sense still.

**Comment by Kubik42** [comment]
Addressed in cb8ccc48755f08f3184b0327633ca8d2af047e7a
