### ISSUE TITLE
Guide for MicroProfile Rest Client Async Methods

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/guides-common#162]
MP Rest Client 1.1 will be part of the 18.0.0.3 release.  It includes four new enhancements from the previous 1.0 release  They are (copied from the [MP Rest Client 1.1 release page] (https://github.com/eclipse/microprofile-rest-client/releases/tag/1.1)):
- Asynchronous Methods - to use, just update the return type of your Rest Client methods to be `CompletionStage`.
- `RestClientBuilderListener` - now products can plug in and register providers, update config properties, etc. prior to the creation of new client instances. This enables other MicroProfile technologies, like Open Tracing to automatically add their client request/response filters to MP Rest Clients.
- Supports java.net.URI in addition to java.net.URL.
- `@RegisterRestClient` is now a bean-defining annotation - no longer need to add `@Dependent` annotation to the client interface.

This guide should focus primarily on the asynchronous methods as this is the biggest change.  Using URIs instead of URLs and using client interfaces without the CDI scope annotations (like `@Dependent`) could be included but won't require as much explanation.  The `RestClientBuilderListener` is primarily intended for third party extensions, not for most users.

**Comment by evelinec** [comment]
Re "Using URIs instead of URLs and using client interfaces without the CDI scope annotations (like @Dependent) could be included but won't require as much explanation." We're proposing to update our current Rest Client guide with these change.

**Comment by yeekangc** [comment]
@andymc12, as you know, we do not guides by spec level but focus on topics or technologies that are relevant and important to developers.

Sounds like what we have here is the suggestion for a guide on Async Methods.  The rest can either be "built into" the sample impl or where and if appropriate, be updates to say the existing MP Rest Client intro guide.

Your thoughts?

**Comment by andymc12** [comment]
@yeekangc That sounds like a great idea.  Yes, the biggest feature in 1.1 is async methods, so if you can work in some of the other features (like using URIs instead of URLs), that would be great.

Thanks!

**Comment by yeekangc** [comment]
Thank you, @andymc12.  Re-purposing this for MP Rest Client Async Methods.

**Comment by andymc12** [comment]
Per separate discussion, it might also make sense to document async in general for REST - so that it could include async JAX-RS (client and server) methods.

**Comment by irobins** [comment]
Async JAX-RS is, at the same time, one of the most promising and one of the most confusing parts of MP/JavaEE . Full of implementations choices but short on prescriptive advice and examples to "do it like this and here's the running result". We are in serious need of this guide.

**Comment by gkwan-ibm** [comment]
- will draft the guide

**Comment by gkwan-ibm** [comment]
- draft is ready
- can start peer review

**Comment by gkwan-ibm** [comment]
- peer review is in progress

**Comment by gkwan-ibm** [comment]
- dev content review in progress

**Comment by evelinec** [comment]
- reviewing the diagram with YK

**Comment by gkwan-ibm** [comment]
- prototyping the app

**Comment by evelinec** [comment]
- working on the app, has problem with the producer and consumer

**Comment by gkwan-ibm** [comment]
- target to complete the prototype on next Thursday

**Comment by gkwan-ibm** [comment]
- reworking the README and test

**Comment by evelinec** [comment]
- test is working; working on the readme today

**Comment by gkwan-ibm** [comment]
- the draft is completed and need to update the copyright

**Comment by gkwan-ibm** [comment]
- working on the dev content review feedback

**Comment by gkwan-ibm** [comment]
- target to complete the dev content review feedback on today or next Mon
- then will do the 2nd around dev content review

**Comment by gkwan-ibm** [comment]
- addressed the first round dev content review feedback
- will do the 2nd around dev content review and peer review

**Comment by gkwan-ibm** [comment]
- peer review in progress

**Comment by gkwan-ibm** [comment]
- completed the peer review and test
- addressing the peer review feedback

**Comment by gkwan-ibm** [comment]
- target to have SME review on tomorrow or next Mon

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- user review in progress

**Comment by gkwan-ibm** [comment]
- addressing the user review

**Comment by gkwan-ibm** [comment]
- final content review in progress

**Comment by DannyS03** [comment]
Tested end-to-end on macOS 
- There are test case failures (`endpoint tests`) for the micro-services, but application works and able to build and containerize with docker.
- Endpoints accessible.

**Comment by evelinec** [comment]
@Charlotte-Holt This guide is ready for you to review. Repo: https://github.com/OpenLiberty/draft-guide-microprofile-rest-client-async

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/microprofile-rest-client-async.html.
