### ISSUE TITLE
Guide for Social Login

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#167]
Simplify the security with SSO and/or social logins now the features are available in Open Liberty.

eg https://github.com/OpenLiberty/open-liberty/issues/3690

**Comment by yeekangc** [comment]
We have #131 for SSO using JWT already and it has been prioritized.  Then, we should cover Social Login (as a separate guide).

I think we can re-purpose this issue to track Social Login.  Is that alright, @lauracowen?

**Comment by yeekangc** [comment]
Re-purposing this to cover Social Login.

**Comment by kwsutter** [comment]
This request just came up on the review for OIDC auto-discovery...  Since we are now focusing our efforts on socialLogin being *the* OIDC solution for both Open Liberty and WebSphere Liberty, we need to ensure that we have suitable Guides in place to support that direction.

**Comment by yeekangc** [comment]
Demonstrate the use of the [socialLogin](https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html) feature to authenticate users that will login using a third-party service like Google, GitHub etc.

**Comment by yeekangc** [comment]
@kartikrajkanna and Trevor (Crawford) may be looking at this.

**Comment by ankitagrawa** [comment]
Drafting the guide. 
Test Case development in progress.

**Comment by gkwan-ibm** [comment]
- completed the test
- drafting the guide content

**Comment by gkwan-ibm** [comment]
- the draft is completed
- ready to have dev content review

**Comment by gkwan-ibm** [comment]
- The 1st dev content review feedback
  - https://github.com/k-rtik/draft-guide-sl/issues/1

**Comment by gkwan-ibm** [comment]
- addressing the dev content review feedback

**Comment by gkwan-ibm** [comment]
- addressed the first dev content review feedback

**Comment by gkwan-ibm** [comment]
@k-rtik 
- The 2nd dev content review feedback
  - https://github.com/OpenLiberty/draft-guide-social-login/issues/1

**Comment by gkwan-ibm** [comment]
- addressing the dev content review feedback

**Comment by gkwan-ibm** [comment]
@k-rtik 
- The 3rd dev content review feedback
  - https://github.com/OpenLiberty/draft-guide-social-login/issues/3

**Comment by gkwan-ibm** [comment]
- addressing the 3rd dev content review feedback

**Comment by gkwan-ibm** [comment]
@k-rtik 
- the 4th dev content review feedback
  - https://github.com/OpenLiberty/draft-guide-social-login/issues/5

**Comment by gkwan-ibm** [comment]
addressing the 4th dev content review feedback

**Comment by gkwan-ibm** [comment]
- addressed the 4th dev content review feedback
- will do some testing, then ready to peer review

**Comment by gkwan-ibm** [comment]
- ready for peer review
 - Mac (Danny)
 - Linux (Nimrah)
 - Win (Jimmy)

**Comment by gkwan-ibm** [comment]
- addressing teh peer review feedback

**Comment by gkwan-ibm** [comment]
- ready for dev content review again

**Comment by gkwan-ibm** [comment]
- after address https://github.com/OpenLiberty/draft-guide-social-login/issues/14, need to redo peer review

**Comment by gkwan-ibm** [comment]
- peer review
  -  Mac (Mai)
  -  Linux (Nimrah)
  -  Win (Danny)

**Comment by ankitagrawa** [comment]
- addressing the feedback.

**Comment by gkwan-ibm** [comment]
- addressed the peer review feedback
- will be ready to next after testing

**Comment by gkwan-ibm** [comment]
- peer review completed
- after GK review, next is SME review

**Comment by gkwan-ibm** [comment]
- waiting SME review

**Comment by gkwan-ibm** [comment]
- addressing SME review feedback

**Comment by gkwan-ibm** [comment]
- addressed SME review feedback but waiting approval

**Comment by gkwan-ibm** [comment]
- should start user review

**Comment by gkwan-ibm** [comment]
- SME approved
- user review in progress

**Comment by gkwan-ibm** [comment]
- need to revise the guide with 2 social providers

**Comment by gkwan-ibm** [comment]
- revised the guide with GH and LinkedIn

**Comment by gkwan-ibm** [comment]
- next final content review
- study logout

**Comment by gkwan-ibm** [comment]
- addressing final content review

**Comment by ankitagrawa** [comment]
- Ready for dev content review.

**Comment by gkwan-ibm** [comment]
- dev content review for logout
  - https://github.com/OpenLiberty/draft-guide-social-login/issues/25

**Comment by gkwan-ibm** [comment]
- next peer review again after review

**Comment by gkwan-ibm** [comment]
- need to externalize the client id, client secret, and url

**Comment by gkwan-ibm** [comment]
- revised the guide to externalize the client id, and client secret
- addressing feedback

**Comment by gkwan-ibm** [comment]
- Peer review after refreshed on draft site
  - Mac + Acrolix (Nimrah)
  - Linux (Griffin)
  - Win (Austin)

**Comment by meswan** [comment]
Addressing YK's comments

**Comment by gkwan-ibm** [comment]
- addressed peer review and YK's feedback

**Comment by gkwan-ibm** [comment]
- ready dev content review
- next resume peer review for Win

**Comment by gkwan-ibm** [comment]
- addressing peer review feedback
- peer review for Win in progress

**Comment by gkwan-ibm** [comment]
- peer review for Win completed with feedback
- addressing peer review feedback

**Comment by meswan** [comment]
Last feedback to be addressed.

**Comment by gkwan-ibm** [comment]
- peer review completed
- next SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- addressing SME review feedback

**Comment by gkwan-ibm** [comment]
- addressed SME feedback and waiting approval

**Comment by gkwan-ibm** [comment]
- proceed to user review

**Comment by gkwan-ibm** [comment]
- user review in progress

**Comment by gkwan-ibm** [comment]
- user reviewed completed
- next final content review

**Comment by gkwan-ibm** [comment]
- removed (R). After review, will ask for the final content review

**Comment by gkwan-ibm** [comment]
- addressing final content review

**Comment by gkwan-ibm** [comment]
- waiting the final content review approval

**Comment by gkwan-ibm** [comment]
- addressing final content review feedback

**Comment by gkwan-ibm** [comment]
- addressing ID review feedback

**Comment by gkwan-ibm** [comment]
- addressed ID review feedback
- final end-to-end test (Griffin)

**Comment by yeekangc** [comment]
Nicely done.  Thank you all!

**Comment by gkwan-ibm** [comment]
The guide was published at https://openliberty.io/guides/social-media-login.html
