### ISSUE TITLE
Migrate Travis CI from `.org` to `.com`

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#169]
Kin Ueng [4:39 PM]
Hi @yeekangc and @evelinec…heads up on TravisCI.  The way we currently use Travis is through a deprecated way (GitHub Services).  Services uses TravisCI `.org`.  Services is doing a partial shutdown down Oct. 1 2018 and  complete turn off on Jan 2019.  We need to migrate to using GitHub Apps.  Using GitHub Apps will move us to TravisCi `.com`

https://developer.github.com/changes/2018-04-25-github-services-deprecation/
I will have to work with admins for the OpenLiberty GitHub organization to authorize the integration of Travis’s GitHub App to our repositories and I assume this will automatically move us from `.org` to `.com`.

**Comment by kinueng** [comment]
I am in the process of getting approval for switching the website repos from `GitHub Services` to `GitHub Apps` for the Travis CI integration.  Once I get a first hands on experience migrating to GitHub Apps and `travis-ci.com`, I will share what it took for me to migrate.

**Comment by gkwan-ibm** [comment]
close
- all guides and daily builds were migrated to use travis-ci.com
