### ISSUE TITLE
Guide sample app code not consistent with Liberty Maven plugin archetype

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#17]
@hughesj  noticed that the application project structure of the REST guide sample app is inconsistent with the Liberty Maven archetype. I'm guessing this is because the REST sample app was based on a starter project from the App Accelerator and maybe that isn't consistent with the Maven archetype?

Do we need to check the packaging structures of all the guide sample apps against the Liberty Maven archetype and update them to be consistent? (Raising here because it potentially affects all guide sample apps so far.)

As an aside, should be document that future guide sample apps should be started from the Liberty Maven archetype project?

**Comment by evelinec** [comment]
@andrewdes can you take a look and put together the list of guides that are impacted. Propose changes via PRs on the guide, and we'll review them. Thanks.

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guides-common/issues/384

**Comment by gkwan-ibm** [comment]
close
- #384 was closed
- all guides should follow the [ideal template ](https://github.com/OpenLiberty/open-liberty/issues/9890)
