### ISSUE TITLE
Remove assemblyArtifact configuration from liberty-maven-plugin

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/guides-common#170]
As of liberty-maven-plugin version 2.6, we have changed the default runtime from WebSphere Liberty to the latest version of the openliberty-runtime. Once the plugin has been updated to the latest version (2.6.1) in all the sample projects, we can remove the `assemblyArtifact` configuration as well.

**Comment by evelinec** [comment]
Moderate severity, ie, to clean up the pom.xml. After the liberty-maven-plugin is upgraded to v2.6.1, this is good to do.

**Comment by gkwan-ibm** [comment]
The guides were updated to use new LMP.  The pom.xml does not use `<assemblyArtifact/>` anymore
