### ISSUE TITLE
Guide for Kube + MP Config

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#173]
Create a guide on how to externalize config with MP Config for a service and work with it in a Kube environment i.e. integrating with Kube's ConfigMap and Secrets.

**Comment by proubatsis** [comment]
Draft repo: https://github.com/OpenLiberty/draft-guide-kubernetes-microprofile-config

**Comment by evelinec** [comment]
@chirp1 This is guide is ready for you. 

Repo: https://github.com/OpenLiberty/draft-guide-kubernetes-microprofile-config

**Comment by evelinec** [comment]
Guide published: https://openliberty.io/guides/kubernetes-microprofile-config.html
