### ISSUE TITLE
Guide for Spring Boot on Open Liberty

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#175]
Create a guide for developing Spring Boot apps with Open Liberty.

This should supersede some of the guides we have in the pipeline for Spring Boot too.  Should go over what's in #63, #79 and #64 to see what's relevant that should still be covered.

**Comment by yeekangc** [comment]
@tjwatson

**Comment by mesutcelik** [comment]
boost plugin was used here in this guide.
https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring/blob/master/finish/pom.xml#L128

**Comment by evelinec** [comment]
- Gilbert is reworking based on SME feedback

**Comment by evelinec** [comment]
Which repo is this guide located?

**Comment by gkwan-ibm** [comment]
- https://github.com/OpenLiberty/draft-guide-spring-boot
- dev and same-pom branch

**Comment by gkwan-ibm** [comment]
- refactoring the solution/flow and the readme

**Comment by gkwan-ibm** [comment]
- first round dev content review completed

**Comment by gkwan-ibm** [comment]
- addressing the dev content review feedback

**Comment by gkwan-ibm** [comment]
- will have the 2nd round  dev content review

**Comment by gkwan-ibm** [comment]
- addressing the 2nd round dev content review

**Comment by gkwan-ibm** [comment]
- addressed the 2nd round dev content review feedback

**Comment by evelinec** [comment]
- addressed all the feedback and re-tested; pending on dev content re-review
- peer review to start - Mai

**Comment by gkwan-ibm** [comment]
- addressed the 3rd round dev content review feedback

**Comment by gkwan-ibm** [comment]
- peer review in progress

**Comment by gkwan-ibm** [comment]
- peer review completed
- will do SME review

**Comment by gkwan-ibm** [comment]
- addressing YK and SME review feedback

**Comment by yeekangc** [comment]
Should have ID review before publishing.

Providing early signoff assuming no further/major issues.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/spring-boot.html.
