### ISSUE TITLE
Testing the multipane design with static guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#176]
The team has been performing testings of converting the guides to multipane design, and raised these feedback issues: https://github.com/OpenLiberty/openliberty.io/issues/449. 

The above issues need to be resolved for further testing.

**Comment by evelinec** [comment]
Assigned issue to @andrewdes as he has been doing the testing and keeping track of the feedback.

**Comment by evelinec** [comment]
The tests were being done with the CDI-intro and FT guides.

**Comment by gkwan-ibm** [comment]
- Identify issues which are not fixed and which are blockers
- Find and try any corner case guides

**Comment by evelinec** [comment]
Instruction: https://github.com/OpenLiberty/guides-common/blob/master/MULTIPANE-CONVERSION.md

**Comment by justineechen** [comment]
Testing the following guides for multipane: 
- [ ] Creating a RESTful service
- [ ] MP JWT 
- [ ] Deploying with Docker

**Comment by justineechen** [comment]
Steven also mentioned this today:

![image](https://user-images.githubusercontent.com/18709242/48355993-4a72fa00-e663-11e8-8262-34f04e6d384f.png)

**Comment by justineechen** [comment]
Individual issues with priorities: (I closed the bigger issue I opened)
https://github.com/OpenLiberty/openliberty.io/issues/774
https://github.com/OpenLiberty/openliberty.io/issues/773
https://github.com/OpenLiberty/openliberty.io/issues/772
https://github.com/OpenLiberty/openliberty.io/issues/771
https://github.com/OpenLiberty/openliberty.io/issues/770

**Comment by justineechen** [comment]
**Guides that have been changed into multipane:**
- Fault Tolerance (Andrew)
- CDI (Andrew)
- Rest intro (Steven) 
- Creating a RESTful service (Justine)
- JWT (Justine) [in progress]

**Comment by gkwan-ibm** [comment]
- all tests done
  - identified the issues
  - some issues already addressed
  - there are 2 blockers
 - working on a summary doc

**Comment by gkwan-ibm** [comment]
- the summary doc is ready
- looking any workaround for the blocking issues

**Comment by evelinec** [comment]
- continue to look for different workaround for the blocking issues
- finish to converting the "getting started" guide
- identify how many guides are impacted by blocker issues
- try converting one of those older guides

**Comment by justineechen** [comment]
Guides that do not have this blocker: 
- Guide-docker 
- Guide-kubernetes-microprofile-config 
- Guide-kubernetes-intro

**Comment by gkwan-ibm** [comment]
- continue to work on the prototype

**Comment by evelinec** [comment]
- continue to work on 4/8 of the prototyping guides

**Comment by gkwan-ibm** [comment]
- prototyped 8/8

**Comment by gkwan-ibm** [comment]
- working on the conversion instruction
- Steven is working on the issue of multi files in same section

**Comment by gkwan-ibm** [comment]
- need to prepare a priority list for tomorrow meeting
- working on the conversion instruction

**Comment by gkwan-ibm** [comment]
- We met UI team on this morning and presented blocker issues
- Kickoff meeting will hold on next Mon
- Need to update the instruction
  - parent pom
  - make mvn and wget to use quiet option

**Comment by gkwan-ibm** [comment]
- conversion instruction is ready
- some UI issues will be fixed

**Comment by justineechen** [comment]
### Checklist for multipane conversion
**Through the browser:**
- [ ] - Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] - Test the actual application (use it, hit endpoints, etc.)
- [ ] - No files in the middle panel (guide section)
- [ ] - Appropriate files are being displayed on the right hand side at the right time
- [ ] - Any mention of code in the right panel should be hot spotted
- [ ] - Make sure hotspots actually point to the correct lines
- [ ] - Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] - All code commands are highlighting the right code
- [ ] - Any actions to look at the code should be a hotspot
- [ ] - Guide attribution is present

**In the README.adoc:**
- [ ] - Tags in the front matter are correct

**In other files:**
- [ ] - Failsafe plugin is there if applicable
- [ ] - Parent POM update
- [ ] - Files are formatted correctly
- [ ] - .travis.yaml file is updated accordingly

**Comment by gkwan-ibm** [comment]
- Attribution issue was fixed (Need to verify)
- Two files in one subsection issue was ready (will verify after committed)
- Question for code_command (Need to reply)

**Comment by evelinec** [comment]
- testing the 2 file in one section fixes

**Comment by evelinec** [comment]
- need to speak to Steven about the 2 new blockers

**Comment by gkwan-ibm** [comment]
Query the multipane UI issues
- https://github.com/OpenLiberty/openliberty.io/issues?q=is%3Aopen+is%3Aissue+label%3Amultipane

**Comment by gkwan-ibm** [comment]
- looking at multimodules guide issue

**Comment by gkwan-ibm** [comment]
- target: 1 high and 4 medium issues will be addressed by the end of this week

**Comment by evelinec** [comment]
- no more priority 1 issue
- 3 medium priority issues

**Comment by evelinec** [comment]
- 4 medium priority issues (some to be closed today)

**Comment by evelinec** [comment]
- 1 new high priority issue 
- 4 medium priority issues

**Comment by evelinec** [comment]
- 1 high priority (empty code pane)
- 2 medium priority issues

**Comment by evelinec** [comment]
- may be a new issue with the opentracing guide

**Comment by evelinec** [comment]
- 2 high priority issues (new issue on the action arrow)
- 2 medium priority issues
- opentracing guide is the one having the replacing file issue (asap)

**Comment by evelinec** [comment]
- 2 high and 2 medium
- opentracing guide replacing file issue is resolved but has a new issue (Steven is working on it)
