### ISSUE TITLE
Guide for deploying Open Liberty to AWS

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guides-common#182]
We need a guide for deploying to AWS due to it's popularity. I recommend doing this with Docker containers but other methods can be used such as using VM's.

**Comment by yeekangc** [comment]
We will focus on containers.

**Comment by gkwan-ibm** [comment]
- drafting

**Comment by gkwan-ibm** [comment]
- the account is frozen

**Comment by gkwan-ibm** [comment]
- will work out the account

**Comment by gkwan-ibm** [comment]
- we have the account
- we can work it on today

**Comment by gkwan-ibm** [comment]
- tried regular CLI way and EKSCTL to create cluster
- successfully deployed the app and running
- scheduled a meeting with YK to discuss

**Comment by gkwan-ibm** [comment]
- working on the draft
- testing on Windows
- trying to use helm

**Comment by evelinec** [comment]
- tested on Windows, everything is good
- helm chart is only supported on IKS and ICP (Artur), not for AWS
- can start create draft repo to push some code

**Comment by gkwan-ibm** [comment]
- investigating the helm chart to work in AWS
   - need to discuss with YK
- the draft repo https://github.com/OpenLiberty/draft-guide-cloud-aws  is ready to continue development
- continue to draft the readme

**Comment by gkwan-ibm** [comment]
- decided not to use helm chart

**Comment by gkwan-ibm** [comment]
- converted to not use helm
- completed the draft
- JC will do the peer review when the draft is ready

**Comment by gkwan-ibm** [comment]
- JC is doing the peer review

**Comment by gkwan-ibm** [comment]
- testing on Mac

**Comment by gkwan-ibm** [comment]
- finished testing on Mac and Win
- some feedback for readme
- will test on Linux

**Comment by gkwan-ibm** [comment]
- peer review finished
- addressing the feedback

**Comment by gkwan-ibm** [comment]
- prepared a PR to address the peer review feedback

**Comment by gkwan-ibm** [comment]
- addressing more peer review feedback
- need to do Acrolinx 
- will convert to use inventory and system microservices

**Comment by evelinec** [comment]
- addressed all peer review feedback, PR is ready for Justine to review
- Andrew to try setup Acrolink today
- app is converted to use the inv ms, updating the readme

**Comment by gkwan-ibm** [comment]
- successfully set up Acrolink, will do the check on today 
- app is converted to use the inv ms, updating the readme

**Comment by gkwan-ibm** [comment]
- conversion was finished, and verifying it
- will run Acrolink on today

**Comment by gkwan-ibm** [comment]
- Acrolink check completed
- GK is reviewing the content

**Comment by gkwan-ibm** [comment]
- working on GK feedback

**Comment by gkwan-ibm** [comment]
- PR for GK feedback is ready for review

**Comment by evelinec** [comment]
- waiting for Gilbert to merge PR
- then SME review (to be found out asap)

**Comment by gkwan-ibm** [comment]
- addressing YK feedback
- SME and User review in progress

**Comment by gkwan-ibm** [comment]
- will address SME and User review feedback

**Comment by evelinec** [comment]
@Charlotte-Holt This guide is ready for you to review. Here's the repo: https://github.com/OpenLiberty/draft-guide-cloud-aws

**Comment by evelinec** [comment]
Expected ID edits by EOD, 5/20.

**Comment by Charlotte-Holt** [comment]
@andrewdes @evelinec My suggestions are in the attached Word document. Please feel free to reach out to me with any questions. Thanks! 
[AWS Guide Comments.docx](https://github.com/OpenLiberty/guides-common/files/3199107/AWS.Guide.Comments.docx)

**Comment by andrewdes** [comment]
Hey @Charlotte-Holt, I have made the edits and opened a PR for your review here: https://github.com/OpenLiberty/draft-guide-cloud-aws/pull/29

**Comment by Charlotte-Holt** [comment]
Looks good, @andrewdes. ID reviewed label added.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/cloud-aws.html.
