### ISSUE TITLE
API dependencies vs ESA dependencies

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#184]
The ESA dependencies make the build files simpler.  Then, they are not public APIs but are specific to Liberty.  Consider if we should use public APIs (and only public APIs) as dependencies instead.

Can the build plugin derives what is needed from the public API dependencies?

This is a feedback/question from @Emily-Jiang.

**Comment by yeekangc** [comment]
@ericglau @patricktiu @gkwan-ibm

**Comment by gkwan-ibm** [comment]
close because all guides were and will be changed to use ideal pom.xml
