### ISSUE TITLE
Guide for deploying Open Liberty to the Azure Cloud

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guides-common#186]
We need a guide for deploying to Azure due to it's popularity. I recommend doing this with Docker containers but other methods can be used such as using VM's.

**Comment by yeekangc** [comment]
We will focus on containers.

**Comment by gkwan-ibm** [comment]
- trying out how to deploy microserivces in Azure Cloud

**Comment by gkwan-ibm** [comment]
- could successfully deploy the app to azure cloud
- start to work on the draft

**Comment by gkwan-ibm** [comment]
dev content review in progress

**Comment by evelinec** [comment]
- addressed all dev content review feedback; pending on Gilbert to review 
- peer review can start - Eveline

**Comment by gkwan-ibm** [comment]
- can do peer review

**Comment by gkwan-ibm** [comment]
- peer review in progress

**Comment by evelinec** [comment]
- follow up SME reviewer(s)
- arrange for final content review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- working on SME feedback

**Comment by evelinec** [comment]
- accounts are requested for Justeen (user review) and Andrew

**Comment by gkwan-ibm** [comment]
- user review in progress

**Comment by gkwan-ibm** [comment]
- user review completed
- will do final content review

**Comment by evelinec** [comment]
- pending on final content review

**Comment by gkwan-ibm** [comment]
- addressing the final content review

**Comment by gkwan-ibm** [comment]
- addressed the final content review feedback
- ID is reviewing

**Comment by gkwan-ibm** [comment]
- addressed the ID review feedback
- will ask for ID to have 2nd review

**Comment by gkwan-ibm** [comment]
- ID 2nd review completed
- can sign-off

**Comment by yeekangc** [comment]
Guide published at https://openliberty.io/guides/cloud-azure.html on August 14th.
