### ISSUE TITLE
Guide for deploying Open Liberty to openshift.io

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guides-common#189]
Our competitors have guides for deploying to different clouds.  We should include openshift.io in the set of public clouds we demonstrate.  This should probably focus on Docker-based deployments.

**Comment by yeekangc** [comment]
We will focus on containers.

**Comment by gkwan-ibm** [comment]
- drafting the guide

**Comment by yeekangc** [comment]
Need to cover the use of operators: https://operatorhub.io/operator/open-liberty

**Comment by evelinec** [comment]
- fixed the problem with the new openshift version
- still have problem accessing the `system` service 
- leave the operators coverage for now
- should be ready for `dev content review` soon

**Comment by gkwan-ibm** [comment]
- target to complete the draft on today

**Comment by gkwan-ibm** [comment]
- dev content review in progress

**Comment by evelinec** [comment]
- addressed dev content review feedback and pending on Gilbert's review
- peer testing on different platforms can start - Danny

**Comment by evelinec** [comment]
- under peer review

**Comment by gkwan-ibm** [comment]
- addressing peer review feedback

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- updated the Win command and completed the peer review feedback

**Comment by evelinec** [comment]
- second SME review is in progress
- have an user that has the cluster provisioned

**Comment by gkwan-ibm** [comment]
- addressing the SME review

**Comment by gkwan-ibm** [comment]
- addressed SME review feedback
- working on user review

**Comment by gkwan-ibm** [comment]
- addressing the user review feedback

**Comment by gkwan-ibm** [comment]
- addressed the user review feedback
- final content review in progress

**Comment by gkwan-ibm** [comment]
- addressing the final content review

**Comment by gkwan-ibm** [comment]
- updated the guide after got the account
- working on the end-to-end test

**Comment by evelinec** [comment]
@Charlotte-Holt This guide is ready for you to review. Here's the repo: https://github.com/OpenLiberty/draft-guide-cloud-openshift/tree/dev

**Comment by gkwan-ibm** [comment]
- end-to-end completed and ready to signoff

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/cloud-openshift.html.
