### ISSUE TITLE
Update appropriate guide to show MP Metrics for Fault Tolerance 1.1

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guides-common#190]
Consider updating one of our existing guides to cover this new capability.  This probably belongs in the Metrics guide because we usually talk about Fault Tolerance before we talk about Metrics.

https://openliberty.io/blog/2018/10/05/microprofile-faulttolerance-1.1-metrics.html

**Comment by yeekangc** [comment]
Need to figure out how best to cover this and whether it would warrant updates to existing guide.  Does it detract from learning goals of the guide?

@Emily-Jiang, feel free to chime in.

**Comment by Emily-Jiang** [comment]
I think when you update the Fault Tolerance guide to use 1.1 version. You can add a link to a blog on FT metrics and also add a paragraph on the metrics aspect as there is no use code needed, just info only.

**Comment by evelinec** [comment]
Just found that mpMetrics-2.0 doesn't provide any metrics for fault tolerance methods. mpMetrics-1.1 version does. Anyone know what may be going on?

**Comment by evelinec** [comment]
The metrics-2.0 issue is related to https://github.com/OpenLiberty/open-liberty/issues/8886.

**Comment by evelinec** [comment]
Tested metrics-2.0 with `cl191020191002-0300` build, it's working as expected.

**Comment by gkwan-ibm** [comment]
- Mai will do the peer view

**Comment by gkwan-ibm** [comment]
- peer view in progress

**Comment by evelinec** [comment]
PR is in https://github.com/OpenLiberty/guide-microprofile-fallback/pull/97. @Azquelt Can you help SME review the changes? Thank you.

**Comment by gkwan-ibm** [comment]
- final review in progress

**Comment by yeekangc** [comment]
Providing early signoff assuming no further/major issues.

**Comment by gkwan-ibm** [comment]
update was published on last night
