### ISSUE TITLE
Guides fails with latest OpenJDK 8 version

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#198]
Problem found on Ubuntu with the following OpenJDK 8 version: 

```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
Notice the build version, `1.8.0_181-8u181-b13-1`. 

The follow version was working with the guides: 
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
The working build version is `1.8.0_181-8u181-b13-0`.

**Comment by proubatsis** [comment]
Test the change proposed in: https://github.com/OpenLiberty/guide-getting-started/pull/35

# Mac

- [ ] Open JDK 8 - Hotspot
- [ ] Open JDK 9 - Hotspot
- [ ] Open JDK 10 - Hotspot
- [ ] Open JDK 8 - Open J9
- [ ] Open JDK 9 - Open J9
- [ ] Open JDK 10 - Open J9
- [ ] Oracle JDK 8
- [ ] Oracle JDK 9
- [ ] Oracle JDK 10
- [ ] IBM JDK 8


# Windows

- [ ] Open JDK 8 - Hotspot
- [ ] Open JDK 9 - Hotspot
- [ ] Open JDK 10 - Hotspot
- [ ] Open JDK 8 - Open J9
- [ ] Open JDK 9 - Open J9
- [ ] Open JDK 10 - Open J9
- [ ] Oracle JDK 8
- [ ] Oracle JDK 9
- [ ] Oracle JDK 10
- [ ] IBM JDK 8


# Ubuntu

- [ ] Open JDK 8 - Hotspot
- [ ] Open JDK 9 - Hotspot
- [ ] Open JDK 10 - Hotspot
- [ ] Open JDK 8 - Open J9
- [ ] Open JDK 9 - Open J9
- [ ] Open JDK 10 - Open J9
- [ ] Oracle JDK 8
- [ ] Oracle JDK 9
- [ ] Oracle JDK 10
- [ ] IBM JDK 8

**Comment by gkwan-ibm** [comment]
- let test the OpenLiberty/guide-getting-started#35  PR

**Comment by proubatsis** [comment]
Running `mvn clean install` on `guide-getting-started` works on the JVMs as outlined above.
