### ISSUE TITLE
Bad cached in the browser that caused JSF exception

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#199]
- Is there a better way to do the redirect to the application page?
- Do we only need to prevent caching to form pages? All pages? A certain subset of pages?

Tentative fix JWT and Securing Web App guides

**Comment by proubatsis** [comment]
![image](https://user-images.githubusercontent.com/8409464/48095575-191da880-e1e3-11e8-95ae-074943264007.png)

This is found on the `application.jsf` page, so it looks like any page with a form may need to be prevented from being cached.

**Comment by proubatsis** [comment]
> Is there a better way to do the redirect to the application page?

I verified that what we are currently doing is fine in this respect.


So the only action that needs to be taken is to apply the changes to prevent caching to the `application.jsf` page as well. I will see if any errors arise as a result of it not being cached first.

**Comment by gkwan-ibm** [comment]
- identified JWT guide need to be updated
- Securing guide may need too

**Comment by proubatsis** [comment]
I was not able to cause any issues without adding the script to the `application.jsf` page, so I do not think it is necessary. As long as the security guide is good too @justineechen I think this issue can be closed.

**Comment by justineechen** [comment]
I haven't been able to create any errors in the security guide with the script either.
