### ISSUE TITLE
Update the `RELEASE` version on dependency management

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#200]
Found this bug about Maven to support version ranges for dependency management. Once fixed, we can update the guides using the deprecated `RELEASE` version that gives warning messages at `mvn install`. 

https://issues.apache.org/jira/browse/MNG-4463

**Comment by gkwan-ibm** [comment]
Currently,
- parent pom version support: RELEASE (deprecated) or a range `[ v1, v2 )` with upper bound
- open liberty plugins version support: RELEASE  (deprecated)  or  a range `[v1, )` without upper bound
- feature bom version support: RELEASE (deprecated)  or a specific version

**Comment by gkwan-ibm** [comment]
close:
- not using parent pom.xml
- updated to use ideal pom.xml with LMP 3.x
  - not using RELEASE anymore
