### ISSUE TITLE
Make sure the start directory is same as the finish directory

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#202]
When create PR, currently, most of the guides will run `mvn install` under the finish directory by Travis. This issue will implement a way to guarantee the start directory is same as the finish directory during PR testing, instead of finding out-of-sync very late by manually check.

**Comment by yeekangc** [comment]
This looks to be a duplicate of #532?

**Comment by yeekangc** [comment]
Closing as a duplicate.  If this is still needed, we can re-open when necessary.
