### ISSUE TITLE
Guide for Google Cloud Platform

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#209]
Guide on how to deploy microservices onto Kubernetes Engine (GKE) on GCP.

Similar in concept to the guides below:
https://openliberty.io/guides/cloud-ibm.html
https://openliberty.io/guides/cloud-aws.html

**Comment by gkwan-ibm** [comment]
- proved the app works on Google cloud
- drafting the Readme

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
@NimG98 you may proceed to
- create draft repo 
- move the content to dev branch
- refresh the draft site
- create travis test

**Comment by ankitagrawa** [comment]
- repo created.

**Comment by gkwan-ibm** [comment]
- peer review
  - Mac (Darren)
  - Linux (Meswan)
  - Win (Danny)

**Comment by gkwan-ibm** [comment]
- ready for dev content review again and SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- addressing the SME review feedback

**Comment by ankitagrawa** [comment]
User review in progress.

**Comment by gkwan-ibm** [comment]
- user review completed and addressing the feedback

**Comment by gkwan-ibm** [comment]
- final content review in progress

**Comment by gkwan-ibm** [comment]
- final content review completed
- asked ID to review

**Comment by ankitagrawa** [comment]
ID review in progress.

**Comment by gkwan-ibm** [comment]
addressing ID and SME feedback

**Comment by gkwan-ibm** [comment]
- ready to publish

**Comment by yeekangc** [comment]
@mstuy signed off.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/cloud-google.html.
