### ISSUE TITLE
Review published guides and identify items for improvements

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#21]
Review the currently published guides and identify anything that should be improved.

For example, consider if we should have diagrams as part of introduction to better illustrate what the guides and/or the samples will talk about.  Or, any reorganization or structure improvements that we should do.

- Creating JAX-RS
- Maven
- MicroProfile Intro
- HATEOAS
- Multi-Modules
- CORS
- Consuming REST from Java
- Consuming REST from AngularJS

**Comment by Kubik42** [comment]
**Progress**:
- removed leftover branches

**Comment by Kubik42** [comment]
@yeekangc everything has been reviewed. I'm thinking of making PRs with the changes for the guides. What do you think?

**Comment by yeekangc** [comment]
@Kubik42, we can have PRs with the changes for reviews and go from there.

Some of what you are suggesting involve changes to the writing style of the guides.  We will need to work with @lauracowen @sishida @bcpswope further to come to a conclusion.

**Comment by evelinec** [comment]
@Kubik42 is there more work for this issue?

**Comment by Kubik42** [comment]
@evelinec None of the PRs listed here have actually been merged. We held off doing that because we were going through layout changes at the time. I guess, the best course of action is to open new PRs that will include the old changes + new changes for layout stuff.

**Comment by evelinec** [comment]
@Kubik42 Since this issue is in the current high priority in progress list, can you see if we can wrap up with some of the changes made so far? We will revisit via new issues when the new layout is ready.

**Comment by Kubik42** [comment]
I'll wait until the new layout is out, then rollout the changes.

**Comment by Kubik42** [comment]
Reassigning to @andrewdes as he will be taking over the multipane work.

**Comment by yeekangc** [comment]
Closing for what was done was completed.
