### ISSUE TITLE
Test automation script should update the RELEASE in the pom.xml for daily build tests

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#214]
Now, the test automation script only insert the \<runtimeUrl\>. It is not enough. It should update RELEASE to the right version.

Make sure:
- [ ] the latest (build level) OL version is used 
- [ ] the latest feature versions are used

**Comment by evelinec** [comment]
- starting to work on it

**Comment by evelinec** [comment]
This request is more complicated and needed further discussions.

**Comment by evelinec** [comment]
Logging some discussion with the install feature team: 

We'll need build the repository structures for the following two zip files (from libertyfs) and then adjust the pom to get the features from the constructed repository: 
- wlp-repo-cl190320190318-0300.zip 
- mavenArtifact.zip 

Here's some pom config instruction: 
https://maven.apache.org/guides/mini/guide-multiple-repositories.html
