### ISSUE TITLE
Categorisation of guides

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#216]
In a design call we discussed the categorisation of the guides and I think @cajaygle agreed we could move the MicroProfile category to the top (above the 'get started' one, which isn't as relevant as the MicroProfile one for getting started writing microservices with MP and OL). I don't think there were any objections to doing this but I don't think there was an issue to do it.

@cajaygle Are you still fine with this being done?

**Comment by yeekangc** [comment]
Closing as duplicate.
