### ISSUE TITLE
Create guide for MicroProfile Concurrency, or include in a related guide

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/guides-common#219]
On the WAD call for MicroProfile Concurrency, it was discussed that MicroProfile Concurrency could be covered within another guide (MicroProfile Fault Tolerance or JAX-RS) or create a separate guide for it.  It looks like there are several issues already opened to create JAX-RS guides, including https://github.com/OpenLiberty/guides-common/issues/118 which covers the reactive client, which has some similarities in the usage of CompletableFutures.  There is also a MicroProfile Fault Tolerance guide, https://openliberty.io/guides/bulkhead.html, which currently appears to recommend some bad practices around creating your own thread pools. This would be an excellent candidate to switch over to using MicroProfile Concurrency.

**Comment by yeekangc** [comment]
@mbroz2 @kinueng, please see comments above re Bulkhead guide.

**Comment by yeekangc** [comment]
We need to work out what's relevant and where to best cover what is needed before we can prioritize.

**Comment by mbroz2** [comment]
After discussion with @njr-11 we'll plan on updating the [bulkhead guide](https://openliberty.io/guides/bulkhead.html) to leverage MP Concurrency once it's been released.

**Comment by lauracowen** [comment]
@njr-11 @yeekangc As MP Context Progation (new name) is now out, will the bulkhead guide be updated?

**Comment by njr-11** [comment]
> @njr-11 @yeekangc As MP Context Progation (new name) is now out, will the bulkhead guide be updated?

@mswatosh from my team has been working on guide updates for MP Context Propagation

**Comment by mbroz2** [comment]
Yes, @mswatosh has already updated the bulkhead guide and has been waiting for me to finish code reviewing it so that it can be delivered.  The PR is here: https://github.com/OpenLiberty/iguide-bulkhead/pull/177

**Comment by lauracowen** [comment]
@dmuelle Can you add to the MP CP topic a link to the bulkhead guide as an example of MP CP? When the new MP CP guide is done, we can link to that too.

**Comment by dmuelle** [comment]
@lauracowen link has been added to the MP CP topic currently building on draft

**Comment by yeekangc** [comment]
Thanks.  We have it covered at least in the interactive guide for FT/Bulkhead.  If we feel that we should have a dedicated static guide for it still, we can discuss.

**Comment by gkwan-ibm** [comment]
close
- MicroProfile Concurrency was archived
- published several guides for [MicroProfile Reactive Messaging](https://openliberty.io/guides/?search=reactive)
- published a [Consuming RESTful services asynchronously with template interfaces](https://openliberty.io/guides/microprofile-rest-client-async.html) guide
- have the [issue](https://github.com/OpenLiberty/guides-common/issues/896) for Jakarta Concurrency
