### ISSUE TITLE
Create a guide for MicroProfile JWT Propagation

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#22]
Create a guide on how to use MicroProfile JWT Propagation.

**Comment by evelinec** [comment]
Adding "ID require" tag for team to plan. 
Repo link will be added when guide is ready for ID review.

**Comment by evelinec** [comment]
@sishida The JWT guide is ready for some ID review. 
Repo link: https://github.com/OpenLiberty/draft-guide-microprofile-jwt

@JunyiSun FYI.

**Comment by sishida** [comment]
@evelinec and @JunyiSun:
Overall I thought it was good. :) I made some minor edits in a pull request here: https://github.com/OpenLiberty/draft-guide-microprofile-jwt/pull/22
Thank you!

**Comment by sishida** [comment]
@evelinec and @JunyiSun:
I ran the grammar checker and made a few more changes: https://github.com/OpenLiberty/draft-guide-microprofile-jwt/pull/24/files#diff-7bd4a925c695c2eb0eced3872b9b965f Thank you!

**Comment by yeekangc** [comment]
https://openliberty.io/guides/microprofile-jwt.html
