### ISSUE TITLE
Guides for Caching in Microservices with Hazelcast

### ISSUE THREAD

**Issue by mesutcelik** [OpenLiberty/guides-common#229]
I am planning to write a guide for Hazelcast+SpringBoot + OpenLiberty deployed to Kubernetes. They are going to be around those tech but can be changed while preparing the guide.

I checked the guide wiki and understand that I need to first create a repo under my account and work on it. Is there any other thing that I should be aware of?

**Comment by evelinec** [comment]
Hi @mesutcelik, welcome and thank you for contributing a guide! Here's a template with instructions on how to get started: https://github.com/OpenLiberty/draft-guides-template. Feel free to let us know if you have any questions.

**Comment by mesutcelik** [comment]
Hi again,

I have completed the guide. 
https://github.com/mesutcelik/hazelcast-springboot-openliberty

Can you please review and let me know if you have any feedback? I have gone through a few times and I really need some other pair of  eyes... 👀

Guide uses following technologies

- Hazelcast
- Spring Boot
- OpenLiberty
- Minikube
- Kubernetes
- boost-maven-plugin
- hazelcast-kubernetes plugin

**Comment by yeekangc** [comment]
@evelinec @gkwan-ibm ^^^

**Comment by aguibert** [comment]
@yeekangc @gkwan-ibm can we start by making a repo for this guide under the OpenLiberty org, then @mesutcelik can make a PR to that repo and we can more easily leave comments on the content

**Comment by evelinec** [comment]
Hi @mesutcelik, thank you for providing the draft content. We're reviewing it. We'll get back to you soon.

**Comment by evelinec** [comment]
Hi @mesutcelik, we'll proceed making a repo for this guide under the OpenLiberty organization for you to make a PR to the repo. In terms of the content, we believe that the guide should also cover Java EE and MicroProfile. What do you think?

**Comment by mesutcelik** [comment]
Thanks @evelinec for taking care of that.

> In terms of the content, we believe that the guide should also cover Java EE and MicroProfile. What do you think?

It is possible but I feel like it is too much for the same guide. I can create separate but similar one for Microprofile if you want.

**Comment by evelinec** [comment]
Thank you @mesutcelik. We can go with two separate guides. 

Here's the repo under the OpenLiberty organization: https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring, would you create a PR to this repo with the Spring Boot content? 

Let us know when you have the MicroProfile one ready. Thank you.

**Comment by mesutcelik** [comment]
I will have a look when I can find time to create another one but it shouldn't be long. Current structure  can easily be adapted to Microprofile. Can you also share some other guides you think I can check?

I also checked the repo you mention but I can't fork it. It says it is empty. I think you need to push at least a file like a LICENSE file.

**Comment by evelinec** [comment]
Sorry @megmulsy, the repo is now activated with an initial file. 

We have a series of MicroProfile guides on our [Open Liberty guides website](https://openliberty.io/guides/?search=microprofile&key=tag) about MicroProfile technologies. Let us know what you find out, and we discuss further. Thank you.

**Comment by evelinec** [comment]
Thank you @mesutcelik for submitting the PR. We're reviewing it, and will provide feedback and move forward soon. 

The next steps are to go through a series of reviews and tests for this draft content, before it'll be published. As well, we would like to get the guide with the MicroProfile technologies, and align publishing these two guides together.

**Comment by gkwan-ibm** [comment]
- created the dev branch for development
- EC is converting the readme to multipane style

**Comment by evelinec** [comment]
Hi @mesutcelik, I'd like to let you know we merged the initial PR from you. Thank you.  

Also, we created a number of issues on the guide's repo to do he reviews and tests. Feel free to check them out. I want to point out one of the issue, https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring/issues/3, which is to convert the guide to our new multipane design. We need to do this first, in order for the guide's content to show up entirely on our website. Let us know if you'd like to do this. I can also help with this task. 

Another note, create PR against the `dev` branch for any new changes. The `master` branch is reserved for publishing content.

**Comment by mesutcelik** [comment]
> Hi @mesutcelik, I'd like to let you know we merged the initial PR from you. Thank you.

you are very welcome!

> 
> Also, we created a number of issues on the guide's repo to do he reviews and tests. Feel free to check them out.

I will have a look at the issues.


>  I want to point out one of the issue, [OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring#3](https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring/issues/3), which is to convert the guide to our new multipane design. We need to do this first, in order for the guide's content to show up entirely on our website. Let us know if you'd like to do this. I can also help with this task.

I would be happy if you can convert to multipane. I will be for sure using multipane in the new guide that I am going to prepare.

> 
> Another note, create PR against the `dev` branch for any new changes. The `master` branch is reserved for publishing content.

👍

**Comment by mesutcelik** [comment]
> We would like to consider both a guide using Spring Boot and another guide using EE/MicroProfile.

I see. I think that is what we already agreed. 

Btw, I have checked the issues and they are mostly review related stuff so I can't do anything over there. Howevew, I tweeted for the reviewer search. feel free to retweet.
https://twitter.com/mesutcelik/status/1110536028320907265

**Comment by yeekangc** [comment]
Yes, @mesutcelik.  That's what we agreed upon.  Just thought to make a note as I updated the issue title.  Looking forward to what you have for EE/MicroProfile.

We will progress what we can with the issues and will reach out if we need help.  Thank you for the tweet for reviewer.

**Comment by evelinec** [comment]
Hi @mesutcelik, we have a question to ask you. Our guide has an attribution statement, ie, `Caching Microservices with Hazelcast in Kubernetes by {guide-author} is licensed under CC BY-ND 4.0`. As with the {guide-author} field, do you want to state your name or your company's name? Thank you.

**Comment by mesutcelik** [comment]
Both is fine by me.

**Comment by evelinec** [comment]
Hi Mesut, we recently ran the build on this guide and found a problem, this issue https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring/issues/11 was opened. Do you think you'd like to take a look? @mesutcelik Thanks.

**Comment by evelinec** [comment]
Hi Mesut, we had also review the content of the guide and had some feedback that we would like to improve for this guide. Would you take a look at issue https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring/issues/12, and let us know what you think? @mesutcelik Thank you.

**Comment by mesutcelik** [comment]
Hi @evelinec , I will probably have a look at them next team... Thanks for update!

**Comment by evelinec** [comment]
Hi @mesutcelik, have you had a chance to take a look at the two issues?

**Comment by mesutcelik** [comment]
Hi @evelinec ,
I sent a PR for README update.
https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring/pull/13

The other issue in fact is related to boost maven plugin. I think we need to wait for a new release.
More info is [here](https://github.com/OpenLiberty/draft-guide-kubernetes-caching-hazelcast-spring/issues/11#issuecomment-488395893).

**Comment by evelinec** [comment]
Hi @mesutcelik, sorry for the delay in responding to your PR. We'll get back to you in the next few days.

**Comment by gkwan-ibm** [comment]
- Need to resolve open issues #12
- Should have similar guide for Java EE / MicroProfile
- Help wanted for outstanding work

**Comment by yeekangc** [comment]
Hazelcast team now has a set of guides at https://guides.hazelcast.org/home/.

**Comment by yeekangc** [comment]
We will close this for now.  The issue can be re-opened and revisited if necessary.
