### ISSUE TITLE
Create a guide for MicroProfile OpenAPI

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#23]
Create a guide on how to use MicroProfile OpenAPI.

**Comment by yeekangc** [comment]
@arturdzm has kindly volunteered to contribute to this guide.

**Comment by evelinec** [comment]
ID review is in progress, thanks @sishida 
Repo link: https://github.com/OpenLiberty/draft-guide-microprofile-openapi

**Comment by yeekangc** [comment]
https://openliberty.io/guides/microprofile-openapi.html
