### ISSUE TITLE
The guide's searching mechanisms need improvement

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#232]
The current behavior for tags is basically, we only show a select list of tags, all the other tags are hidden.  All tags, visible and hidden, are used in the guide search bar.  The search bar is a simple String.contain(“your search term”) against the guides’ title, description, visible and hidden tags.

Currently the list of visible tags are https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid. All of the static guides are revised to use only these visible tags. With these changes, some of the guides, ie, cdi-intro, are NOT searchable by the acronym term, ie, CDI. 

Current searching problems: 
1. Search "CDI" and the "cdi-intro" guide does not show up.
2. Search "client" and only 1 out of the 3 client guides showed up. 
(The MP REST client guide shows up, but the client-java and client-angularjs guides do not.)
3. Search "REST" and 7 guides show up compare to 9 in today's ol.io site. 

The direction is that the guides do NOT want to be clustered with any additional tags apart from those visible ones in the link. Thus, we need to improve guide's search-ability in other areas..

**Comment by evelinec** [comment]
@yeekangc @kinueng

**Comment by mbroz2** [comment]
Hidden tags are the current strategic approach for exposing resources (like guides) through search.  Once site-wide search is implemented, it is expected to leverage hidden tags not only in guides but other site resources like blogs.
The statement for guide authors(and in the future, other authors like blog) is: "Add tags relevant to your [guide/blog/etc].  All tags will be searched on, but only the tags listed [**here**](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid) will be visible in the guide"

**Comment by gkwan-ibm** [comment]
@mbroz2  Can the guide site search for an additional field? Instead of putting back the removed tags into the page-tags field, can we add a new field, e.g. page-search-keywords, into the guides, and let the search engine to search that additional field?

**Comment by mbroz2** [comment]
If that simplified things for the static guides, than we could enable that on our end (site wise, it would just be another list of hidden tags).  However, I'm not sure I understand what we would be gaining by introducing the extra list of labels (prior to this work item, the use of labels was the same for both static and interactive guides and, for simplicity, I would like to keep them in sync)

**Comment by gkwan-ibm** [comment]
IMO, a new field will make the contributors (from IBM or non-IBM) more clear. They may not know what is visible/hidden tag and what they mean. Also, if using page-tags only, after a while, whoever read the raw version of the README.adoc, they may not know which are the visible tags and which not.

**Comment by yeekangc** [comment]
+1 for site-wide search and I presume this is a priority issue tracked separately.

In terms of tags, my take is that we should have a mechanism where tags can be managed outside of the individual documents especially for guides that is easy to use and manage so as guides and our tagging/categorisation evolve, updating them for multiple tags is simple.  The individual documents can provide a default set of tags from a defined list but we need flexibility to update over time without having to update multiple repos and multiple documents manually.

For using hidden tags for searching, my take is (1) we do site-wide search right and (2) if we need to use such a mechanism, I am for a different attribute or field like keywords than tags too.  Using tags particularly hidden vs non-hidden tags will be confusing to contributors and difficult to manage over time.  You will need tags, definitions of hidden vs non-hidden somewhere and also what's the latest values etc.

As an aside, I do believe we need to clean up our current hidden tags if they are meant to be used.  I don't think we have done them with any principle in mind and to facilitate site searching.

**Comment by mbroz2** [comment]
Based on our discussion, closing this issue as it's currently unknown if there will be any action to take in the short term (if search tags/keywords are added under a new param, please open a new issue for that and we'll integrate them into search).  I'll open a new issue for single-file tag management, which is the longer-term solution to this problem.

**Comment by yeekangc** [comment]
And, we should have separate issue for site-wide search already.

**Comment by evelinec** [comment]
Opened #234.

**Comment by mbroz2** [comment]
Correct, site-wide search is here: https://github.com/OpenLiberty/openliberty.io/issues/288

**Comment by evelinec** [comment]
As discussed with YK today, here's some current actions to help with this issue: 
- put some meaningful tags back to the guide
- where, 1) new field or 2) in the title and/or description fields
