### ISSUE TITLE
Add tags/keywords under a new param for searching

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#234]
Refer to #232.

**Comment by yeekangc** [comment]
@evelinec @gkwan-ibm, we can use this issue to delineate what needs to be done short term and longer term to resolve what was reported in #232.

**Comment by evelinec** [comment]
@kinueng can you assign this item to your team, as we decided to do this to help with the searching issues in the short term. See issue #232. Thank you.

**Comment by evelinec** [comment]
@gcharters reported a searching issue on the "HATEOAS" guide, https://github.com/OpenLiberty/guide-rest-hateoas/issues/44.

**Comment by yeekangc** [comment]
Quick fix for CDI guide: https://github.com/OpenLiberty/guide-cdi-intro/pull/91

**Comment by steven1046** [comment]
The new guide metadata is:
```:page-search-keywords: ['phrase1','phrase2']```

**Comment by evelinec** [comment]
FYI, I'm testing these new guide metadata now.

**Comment by steven1046** [comment]
They aren't in master yet, I'm trying to get it into master today.

**Comment by evelinec** [comment]
I'm testing the `development` branch. Will it work? @steven1046

**Comment by evelinec** [comment]
Seems working! :)

**Comment by steven1046** [comment]
Yes

**Comment by steven1046** [comment]
@evelinec it's in master now so it will work on the QA and draft sites.

**Comment by evelinec** [comment]
Team is working on the search keywords for all the guides and will update them once ready.

**Comment by evelinec** [comment]
This task is complete. Guides can add search keywords as appropriate.
