### ISSUE TITLE
Manual tests for the guides for 19002 candidate build

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#235]
Manual test the guides against 19.0.0.2 GM master, Java11OpenJ9
- [x] Getting Start (Gilbert)
- [x] Kube Intro (Andrew)
- [x] Gradle (Andrew)
- [x] Maven (Panagiotis)
- [ ] JWT (Panagiotis)
- [x] Arquillian - candidate draft guide (Eveline)

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform

**Comment by evelinec** [comment]
Arquillian tests: 
- automated tested with oraclejdk8 and openjdk11
- manually tested with adoptedopenj8jdk11 (version info below)

JDK11OpenJ9 version:
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.1, JRE 11 Mac OS X amd64-64-Bit 20190205_112 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - 289c70b684 based on )

**Comment by proubatsis** [comment]
JDK 11 + 19.0.0.2 Fails on master
JDK 11 + 19.0.0.1 Fails on master
JDK 11 + 19.0.0.1 Fails on multipane

Go to finish directory, run `mvn clean install liberty:start-server`, login with credentials `bob`/`bobpwd`, and the following error is shown. This error does not occur with JDK 8.

![image](https://user-images.githubusercontent.com/8409464/53458629-ebb07100-3a04-11e9-8b71-30821c000e38.png)

**Comment by yeekangc** [comment]
Does multi-module work or that's a known failure with 19002 as well as Java 11?  Like https://github.com/OpenLiberty/guide-maven-multimodules/issues/34, @proubatsis?

**Comment by evelinec** [comment]
> JDK 11 + 19.0.0.2 Fails on master
> JDK 11 + 19.0.0.1 Fails on master
> JDK 11 + 19.0.0.1 Fails on multipane
> 
> Go to finish directory, run `mvn clean install liberty:start-server`, login with credentials `bob`/`bobpwd`, and the following error is shown. This error does not occur with JDK 8.
> 
> ![image](https://user-images.githubusercontent.com/8409464/53458629-ebb07100-3a04-11e9-8b71-30821c000e38.png)

@proubatsis I also ran into this problem on my Mac when testing 19001 with JDK11. Try open the url in a private window. That resolved my problem on Mac. The same error was found on Windows, but I think we didn't continue the investigation (@andrewdes and @gkwan-ibm can add more on that).

**Comment by proubatsis** [comment]
@evelinec Private window did not fix the issue for me, only JDK 8 fixed it for me.

**Comment by evelinec** [comment]
@proubatsis I just tested this build, Open Liberty 19.0.0.2/wlp-1.0.25.cl190220190222-1311 on Eclipse OpenJ9 VM, version 11.0.2+9 (en_CA), I don't see the problem, even on a non private window.

**Comment by evelinec** [comment]
@proubatsis For the failures you mentioned for the JWT guide, are there other issues than the UI problem? Referring to:

```
JDK 11 + 19.0.0.2 Fails on master
JDK 11 + 19.0.0.1 Fails on master
JDK 11 + 19.0.0.1 Fails on multipane
```

**Comment by proubatsis** [comment]
@evelinec 
After a bit more investigation, it turns out that the issue seems to occur mainly on JDK 11.0.1, I have not been able to reproduce it on 11.0.2.

**Comment by proubatsis** [comment]
Tracking this issue in https://github.com/OpenLiberty/guide-microprofile-jwt/issues/88
