### ISSUE TITLE
Gathering test runtime logs depends on the test result

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#237]
The automated test gathers test runtime logs after each test and send it to the artifactory as a storage. The mechanism relies on the test to be successful and able to gather the release and build number info, which is extracted from the server's console.log. When the test fails to produce the console.log, these information is unavailable. Thus collecting the runtime logs mechanism will not function correctly. It tries to collect all the contents in the current working directory, which can be very huge. Thus causing the `This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log. ` error on Travis. 

```
OpenLiberty release: 
Open Liberty build number: 
Java version: 
```

[ERROR] Failed to execute goal net.wasdev.wlp.maven.plugins:liberty-maven-plugin:2.6.4:install-server (create-server) on project ServletSample: java.net.SocketException: Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command "sed -i "\#<assemblyArtifact>#,\#</assemblyArtifact>#c<install><runtimeUrl>https:\/\/public.dhe.ibm.com\/ibmdl\/export\/pub\/software\/openliberty\/runtime\/nightly\/2019-03-02_2028\/openliberty-all-19.0.0.3-cl190220190302-1901.zip<\/runtimeUrl><\/install>" pom.xml; cat pom.xml; mvn -q clean install;" exited with 1.
0.01s$ logsPath=$(find . -name "console.log" | sed "s/console.log//g");
The command "logsPath=$(find . -name "console.log" | sed "s/console.log//g");" exited with 0.
0.02s$ build=$(grep "Open Liberty" $logsPath/console.log | cut -d" " -f5 | cut -d")" -f1 ); release=$( echo "$build" | cut -d"/" -f1); number=$(echo "$build" | cut -d"/" -f2); ol_jv=$(grep -i "on java" $logsPath/console.log); jv=$(echo "$ol_jv" | sed "s/.* on //g"); echo -e "\n"; echo -e "\033[1;34mOpenLiberty release:\033[0m \033[1;36m$release\033[0m"; echo -e "\033[1;34mOpen Liberty build number:\033[0m \033[1;36m$number\033[0m"; echo -e "\033[1;34mJava version:\033[0m \033[1;36m$jv\033[0m";
grep: /console.log: No such file or directory
grep: /console.log: No such file or directory
OpenLiberty release: 
Open Liberty build number: 
Java version: 
The command "build=$(grep "Open Liberty" $logsPath/console.log | cut -d" " -f5 | cut -d")" -f1 ); release=$( echo "$build" | cut -d"/" -f1); number=$(echo "$build" | cut -d"/" -f2); ol_jv=$(grep -i "on java" $logsPath/console.log); jv=$(echo "$ol_jv" | sed "s/.* on //g"); echo -e "
"; echo -e "OpenLiberty release: $release"; echo -e "Open Liberty build number: $number"; echo -e "Java version: $jv";" exited with 0.
$ cd $logsPath; repo_name=$(echo "$TRAVIS_REPO_SLUG" | sed -e "s/\//-/g"); if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then result="passed"; else result="failed"; fi; serverlogsarchive="$repo_name-$TRAVIS_BUILD_NUMBER-$result.zip";zip -r "$serverlogsarchive" .; curl -H "$JFROG_TOKEN" -T "$serverlogsarchive" "https://na.artifactory.swg-devops.com/artifactory/hyc-openliberty-guides-files-generic-local/";
	zip warning: name not matched: .kiex/elixirs/.default.fish
	zip warning: name not matched: .kiex/elixirs/.default.csh
	zip warning: name not matched: .phpenv/versions/hhvm-stable/bin/php
	zip warning: name not matched: .phpenv/versions/hhvm/bin/php
  adding: .travis_packer_templates_rspec.json (deflated 93%)
  adding: .local/ (stored 0%)
  adding: .local/share/ (stored 0%)
  adding: .local/share/composer/ (stored 0%)
  adding: .local/share/composer/.htaccess (stored 0%)
  adding: .local/share/heroku/ (stored 0%)
  adding: .local/share/heroku/plugins/ (stored 0%)
  adding: .local/share/heroku/plugins/node_modules/ (stored 0%)
  adding: .local/share/heroku/plugins/node_modules/.yarn-integrity (deflated 33%)
  adding: .local/share/heroku/plugins/package.json (stored 0%)
  adding: .local/share/heroku/plugins/yarn.lock (deflated 7%)
  adding: .profile (deflated 46%)

**Comment by yeekangc** [comment]
The error at the end of the raw log is this: “The job exceeded the maximum log length, and has been terminated”

**Comment by gkwan-ibm** [comment]
close
- test is migrating to us Github action, the console output should be captured by the framework and OL logs files can be attached to the build result
