### ISSUE TITLE
Improve test reporting mechanism

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#238]
YK: We can consider better reporting too -- both the mechanism as well as how results are presented.  A status summary will be nice if the team would like folks like me to ignore these notifications.

**Comment by yeekangc** [comment]
- Provide summaries of results besides individual notifications of failures on Slack
- Provide updates for re-runs and indication of re-runs for failed runs too

**Comment by evelinec** [comment]
Some detail expectations for the above 2 points: The better reporting issue should help with solving some of these false alarms and ensuring that reruns will be considered.

**Comment by gkwan-ibm** [comment]
close
- test are migrating to Github actions
