### ISSUE TITLE
Update MP Rest Client guide with new 1.2/1.3 features

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#240]
Raised by @andymc12 [moved here from the Docs backlog]:

The existing MP Rest Client guide ( https://openliberty.io/guides/microprofile-rest-client.html ) uses MP Rest Client 1.1 APIs, and with MP Rest Client 1.2 about to release, we should probably update the guide to take advantage of some of the new features in 1.2 - specifically:

 -   adding the URI directly in the @RegisterRestClient annotation on the rest client interface
 -  using the new @ClientHeaderParam annotation to send hardcoded or computed HTTP headers

Most of the other features in 1.2 are used for integration with other technologies like MP Open Tracing or MP Fault Tolerance. These features could be added in different guides that focus on these other technologies.

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guide-microprofile-rest-client/issues/70

**Comment by andymc12** [comment]
I'm thinking we should probably update the guides to 1.3 (which builds on the 1.2 changes), and adds:
* portable SSL APIs - this might be something to mention, but not necessary change the samples?
* configKeys - this is a nifty feature to configure multiple rest client interfaces with a single config line
* rest client interfaces can extend (or be casted to) Closeable/AutoCloseable allowing the user to control when the client is closed (and resources cleaned up)
* default MIME types when not specified by the app is now `application/json` - if any of the samples do not specify `@Produces(...)` and `@Consumes(...)`, then should be updated to do so.

Hope this helps

**Comment by evelinec** [comment]
- peer review - Danny

**Comment by yeekangc** [comment]
Providing early signoff assuming no further/major issues.

**Comment by gkwan-ibm** [comment]
update was published on last night
