### ISSUE TITLE
Provide setup local dev site instruction for contributor

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#241]
For the instruction Step 4.2, should we point contributor to the setup local dev site wiki to develop readme? https://github.com/OpenLiberty/openliberty.io/wiki/Setting-up-local-website-development

Note, the link above need some work to make it targeted for setting the dev site environment for guides.

**Comment by yeekangc** [comment]
Related to https://github.com/OpenLiberty/guides-common/issues/207.  May be a duplicate of each other?

**Comment by gkwan-ibm** [comment]
close
- duplicate of #207
