### ISSUE TITLE
Creating Docker image of your app

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#242]
From @gcharters:

We have a Docker guide that focuses on how to develop apps using Docker. But there's a gap in the story where we don't have a guide to show how to create a Docker image that you can then deploy into Kubernetes.

At conferences, Graham uses the guides to show the end-to-end story of writing, deploying, and managing microservices in the cloud: https://github.com/gcharters/workshop-cloud-native-java There's currently a gap in the story before the Kubernetes guide where there should really be one about creating the Docker image.

**Comment by yeekangc** [comment]
Can we leverage Boost for this?  @scottkurz, any thoughts?

@charters @NottyCode, what do you think?

**Comment by gkwan-ibm** [comment]
- created the draft repository https://github.com/OpenLiberty/draft-guide-microservices-docker
- working on the ReadMe

**Comment by evelinec** [comment]
- finishing the first draft, inform team when ready
- peer review and CNAI content review are the next actions

**Comment by gkwan-ibm** [comment]
- fixing the inventory/system 
- will address Gilbert feedback

**Comment by gkwan-ibm** [comment]
- Peer review in progress

**Comment by gkwan-ibm** [comment]
- completed peer review on Linux and Mac, and will do on Windows

**Comment by gkwan-ibm** [comment]
- peer view done
- automation is completed
- will do CNAI content review

**Comment by gkwan-ibm** [comment]
- dev content review in progress

**Comment by gkwan-ibm** [comment]
- should start the SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
User review in progress

**Comment by gkwan-ibm** [comment]
final content review in progress

**Comment by gkwan-ibm** [comment]
- addressing feedback from YK and Emily

**Comment by gkwan-ibm** [comment]
- doing end to end test

**Comment by evelinec** [comment]
- finished end to end test and addressed feedback
- ready for ID today

**Comment by evelinec** [comment]
- working on re-writing the descriptions for the docker-intro guide

**Comment by gkwan-ibm** [comment]
- need to address https://github.com/OpenLiberty/draft-guide-microservices-docker/issues/14 before publish

**Comment by gkwan-ibm** [comment]
- NG and JC will do  pre-publish test
- JC will prepare PR for the original docker guide

**Comment by gkwan-ibm** [comment]
- GK will publish the guide on today

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/containerize.html.
