### ISSUE TITLE
Update error message in InventoryResource to display in JSON

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guides-common#243]
Guides affected: 
- [x] guide-microprofile-opentracing (Tiago)
    - https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/99
- [x] guide-microprofile-openapi (Austin)
    - https://github.com/OpenLiberty/guide-microprofile-openapi/pull/92
- [x] guide-microprofile-config (Tiago)
    - https://github.com/OpenLiberty/guide-microprofile-config/pull/144
- [x] guide-microprofile-fallback (Austin)
    - https://github.com/OpenLiberty/guide-microprofile-fallback/pull/134
- [x] guide-microprofile-health (No need to update)
    - https://github.com/OpenLiberty/guide-microprofile-health/pull/80
- [x] guide-microprofile-jwt (Tiago)
    - https://github.com/OpenLiberty/guide-microprofile-jwt/pull/114
- [x] guide-microprofile-metrics (Tiago)
    - https://github.com/OpenLiberty/guide-microprofile-metrics/pull/109
- [x] guide-microprofile-rest-client (Tiago)
    - https://github.com/OpenLiberty/guide-microprofile-rest-client/pull/124
- [x] guide-okd (Tiago)
    - https://github.com/OpenLiberty/guide-okd/pull/37
- [x] guide-cloud-openshift (Tiago)
    - https://github.com/OpenLiberty/guide-cloud-openshift/pull/57
- [x] guide-containerize (Tiago)
    - https://github.com/OpenLiberty/guide-containerize/pull/41
- [x] guide-cloud-google (Tiago)
    - https://github.com/OpenLiberty/guide-cloud-google/pull/26
- [x] guide-cloud-ibm (Tiago) 
    - https://github.com/OpenLiberty/guide-cloud-ibm/pull/88
- [x] guide-kubernetes-intro (Austin)
    - https://github.com/OpenLiberty/guide-kubernetes-intro/pull/146
- [x] guide-kubernetes-microprofile-config (Austin)
    - https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/pull/102
- [x] guide-cloud-aws (Tiago)
    - https://github.com/OpenLiberty/guide-cloud-aws/pull/89
- [x] guide-microprofile-istio-retry-fallback (Austin)
    - https://github.com/OpenLiberty/guide-microprofile-istio-retry-fallback/pull/47
- [x] guide-cdi-intro (Austin)
    - https://github.com/OpenLiberty/guide-cdi-intro/pull/151
- [x] guide-kubernetes-microprofile-health (Austin)
    - https://github.com/OpenLiberty/guide-kubernetes-microprofile-health/pull/93

Will be done by other issue:
- guide-microprofile-rest-client-async
- guide-arquillian-managed

**Comment by gkwan-ibm** [comment]
see https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/62

**Comment by gkwan-ibm** [comment]
Update the InventoryResource
```
    public Response getPropertiesForHost(@PathParam("hostname") String hostname) {
        Properties props = manager.get(hostname);
        if (props == null) {
            return Response.status(Response.Status.NOT_FOUND)
                           .entity("ERROR: Unknown hostname or the system service may " 
                                 + "not be running on " + hostname)
                           .build();
        }
        manager.add(hostname, props);
        return Response.ok(props).build();
    }
```
to 
```
    public Response getPropertiesForHost(@PathParam("hostname") String hostname) {
        Properties props = manager.get(hostname);
        if (props == null) {
            return Response.status(Response.Status.NOT_FOUND)
                           .entity(new Properties())
                           .build();
        }
        manager.add(hostname, props);
        return Response.ok(props).build();
    }
```
