### ISSUE TITLE
Any guide missing "Try what you’ll build" section?

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#244]
Determine which guides are missing "Try what you’ll build".  If necessary, add it to the guides.

**Comment by justineechen** [comment]
Guides that are missing "Try what you'll build":
- https://openliberty.io/guides/docker.html
- https://openliberty.io/guides/getting-started.html
- https://openliberty.io/guides/kubernetes-microprofile-config.html
- https://openliberty.io/guides/kubernetes-intro.html
- https://openliberty.io/guides/rest-client-angularjs.html
- https://openliberty.io/guides/gradle-intro.html
- https://openliberty.io/guides/maven-intro.html
- https://openliberty.io/guides/rest-intro.html
- https://openliberty.io/guides/rest-client-java.html
- https://openliberty.io/guides/cors.html
- https://openliberty.io/guides/kubernetes-microprofile-health.html
- https://openliberty.io/guides/maven-multimodules.html
- https://openliberty.io/guides/rest-hateoas.html

**Comment by yeekangc** [comment]
Related to https://github.com/OpenLiberty/guides-common/issues/21 and we should cross-check and see how we can wrap these up ASAP.

**Comment by justineechen** [comment]
Guides that may not need `Try what you'll build`:
https://openliberty.io/guides/docker.html
https://openliberty.io/guides/getting-started.html
https://openliberty.io/guides/kubernetes-microprofile-config.html
https://openliberty.io/guides/kubernetes-intro.html
https://openliberty.io/guides/kubernetes-microprofile-health.html
https://openliberty.io/guides/gradle-intro.html
https://openliberty.io/guides/maven-intro.html
https://openliberty.io/guides/cors.html

Guides that need `Try what you'll build`:
https://openliberty.io/guides/rest-client-angularjs.html
  - There is a Try what you'll build section but it is named Starting the service
https://openliberty.io/guides/rest-intro.html
https://openliberty.io/guides/rest-client-java.html
https://openliberty.io/guides/maven-multimodules.html
https://openliberty.io/guides/rest-hateoas.html

**Comment by yeekangc** [comment]
Please be sure we add only where it makes sense and necessary, @justineechen @gkwan-ibm.

These should aid and add to the overall learning experience but not take away or introduce confusion.

**Comment by justineechen** [comment]
Note: The rest-client-java guide was not updated because it has a `Starting the service` section that shows users the existing application that they will work with.
