### ISSUE TITLE
Skipping build tests due to build delays

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#246]
Example: 

2019-03-16
2019-03-15
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   302    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   302  100   302    0     0    228      0  0:00:01  0:00:01 --:--:--   228
[ "2019-03-10_0446", "2019-03-10_1436", "2019-03-10_2028", "2019-03-11_0428", "2019-03-11_1527", "2019-03-12_0152", "2019-03-12_0455", "2019-03-12_1457", "2019-03-13_0028", "2019-03-13_0434", "2019-03-13_1213", "2019-03-13_1512", "2019-03-13_2039", "2019-03-13_2325", "2019-03-14_0438", "2019-03-14_1445" ]

These were the builds with the `2019-03-15` date, but looks like they were available after the tests were scheduled to run: 

[DIR] 2019-03-14_1445/                                14-Mar-2019 09:04    -   
[DIR] 2019-03-15_0041/                                16-Mar-2019 07:26    -   
**[DIR] 2019-03-15_0453/                                16-Mar-2019 07:26    -   
[DIR] 2019-03-15_1410/                                16-Mar-2019 07:26    -   
[DIR] 2019-03-15_1506/                                16-Mar-2019 07:26    -   
[DIR] 2019-03-15_2203/                                16-Mar-2019 07:26    -**   
[DIR] 2019-03-16_1505/                                16-Mar-2019 09:33    -

**Comment by gkwan-ibm** [comment]
close
- test is migrating to github action.
