### ISSUE TITLE
Investigate an automated way to copy the checklist issues to a new draft repo

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#247]
use Github REST APIs to create issues for new draft guide repo:
- [Peer reviews for different platforms](https://github.com/OpenLiberty/draft-guides-template/issues/12)
- [User review](https://github.com/OpenLiberty/draft-guides-template/issues/15)
- [final end-to-end](https://github.com/OpenLiberty/draft-guides-template/issues/16)
- [Publishing Tasks Checklist](https://github.com/OpenLiberty/draft-guides-template/issues/18) 
- [Post-Publishing Tasks Checklist](https://github.com/OpenLiberty/draft-guides-template/issues/17)

**Comment by justineechen** [comment]
I have tested a script I wrote to create the checklist issues in a draft repo. I tested it on the draft-guide-cloud-aws guide so the results for the issues are here: https://github.com/OpenLiberty/draft-guide-cloud-aws/issues

The line break in MD makes the checklist not appear properly on github though.. I am still looking into how to fix that

**Comment by justineechen** [comment]
I'm also not using the GuidesBot id because I would have to put an OAUTH/personal access token into the script. So the user can use their own username/github account and if they have two factor authentication then they will need to use a personal access token.

**Comment by gkwan-ibm** [comment]
close
- bash scripts were created at `github.ibm.com` under `websphere/olguides-automation` repository ` create-issues` directory
