### ISSUE TITLE
Clean up docker hub daily build images

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#248]
The only remaining task from #220 is to clean up the docker images from docker hub.

**Comment by gkwan-ibm** [comment]
- study any REST api to remove docker image from dockerhub
- study to use scheduled github action to clean up

**Comment by gkwan-ibm** [comment]
close
- a script was implemented at `https://github.ibm.com/websphere/olguides-automation`
- require to run it manually per month
