### ISSUE TITLE
Create a guide on MicroProfile REST Client

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#25]
Create a guide on how to use/create MicroProfile Type-safe REST Client.

**Comment by evelinec** [comment]
@sishida Guide is ready to be considered for ID review in the next iteration: 
Repo Link: https://github.com/OpenLiberty/draft-guide-microprofile-rest-client

**Comment by sishida** [comment]
I have created pull requests for the ID line edits and Acrolinx check. :) Thanks!

**Comment by evelinec** [comment]
Completed.
