### ISSUE TITLE
Do not use "RELEASE" to specify parent pom and inherit liberty-maven-plugin version

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/guides-common#251]
Setting a dependency/plugin version as `RELEASE` has been deprecated since Maven 3.0 (released in 2010) and has long since been [considered to be bad practice](https://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency). However, many of the of the guides have recently been updated to use `RELEASE` as the dependency version, which as of Maven 3.6.0 is only functional due to [an oversight](https://issues.apache.org/jira/browse/MNG-6342) in the Maven project. The guides are currently using this "hack" to resolve versions for the `liberty-maven-app-parent`, and through it, the `liberty-maven-plugin`.

The reason this is bad practice is because it leaves us with builds that are not reproducible. The success of a build that uses `RELEASE` as a plugin or dependency version is dependent upon what the latest version is at the time the build was executed. Furthermore, unless we set up a separate task to re-run each guide that uses the `liberty-maven-plugin` every time a new version is released, we won't even consistently know the status of these builds.

In an effort to maintain our guides and keep the versions up to date, our team put mechanisms in place last year to upgrade the `liberty-maven-plugin` version for the Open Liberty guides using an automated script that is executed as part of each `liberty-maven-plugin` release. The only manual work that is required is verification that the Travis builds passed using the updated plugin version for each guide. I strongly recommend that we return to using this mechanism as it is much more reliable. 

Finally, if the guides are meant to be a demonstration of best practice, it doesn't exactly look too good if the first message the user is greeted with when they run one of our guides is this (on Maven 3.6.0):

```
Charless-MacBook-Pro:finish ctianus.ibm.com$ mvn clean install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.openliberty.guides:ServletSample:war:1.0-SNAPSHOT
[WARNING] 'parent.version' is either LATEST or RELEASE (both of them are being deprecated) @ line 8, column 18
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------------< io.openliberty.guides:ServletSample >-----------------
[INFO] Building ServletSample 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
...
```

**Comment by chyt** [comment]
I'll also tie this in with this issue, but we should also not be using `RELEASE` to specify the version for the Open Liberty runtime in the `liberty-maven-plugin` `assemblyArtifact` configuration parameter. The `liberty-maven-plugin` supports version ranges for the `assemblyArtifact` version, so that would be the way to appropriately handle this issue. 

However, version ranges are not supported in the parent pom or plugins, so we'll still want to use the automated updater for those scenarios.

**Comment by chyt** [comment]
> @chyt we know and understand the issue of using RELEASE. We are willing to change if the solution is good and permanent in our perspective. Would you tell us which version range should be used so that we don't need to update the pom.xml frequently? Not only openliberty-runtime but also feature-bom and liberty-maven-app-parent, etc

_Originally posted by @gkwan-ibm in https://github.com/OpenLiberty/guide-maven-intro/pull/45#issuecomment-474568412_

As I said above, you cannot use version ranges for parents or plugins. However, I do not expect we would need to update the parent pom often as it has not changed for a long time. For the runtime and features bom, anything like `[19.0.0.2,)` would work. 

I don't think it's reasonable to expect a solution that will require no code changes. As we update our plugins with fixes and enhancements, it's reasonable to expect that we will want to continually veriy that our resources using these plugins remain functional with the updates. However, as I said, with our updater implementation 90% of the work has been automated.

**Comment by gkwan-ibm** [comment]
The guides were updated to use new LMP  and did not use parent pom anymore.
