### ISSUE TITLE
Tests for the guides on 19003 candidate build

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#252]
- Automated tests for all published guides
- Manual test the guides against 19.0.0.3 GM master, Java11OpenJ9:
- [x] Getting Start (Gilbert)
- [x] Kube Intro (Andrew)
- [x] Gradle (Andrew)
- [ ] Maven Intro (Justine)
- [x] JWT (Justine)
- [x] Sessions - candidate draft guide (Eveline)

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform

**Comment by justineechen** [comment]
JWT - 11.0.1 gets this error when signing into localhost
<img width="1676" alt="Screen Shot 2019-03-22 at 3 17 56 PM" src="https://user-images.githubusercontent.com/18709242/54848897-ee774c80-4cb8-11e9-988c-95da94547be4.png">

**Comment by evelinec** [comment]
The JDK11.0.1 error is a know issue: https://github.com/OpenLiberty/guide-microprofile-jwt/issues/88

**Comment by evelinec** [comment]
Also tested the `maven-intro` with jdk8 and openjdk11.0.2 the guide is working.

**Comment by evelinec** [comment]
For future reference, we need to add the `docker` guide in the manual test list.

**Comment by evelinec** [comment]
@justineechen reported that the `maven-intro` guide is now tested successfully on her environment too. Close issue.
