### ISSUE TITLE
Update the dockfiles for OL docker image change

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#253]
Because OL docker image use non-root now, all guides which contain Dockerfile may need to be updated

At least:
- [ ] getting started
- [ ] docker
- [ ] kube intro
- [ ] kube config
- [ ] kube health
- [ ] istio

draft guides: IBM cloub, AWS

**Comment by evelinec** [comment]
Can we list which guides are impacted?

**Comment by evelinec** [comment]
> Because OL docker image use non-root now, all guides which contain Dockerfile may need to be updated
> 
> At least:
> 
> * [ ]  getting started - failed with issue https://github.com/OpenLiberty/guide-getting-started/issues/64
> * [ ]  docker - Eveline
> * [ ]  kube intro - Eveline
> * [ ]  kube config - Eveline
> * [ ]  kube health - Justine
> * [ ]  istio - Justine
> 
> draft guides: IBM cloub, AWS - Andrew to verify

**Comment by evelinec** [comment]
Test on kube config guide failed, see issue https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/issues/47.

**Comment by evelinec** [comment]
End-to-end tests with changes to the guide: 

- [ ] getting started - Justine
- [ ]   kube intro - Andrew
- [ ]   kube config - Eveline
- [ ]   kube health - Justine
- [ ]   istio - Justine

**Comment by gkwan-ibm** [comment]
1: apt-get, 2: copy, 3: unknown issues
- [ ] getting started - 1, 2
   - qa to master PR 
- [ ] kube intro - 2
   - qa is ready to test
- [ ] kube config - 2, 3
  - investigating 3
- [ ] kube health - 2
  - testing qa
- [ ] istio - 2
  - testing qa

completed:
- [x] docker - 0

**Comment by gkwan-ibm** [comment]
1: apt-get, 2: copy, 3: unknown issues
- [x] getting started - 1, 2
   - PR was merged to master
- [ ] kube intro - 2
   - qa is testing
- [ ] kube config - 2, 3
  - investigating 3
- [x] kube health - 2
  - PR was merged to master
- [ ] istio - 2
  - testing qa
    - Win and Mac are good
    - Linux has issue (maybe the Kube version)
    - Istio 1.1.1

completed:
- [x] docker - 0

**Comment by gkwan-ibm** [comment]
1: apt-get, 2: copy, 3: unknown issues

- [ ] kube config - 2, 3
  - PR is ready for qa
- [ ] istio - 2
  - testing qa
    - Win and Mac are good
    - Linux has issue (maybe the Kube version)
    - Istio 1.1.1

completed:
- [x] docker - 0
- [x] getting started - 1, 2
- [x] kube intro - 2
- [x] kube health - 2

**Comment by gkwan-ibm** [comment]
1: apt-get, 2: copy, 3: unknown issues

- [ ] istio - 2
  - need to update the command to `minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.13.0`
   - need test again for above

completed:
- [x] docker - 0
- [x] getting started - 1, 2
- [x] kube intro - 2
- [x] kube health - 2
- [x] kube config - 2, 3

**Comment by gkwan-ibm** [comment]
all completed
