### ISSUE TITLE
Managing guide's dependencies 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#254]
We need a mechanism to manage the guide's dependencies (list below), keeping them up to date, and ensuring new changes are incorporated and tested where needed. 

- feature dependencies (perhaps related to #251)
- open liberty docker image updates
- docker, kubernetes and Istio version updates
- maven or gradle plugin dependencies (perhaps resolved already by the recent parent pom changes)

**Comment by evelinec** [comment]
@yeekangc @gkwan-ibm FYI

**Comment by yeekangc** [comment]
I am not sure how this is different from what we have in place and working on.  Need elaboration on specifics.

**Comment by evelinec** [comment]
This issue can be added to the infrastructure epic.

**Comment by gkwan-ibm** [comment]
close
- implemented the guides to use dependabot to create PRs for dependencies update
- OL docker image is already the latest
- other items have to do it manually
