### ISSUE TITLE
Support MicroProfile 2.2

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#255]
- Update all guides to use MP 2.2 and associated features (toleration)
- Determine any new content that should be covered and file separate issues to cover
    - Prereq updates for FT 2.0 for Java EE 8

@kwsutter

**Comment by yeekangc** [comment]
Tagging @mbroz2 in case we need to update for interactive guides too.

**Comment by gkwan-ibm** [comment]
- Run automation to generate PRs to update the feature versions (PR)
   - installed features in `<dependenices/>`
   - be aware the parent pom.xml
   - create PRs to qa branch

- Testing (JC)
- Analyze the features (GK)

**Comment by gkwan-ibm** [comment]
- most guides were updated to the latest feature version expect the IBM cloud
- fixing the Travis test failure

**Comment by gkwan-ibm** [comment]
MP 2.2 updated features
- mpFaultTolerance-2.0
- mpOpenAPI-1.1
- mpOpenTracing-1.3
- mpRestClient-1.2

**Comment by gkwan-ibm** [comment]
The only possible thing is to mention following in the MP rest client guide
- @RegisterRestClient(baseUri="http://localhost:9080/myBaseUri") and it can be overridden by the configuration file
