### ISSUE TITLE
Update Kube guides to use the services as the MP guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#256]
Currently kube guides are using ping and name microservices. To make them consisting with MP guides, update them to use inventory and system microservices.

- Kube intro
- Kube config
- Kube health
- Istio
- IBM Cloud
- AWS

**Comment by gkwan-ibm** [comment]
- PR for Kube intro is ready to review

**Comment by evelinec** [comment]
- GK is reviewing the kube-intro PR
- working on the other kube guides

**Comment by gkwan-ibm** [comment]
- kube-intro is ready
- working on kube-config and PR is under review
- working on kube health

**Comment by gkwan-ibm** [comment]
- Kube config is ready at QA site
- working on kube health (target on tomorrow)

**Comment by gkwan-ibm** [comment]
- kube health guide is completed and under testing
- working on the istio guide

**Comment by gkwan-ibm** [comment]
- working on the istio guide and the target is tomorrow

**Comment by gkwan-ibm** [comment]
- istio guide PR is ready

**Comment by evelinec** [comment]
- waiting for some PRs to be reviewed and merged
- all kube guides have been converted
