### ISSUE TITLE
Guides daily build test should use OL daily docker image

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#257]
For the guides which are using OL docker image, the daily build test should use the OL daily docker image

**Comment by evelinec** [comment]
I think there should be two branches of tests, one of them is testing the daily build and the published docker image (this is what we currently have); the other one is to test the daily/development docker images with some latest changes (this is new and need development in the infrastructure).

**Comment by gkwan-ibm** [comment]
dup of #265
