### ISSUE TITLE
Update the wiki "Guidelines for Structure and Styles" for multipane

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#258]
https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles

**Comment by gkwan-ibm** [comment]
New review feedback on the wiki: 

- [ ] The "Types of Guides" link in the TOC is not clickable

- [ ] I think the original sentence is clearer and sufficient. The modified sentences (below) is confusing, imo. 
"Any files that are mentioned in hotspots or code commands should be included as a code column in that subsection. The hotspots and code commands will not be pointed to anything if the code column "include" isn't put in the same subsection as these commands."
I meant to suggest to change the original sentence from "Any files that are mentioned in hotspots or code commands should be included as a code column." to "Any files that are mentioned in hotspots or code commands are included as a code column." 
The reason being the hotspots or code commands need to be added in order to show up on the code column, using "should be" didn't seem to fit.

- [ ] The "include::file" examples may be good to include the example full path, ie, src/main/...filename

Others look good.

_Originally posted by @evelinec in https://github.com/OpenLiberty/guides-common/issues/206#issuecomment-477696761_

**Comment by evelinec** [comment]
- [ ] The "Types of Guides" link is fixed. But this section looks like a subsection under "Language", ie, the font size is smaller than other section headers. I think it needs to be a section on its own.

**Comment by evelinec** [comment]
- [ ] Other headings size are different: 
- Language
- XML Elements

- [ ] The following TOC names and the heading names have different spelling type, ie, cap'ed vs non-cap'ed. Good to make them consistent. 
- Listing Blocks vs Listing blocks
- Project Structure vs Project structure
- Writing Tests vs Writing tests

**Comment by evelinec** [comment]
Looks good. Thanks.

**Comment by gkwan-ibm** [comment]
- major update is completed
- will do some minor update

**Comment by evelinec** [comment]
I've done my updates for now.

**Comment by evelinec** [comment]
Closed.
