### ISSUE TITLE
Consider using liberty kernel for the guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#259]
Currently the guides uses the liberty runtime is more than 100MB, takes a while to download while working with the guides in a lab or conference. We can consider using the liberty kernel instead. 

Potential issues when using liberty kernel in the guides:
1. The daily build tests will not work as the daily install features aren't accessible, see relevant issue #214

**Comment by gkwan-ibm** [comment]
The guides were switch to use the new LMP. It is using Liberty kernel.
