### ISSUE TITLE
Create a guide on CDI

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#26]
Create an introductory guide on using CDI covering the essentials and in the context of developing JAX-RS services.

**Comment by evelinec** [comment]
Adding "ID require" tag for team to plan. 
Repo link will be added when guide is ready for ID review.

**Comment by bcpswope** [comment]
Please let us know when you are ready for us to access the repo and start the review.

**Comment by yeekangc** [comment]
All guides ready for ID review should be viewable from the test site so reviewers can review in context and with the proper styling in place.

PRs can be submitted for changes required and we can use the review process therein to work through the details and finalize the changes.

**Comment by bcpswope** [comment]
Can we please link to the test site in these issues and the repo? For us to branch or fork, we would like to have a link to the relevant repo in the issue.

**Comment by evelinec** [comment]
@bcpswope The CDI guide is good to get some ID review now. Thank you. 
CDI Intro guide (revised version): https://qa-guides.mybluemix.net/guides/cdi-intro.html
CDI Intro guide repo: https://github.com/OpenLiberty/draft-guide-rest-cdi

**Comment by yeekangc** [comment]
Intro guide delivered.
