### ISSUE TITLE
Convert guides to use hotspots by tag 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#261]
Convert gudies to use hotspots by tag pending on https://github.com/OpenLiberty/openliberty.io/issues/979#issuecomment-483697516

**Comment by gkwan-ibm** [comment]
- Steven converting rest client intro guide
- JC converting gradle guide

**Comment by gkwan-ibm** [comment]
- Steven will address issue for the gradle guide

**Comment by evelinec** [comment]
- Steven is still working on nested tagging, and addressing some feedback from Justine on the gradle guide

**Comment by gkwan-ibm** [comment]
- Steven fixed the nested tagging
- Justine continue to convert the gradle guide

**Comment by gkwan-ibm** [comment]
- [ ] update the doc in template to use tag hotspot

**Comment by yeekangc** [comment]
Where are we with this issue?

Currently, we have custom handling for hiding comments since line numbers are used to locate the hotspots:
```
[source, Java, linenums, role='code_column hide_tags=comment']
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[]
----
```

Should check that with this improvement, we can go back to using standard Asciidoc for hiding/excluding using tags:
```
[source, Java, linenums, role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[tags=!comment]
----
```

Otherwise, we should work with the team for further improvements.  @steven1046

**Comment by steven1046** [comment]
If all of the hotspots in a given file use tags rather than line numbers, we shouldn't need a `hide_tags=ABCD` in the role and can just use `tags=!comment` in the include stanza.

**Comment by yeekangc** [comment]
Do we have the syntax for the hotspots documented somewhere?  Thank you.

**Comment by steven1046** [comment]
https://github.com/OpenLiberty/guides-common/wiki/Creating-a-static-guide-in-the-multipane-layout

**Comment by yeekangc** [comment]
Is it https://github.com/OpenLiberty/guides-common/wiki/Creating-a-static-guide-in-the-multipane-layout?  I see the use of file=1 ... Does that mean we count the files somehow?  Can we use filenames?

**Comment by steven1046** [comment]
It's the index of the file in the section. Currently only the index is supported and not the filename.

**Comment by DannyS03** [comment]
Addressed in https://github.com/OpenLiberty/guides-common/issues/352.
