### ISSUE TITLE
Consuming a RESTful web service with Angular 7

### ISSUE THREAD

**Issue by realModusOperandi** [OpenLiberty/guides-common#264]
Is there any interest in an Angular 7 version of "Consuming a RESTful web service with AngularJS"? When I first started an Angular application that consumed an endpoint from OpenLiberty I found that guide but couldn't apply it since it was AngularJS and the two are quite different. 

Now that I have completed that app I experimented with converting it to modern Angular and I think it could work: https://github.com/realModusOperandi/guide-rest-client-angularjs/tree/angular7 I have written the start and finish code and have taken a stab at writing the guide text to give an idea of what would need to be discussed.

I think there's value in doing this because AngularJS is stabilized and Angular has surpassed it in userbase, and because creating a project that builds both an Angular frontend and OpenLiberty app backend requires some work to set up and this guide could provide users with a decent starting point for achieving that (the `start` directory already has the default Angular app generated, the pom file set up to build it, etc.)

**Comment by evelinec** [comment]
@yeekangc @gkwan-ibm FYI.

**Comment by yeekangc** [comment]
@realModusOperandi, I would think we would be open to contribution.  If you are open to take what you have a few steps further and turn it into a draft guide, we can go from there.

**Comment by evelinec** [comment]
Hi Liam, thank you for your contributing a guide. The team has reviewed this topic and decided to accept it as a new guide! I encourage you to go through our guide's template [here](https://github.com/OpenLiberty/draft-guides-template), especially take a look at the [Guidelines for Structure and Styles](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles) wiki. 

When you're ready, you can create a PR to a `draft-guide` repo we had created for you. @realModusOperandi 

Here's a repo we created in the OpenLiberty project for this guide, you can create a PR from your personal repo to this one against the `dev` branch: https://github.com/OpenLiberty/guide-rest-client-angular. We will then start the review processes. 

Thank you.

**Comment by realModusOperandi** [comment]
Thanks! I've made the PR: https://github.com/OpenLiberty/draft-guide-rest-client-angular/pull/1

**Comment by evelinec** [comment]
Hi @realModusOperandi We went through the initial draft guide and provided some feedback in this issue https://github.com/OpenLiberty/draft-guide-rest-client-angular/issues/5. Would you take a look? Thank you.

**Comment by evelinec** [comment]
Hi @realModusOperandi, sorry for the delay in responding to your questions on the previous issue. We'll get back to them as soon as we can. Meanwhile, we got some more review feedback from our team in this issue, https://github.com/OpenLiberty/draft-guide-rest-client-angular/issues/7. Let us know if you'd like take a look. Thank you.

**Comment by evelinec** [comment]
Hi @realModusOperandi, I had gone through the guide with our peer review checklist and found a few more minor issues, as in https://github.com/OpenLiberty/draft-guide-rest-client-angular/issues/11. Let us know if you'd like to take a look. 

Thank you.

**Comment by evelinec** [comment]
Hi @realModusOperandi, my team has reviewed the guide and provide some more feedback, in this issue, https://github.com/OpenLiberty/draft-guide-rest-client-angular/issues/13. Do you think you may take a look? Thank you.

**Comment by realModusOperandi** [comment]
Lots to look at, I will address them today. Thanks!

**Comment by evelinec** [comment]
All remaining issues had been handled. @yeekangc you can sign off this guide now.

**Comment by evelinec** [comment]
@Charlotte-Holt this guide is ready for you to review. Here's the repo: https://github.com/OpenLiberty/draft-guide-rest-client-angular

**Comment by evelinec** [comment]
@justineechen to do end-to-end testing.

**Comment by yeekangc** [comment]
Do we have news on end-to-end testing?

**Comment by evelinec** [comment]
- End-to-end test was completed
- Addressing the one issue raised

**Comment by evelinec** [comment]
- ID review is in progress

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/rest-client-angular.html.
