### ISSUE TITLE
Automate validation of the guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#270]
We had situations in the past, where the guide's flow was not accurate and it didn't get caught till someone actually try out the guide manually from end-to-end. It would be good to have an automatic validation for the guides. ie, checking the flow of the guide from start to finish, going through the guide in the `start` directly?

**Comment by gkwan-ibm** [comment]
- we can consider to use GitHub action and [asciidoctorj](https://github.com/asciidoctor/asciidoctorj)

**Comment by gkwan-ibm** [comment]
close because of no 100% but we are having followings:
- PR-checker
- daily build testing
- PR testApp
- manually test process
