### ISSUE TITLE
Test report requirements 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#271]
- [ ]  build number hover info in build description: build level, overall pass/failed — P1.2

- [ ]  console log for test report: create a failure section to include links to the travis build/jobs — P2

- [ ] console log for test report:
summary: — P4
overall pass/failed
% of success

- [ ] build number hover info in build description: if failed, calculate x% successful, x% failure — P4

**Comment by gkwan-ibm** [comment]
close
- test is migrating to use github action
