### ISSUE TITLE
Replace dockerfile-maven-plugin by something else

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#273]
docker-maven-plugin is deprecated. The guides are using the new dockerfile-maven plugin. See https://github.com/spotify/dockerfile-maven. The issue will study and determine a better way to containerize the application/microservice. An option is multistage (as proubatsis's comment in below) or simply use docker build. 

- getting start guide
- kubes related guides
- cloud related guides

**Comment by yeekangc** [comment]
Should take the opportunity to take a look at what's out there and consider if we should adopt another alternative.

**Comment by gkwan-ibm** [comment]
An alternative is that do not use any docker plugin, instead, user docker command directly.

**Comment by gkwan-ibm** [comment]
@andrewdes @proubatsis

**Comment by proubatsis** [comment]
I'd suggest multi-stage docker builds. Using multi-stage docker builds allows you to easily build and test your microservices inside a container with a single `Dockerfile`. This would remove the need for a Maven plugin and the POM for the Docker based guides would become very similar to the ones that don't use Docker.

**Comment by justineechen** [comment]
There's also another docker maven plugin that is popular if we are moving away from the spotify plugin for specific reasons.. it's by https://github.com/fabric8io

**Comment by evelinec** [comment]
For the `docker-maven-plugin`, do you mean the `dockerfile-maven-plugin`?

**Comment by gkwan-ibm** [comment]
- updated the summary for the correctness

**Comment by gkwan-ibm** [comment]
addressed by #299
