### ISSUE TITLE
Guide's setup time on Windows is very long

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#274]
We generally know that the guides takes much longer to run on Windows than on Mac, especially the first time a guide is being run or when there's a new OL release to download. 

Recently we got user feedback that we'd look further into this issue for improvement. 

Feedback on Windows:
I haven't done a guide in a while, but it seemed like it took a very long time to set things up (especially given my laptop and network specs):
mvn install liberty:start-server Total time: 13:42 min
mvn generate-resources Total time: 05:23 min
so almost 20 minutes to get set up

A same guide only take a few minutes to run on a Mac environment.

**Comment by evelinec** [comment]
On our Windows 10 Intel Core i7-6820HQ CPU @2.70GHz with 32GB of RAM, 64-bit OS, for the "consuming rest using angular" guide, running the `mvn install liberty:start-server` command took about 9 minutes, and the `mvn generate-resources` command took 1 minute. So all together the cmd execution time is about 10 minutes. It was run for the first time where it needs to download a new OL driver as well. Running the `mvn install liberty:start-server` the second time (without having to download the new OL driver) took 2 minutes. Not bad.

**Comment by DannyS03** [comment]
Guide setup on Windows has been enhanced from dev mode changes.
