### ISSUE TITLE
Linux Xenial vs Trustry distribution on Travis

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#277]
Some guide (ref https://github.com/OpenLiberty/guide-bean-validation/issues/49) has been chosen to run on the Linux Xenial distribution instead of the Linux Trusty distribution. The problem is, Xenial does not support older jdk levels before 10 and 11.

Xenial JVM doc: https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
Also refer to: https://travis-ci.community/t/the-travis-ci-build-could-not-be-completed-due-to-an-error/1345/8

```
BanzaiMan
Dec '18

Xenial’s pre-installed JDKs are 10 and 11. https://docs.travis-ci.com/user/reference/xenial#jvm-clojure-groovy-java-scala-support 7 We do not support anything prior.
```

Trusty JVM doc: https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images

Based on the travis support blog, https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment. They are gradually changing the default Travis CI build environment from Ubuntu Trusty to Ubuntu Xenial, we may find more and more guides' tests failing with jdk8, which we need to either specify to run with Trusty, or move the tests to run with jdk11. To be discussed and determined.

**Comment by evelinec** [comment]
Discussed with YK, we need to continue to test with jdk8.

**Comment by evelinec** [comment]
There are more guides that are being run on the Xenial platform now. Need to apply the fix on all guides.

**Comment by evelinec** [comment]
Discussed with team and arrived at 3 options: 
1. Force Trusty 
2. Switch to run tests with OpenJDK8 and OracleJDK11
3. Investigate the solution to run tests with AdoptedJDKs, potentially, with Adopted OpenJ9 11, and Hotspot JDK8 (TBD further)

**Comment by evelinec** [comment]
Since all 3 options requires some work and have their pos and cons, as a temporary solution, we'll go with option 1 for today.

**Comment by evelinec** [comment]
Working on option 1 today.

**Comment by evelinec** [comment]
- Fixed the impacted guides found and the tests were re-run successfully
- Today's daily build tests are green

**Comment by evelinec** [comment]
Two more guides are randomly impacted by this problem: 

- [ ] angularjs

- [ ] mp-config

**Comment by evelinec** [comment]
@MaiHameed FYI

**Comment by evelinec** [comment]
YK: we can switch the daily build test to use OpenJDK8 and OracleJDK11.

**Comment by yeekangc** [comment]
It makes sense to me that we will have a set of runs for Java SDK 8 and another set of runs for Java SDK 11.  These would be regular regression runs through everything (separate from the CI runs for a PR).  Thank you.

**Comment by gkwan-ibm** [comment]
@evelinec after switching the JDKs, should remove the restriction to run Trusty for the updated guides?

**Comment by evelinec** [comment]
Yes. Just tested all the guides with the new JDKs, they seems good.

**Comment by evelinec** [comment]
Changes made:

- [ ] Create Jenkins job to run OpenJDK8 tests 

- [ ] Create Jenkins job to run OracleJDK11 tests

- [ ] Create the launch job to run OpenJDK8 and OracleJDK11 tests for all daily builds on a schedule

- [ ] Test the above new jobs in Jenkins and verify the test results

- [ ] Add/update the new jobs in the appropriate result dashboard

- [ ] Remove forcing the tests to run on Trusty for 8 guides

**Comment by evelinec** [comment]
Just discovered the Oracle JDK11 Java is the Open JDK version from Travis. Team needs to determine whether that coverage is good.

Oraclejdk8: 
$ java -Xmx32m -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)



Oraclejdk11: 
$ java -Xmx32m -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by evelinec** [comment]
Checked with @gkwan-ibm who thinks the new jdk coverages are good. Closed.
