### ISSUE TITLE
Guide for Integration testing Microservices using Testcontainers

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guides-common#278]
A guide showing how to do simple integration testing of Microservices using the Testcontainers project.

SME: @aguibert

**Comment by evelinec** [comment]
@Charlotte-Holt This guide is ready for you to review. Repo: https://github.com/OpenLiberty/draft-guide-microshed-testing.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/microshed-testing.html.
