### ISSUE TITLE
Test the guides with the 19005 candidate build

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#279]
- [x] Automated tests with jdk8 and jdk11 for all published guides (Eveline)

Manual test the guides against 19.0.0.5 GM master with Java11OpenJ9:
- [x] Getting Start (Danny)
- [x] Kube Intro (Mai)
- [x] Gradle (Danny)
- [x] Maven Intro (Mai)
- [x] JWT (Nimrah)
- [x] Docker (Nimrah)
- Make sure to run the `docker pull open-liberty` command before running the `docker build` command to make sure the latest docker image is being pulled in and used in the test.
- [x] IBM Cloud draft guide (Andrew)
- [x] AWS draft guide (Andrew)

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform

**Comment by evelinec** [comment]
Ref to https://github.com/OpenLiberty/guides-common/issues/280 for some of the info on testing the guides manually.

**Comment by MaiHameed** [comment]
Kube Intro Done:
- Checked with jdk 8&11
- No SRVE9967W errors found
- Everything builds and verifies

**Comment by DannyS03** [comment]
Getting Started:

- Successful end-to-end tests with JDK 8 and JDK 11 
- Tested on macOS 10.14.12

**Comment by NimG98** [comment]
Docker:

- followed guide and tested with jdk8 and jdk11
- Tested on Mac

**Comment by MaiHameed** [comment]
Maven Intro:
- Checked endpoints
- Checked with jdk 8&11
- Tested on macOS 10.14.12
- No SRVE9967W errors found

**Comment by NimG98** [comment]
JWT:

- Followed guide and tested with jdk8 and jdk11
- Tested on Mac

**Comment by evelinec** [comment]
> JWT:
> 
> * Followed guide and tested with jdk8 and jdk11
> * Tested on Mac
> * Tested with the GM candidate build (19.0.0.5-cl190520190522-2227)

Thank you @NimG98 Usually, it's helpful to get the OL build number along with the JDK version info. You can get both of these info together in the server's `console.log`, like I showed you when I walked throw the testing steps with you.

**Comment by DannyS03** [comment]
Gradle:

- Successful end-to-end tests with JDK 8 and JDK 11
- Ran with GM candidate build 19.0.05 - cl190520190522-2227
- Tested on macOS 10.14.12

**Comment by evelinec** [comment]
@DannyS03, @NimG98 and @MaiHameed One more thing, for the guides that use docker image, can you run the following command and paste the first line of return. ie, 

Command: `kubectl logs <pod_name>`

Result: 
```
Launching defaultServer (Open Liberty 19.0.0.5/wlp-1.0.28.cl190520190522-2227) on IBM J9 VM, version 8.0.5.35 - pxa6480sr5fp35-20190418_01(SR5 FP35) (en_US)
```

Thank you.

**Comment by MaiHameed** [comment]
```
(Open Liberty 19.0.0.4/wlp-1.0.27.cl190420190419-0642) 
IBM J9 VM, version 8.0.5.35 - pxa6480sr5fp35-20190418_01(SR5 FP35) (en_US)
```

**Comment by evelinec** [comment]
Worked with @DannyS03 to run the tests on the `getting-started` guide.

**Comment by evelinec** [comment]
Completed.
