### ISSUE TITLE
Enable draft guides to run daily build tests 

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#282]
When draft guide is ready they should be run with daily build. This task is to create the base job so that draft guides can be inserted to run. 

We would like to separate the draft guide tests from production (published guides) daily build tests because generally the draft guides have development problems.

**Comment by gkwan-ibm** [comment]
- after user review, draft guide should be in daily build test
  - trigger by the regualer daily build trigger 
  - another Job will run the draft guides
    - oracleJDK8 and openJDK11

**Comment by evelinec** [comment]
@evelinec to review this end to end job and enable it to run with daily build.

**Comment by evelinec** [comment]
- reviewed this job (made a few changes listed below)
- tested the draft guide, ie, Angular, was able to run
- removed the draft guides that were published, ie, angular, ibm-cloud, and aws
- others look good
- when @andrewdes is back, he can create the PR and make the necessary changes into master branch. As well, enable it to run with daily build

Changes made: 
- changed the JDKs to run the tests with draft guide to be same as the daily build tests, ie, oraclejdk8 and openjdk11

**Comment by andrewdes** [comment]
@evelinec @gkwan-ibm I have opened the PR and assigned both of you to review.
