### ISSUE TITLE
Inconsistent capitalization for multi-platform design

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guides-common#284]
There is inconsistency in the capitalization of platform names, such as "Windows" and "WINDOWS". 

![image](https://user-images.githubusercontent.com/46586499/58510899-af0d2680-8167-11e9-80d1-f7171c6b228f.png)
---
![image](https://user-images.githubusercontent.com/46586499/58510942-cf3ce580-8167-11e9-8407-b2684cdb98df.png)

This inconsistency is due to this variable that is defined by us: `[system]#*{win} | {mac}*#`

On some guides, 

```
:win: WINDOWS
```
On other guides,
```
:win: Windows
```

**Guides with all-caps:**
- [ ] guide-istio-intro
- [ ] guide-docker
- [ ] guide-kubernetes-intro
- [ ] draft-guide-cloud-aws
- [ ] draft-guide-cloud-ibm

**Guides with lower-case (need to be changed):**
- [x] guide-kubernetes-microprofile-health
- [x] guide-kubernetes-microprofile-config

**Comment by gkwan-ibm** [comment]
Use capital
:linux: LINUX
:win: WINDOWS
:mac: MAC

**Comment by gkwan-ibm** [comment]
won't be fixed because of new OS-specific design.

will be addressed by #288
