### ISSUE TITLE
Building daily build docker image automation failed

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#287]
Building daily build docker image automation failed causing all of the guides that uses docker images to fail. 

+ BUILDLEVEL=cl190620190603-1900
+ cd official/javaee8/java8/ibmjava
/tmp/jenkins1444593651414694591.sh: 5: cd: can't cd to official/javaee8/java8/ibmjava
Build step 'Execute shell' marked build as failure

Looks like this path `official/javaee8/java8/ibmjava` no longer exist.

**Comment by andrewdes** [comment]
The path to the docker image on https://github.com/OpenLiberty/ci.docker changed to: `official/19.0.0.x/javaee8/java8/ibmjava`. The Jenkins job has been updated to reflect this.

**Comment by evelinec** [comment]
Looks like this problem happened again for last night's tests, probably need to work out a more solid solution. 

cd official/19.0.0.x/javaee8/java8/ibmjava
/tmp/jenkins3512990476115679783.sh: 5: cd: can't cd to official/19.0.0.x/javaee8/java8/ibmjava
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by evelinec** [comment]
@evelinec to follow up while Andrew is away.

**Comment by evelinec** [comment]
This path is now changed to `official/latest/javaee8/java8/ibmjava`.

**Comment by evelinec** [comment]
Checked with Navid who had confirmed with Andy that this change will not happen from now on.
