### ISSUE TITLE
Update the MP Health and Kubernetes MP Health guides for MP Health Check 2.0

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/guides-common#289]
The following two guides should be updated to support MP Health Check 2.0 (mpHealth-2.0):
​https://openliberty.io/guides/microprofile-health.html​
​https://openliberty.io/guides/kubernetes-microprofile-health.html​

The MP Health Check 2.0 will introduce two new health check annotations and two new endpoints:
- @ Liveness : /health/live
- @ Readiness : /health/ready

For more information, please refer to the MpHealth-2.0 WAD, found in the Aha! feature:
https://ibm.ent.box.com/file/470499893181

**Comment by yeekangc** [comment]
Should align with 19.0.0.7.  Also, update all relevant portions in other guides besides the Health Check one too.

**Comment by gkwan-ibm** [comment]
consider #224  and https://github.com/OpenLiberty/guide-microprofile-metrics/issues/50

**Comment by gkwan-ibm** [comment]
- refactoring the app

**Comment by gkwan-ibm** [comment]
- working on the code change and readme

**Comment by gkwan-ibm** [comment]
- target to complete the draft update for both guides on this week

**Comment by evelinec** [comment]
- working on readme of the mphealth guide; application is converted

**Comment by gkwan-ibm** [comment]
- converting the app of kube health guide

**Comment by gkwan-ibm** [comment]
- completed the kube health guide
- working on end-to-end testing on both guides

**Comment by gkwan-ibm** [comment]
- SME reviewed
- completed the end-to-end test
- may request an ID review

**Comment by justineechen** [comment]
- Justine verify QA site, end-to-end
- Andrew will continue verifying the kube health

**Comment by gkwan-ibm** [comment]
- the mpHealth guide was published on last Fri
- the kube health guide PR to qa is ready to review

**Comment by gkwan-ibm** [comment]
the kube health guide was published on yesterday
