### ISSUE TITLE
Remove unnecessary comments and not show the license comment

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#291]
This issue will go through all the guides to make sure the java files, which are shown up on the right pane, not show the license comment and unnecessary comments

**Comment by justineechen** [comment]
Check right pane:
- [ ] Guide-rest-client-java
- [ ] Guide-microprofile-opentracing
- [ ] Guide-microprofile-health
- [ ] Guide-microprofile-metrics
- [ ] Guide-microprofile-config
- [ ] Guide-security-intro
- [ ] Guide-bean-validation
- [ ] Guide-cors
- [ ] Guide-JPA-intro
- [ ] Guide-microprofile-openapi
- [ ] Guide-kubernetes-microprofile-health
- [ ] Guide-maven-multimodules
- [ ] Guide-rest-hateoas
- [ ] Guide-docker
- [ ] Guide-cdi-intro
- [ ] Guide-getting-started
- [ ] Guide-microprofile-JWT
- [ ] Guide-kubernetes-microprofile-config
- [ ] Guide-kubernetes-intro
- [ ] Guide-microprofile-fallback
- [ ] Guide-rest-client-angularjs
- [ ] Guide-microprofile-rest-client
- [ ] Guide-gradle-intro
- [ ] Guide-maven-intro
- [ ] Guide-rest-intro
- [ ] Guide-cloud-aws
- [ ] Guide-cloud-ibm
- [ ] Guide-istio-intro
- [ ] Guide-arquillian-managed

**Comment by evelinec** [comment]
- double checking the remaining uncheck guides
- have Gilbert to review before closing
