### ISSUE TITLE
Create json file for guide prerequisites

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/guides-common#292]
We need a json file in guides-common named guide_prereqs.json to store the guide prerequisites. It should use the format outlined in the example below. `"name"` is what will appear in the button on the guides. If a specific version of the prereq is required, it should be put in the name (eg, `"name": "Maven v2.3.4+"`) and the link should contain directions for that specific version. `"link"` should be a link to instructions for how to install/set up that prereq. `"guides"` should be an array of all the guides that need that prereq. If a prereq is required by all guides, then `*` can be used (eg, `"guides": ["*"]`). The values in this list should match the url and the repo name (eg, `"getting-started"` would be used for https://openliberty.io/guides/getting-started.html).

```
{
    "prereqs": [
        {
            "name": "Docker",
            "link": "https://www.docker.com/get-started",
            "guides": ["docker", "getting-started"]
        },
        {
            "name": "Maven",
            "link": "https://maven.apache.org/download.cgi",
            "guides": ["getting-started", "maven-multimodules", "maven-intro"]
        },
        {
            "name": "Git",
            "link": "https://git-scm.com/book/en/v2/Getting-Started-Installing-Git",
            "guides": ["*"]
        }
    ]
}
```

**Comment by ellenwyllie** [comment]
It would also be good to update the guidelines for writing guides to point the user at the json file.

**Comment by gkwan-ibm** [comment]
drafted guide_prereqs.json is at dev branch: https://github.com/OpenLiberty/guides-common/blob/dev/guide_prereqs.json

**Comment by ellenwyllie** [comment]
If there is a prereq that is required by all the guides except for a small number the following syntax can be used to exclude certain guides:

```
{
    "name": "Maven",
    "link": "https://maven.apache.org/download.cgi",
    "guides": ["*"],
    "exclude": ["gradle-intro"]
}
```

**Comment by gkwan-ibm** [comment]
> If there is a prereq that is required by all the guides except for a small number the following syntax can be used to exclude certain guides:

updated guide_prereqs.json at the dev branch

**Comment by ellenwyllie** [comment]
For a draft guide, there is no need to include "draft-guide" in the json. It works the same way as a published guide.
For example: For "draft-guide-microprofile-rest-client-async", just add "microprofile-rest-client-async" to the json

**Comment by gkwan-ibm** [comment]
Need to update the following guides to change the "Prerequisites" to "Additional prerequisites"
- [ ] guide-kubernetes-intro
- [ ] guide-kubernetes-microprofile-config
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-istio-intro
- [ ] guide-cloud-ibm
- [ ] guide-cloud-aws
- [ ] guide-sessions
- [ ] guide-cloud-azure
- [ ] draft-guide-cloud-openshift
