### ISSUE TITLE
Guide for MicroProfile Fault Tolerance with Istio Fault Tolerance

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#296]
This is from @Emily-Jiang:

I would like a guide to demonstrate the ecosystem of MicroProfile Fault Tolerance with Istio Fault Tolerance:

Scenario 1:

Use MP FT in dev with Retry
Use Istio Retry and switched off MicroProfile FT using the MP FT config.

Scenario 2:

Use MP FT fallback
Use Istio Fault Tolerance
When the backend dies and retry was exhausted, FT fallback was triggered.

**Comment by evelinec** [comment]
- working on the application

**Comment by gkwan-ibm** [comment]
- tried out the Istio retry function
- need to contact Emily to clarify the scenario how the fallback can work when both Istio and microservice enable retty

**Comment by gkwan-ibm** [comment]
- we successfully prototyped the first scenario
- will try the second scenario

**Comment by gkwan-ibm** [comment]
-  Emily clarified the scenario and we are working on the scenario

**Comment by yeekangc** [comment]
@NimG98, please update with details of scenarios here if possible.

**Comment by NimG98** [comment]
For the second scenario (fallback):
- We were originally putting the @Fallback annotation on the server side (SystemResource.java).
- But Emily said that the istio retry and the FT annotations should be on the client side

We are currently trying to make the application and fallback work on the client side

**Comment by yeekangc** [comment]
I presume client as in the consuming service.  It should work in any case (for the appropriate scenarios) but this makes sense.

**Comment by justineechen** [comment]
- Continue to draft first scenario

**Comment by gkwan-ibm** [comment]
We tried the second scenario to do FT on the client side. The behavior is not as the expectation. After adding  @Fallback, the fallback method is called, and no retry is happened by mp or istio. 

We also tried the scenario by Thorntail which had the same behavior (no retry is happened by mp or istio, if adding @Fallback).

**Comment by gkwan-ibm** [comment]
- target to finish the draft for the first scenario on tomorrow

**Comment by gkwan-ibm** [comment]
- improving the prototyped app
- readme draft in half way

**Comment by gkwan-ibm** [comment]
- after discussed with Andrew, we will continue to come out a good scenario to demonstrate retry and fallback

**Comment by gkwan-ibm** [comment]
- we found out the scenario to demonstrate retry and fallback
- continue to draft the readme, (target to complete on today)

**Comment by gkwan-ibm** [comment]
- drafted the readme and rerunning end-to-end

**Comment by gkwan-ibm** [comment]
- reworking on the flow

**Comment by gkwan-ibm** [comment]
- target to start the dev content review on today

**Comment by gkwan-ibm** [comment]
- addressing the dev content review feedback

**Comment by gkwan-ibm** [comment]
- peer review in progress

**Comment by gkwan-ibm** [comment]
- need to find out why server pause not work on Win
- SME review in progress

**Comment by yeekangc** [comment]
@gkwan-ibm @NimG98, please tag issue appropriately for completed reviews.

**Comment by gkwan-ibm** [comment]
- addressing SME feedback
- ID review in progress

**Comment by gkwan-ibm** [comment]
- user review in progress
- addressing ID review feedback and user review feedback

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/microprofile-istio-retry-fallback.html.
