### ISSUE TITLE
Update Docker content in guides to use server package deploy

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#299]
Get to a container image from a loose application using a server package (e.g. tar.gz) and dropping it onto Liberty as part of image build.

Involve at least the guides below:
- Getting Started guide -- See https://github.com/OpenLiberty/guide-getting-started/issues/54
- Developing microservices with Docker
- Containerizing microservices

May cover other updates/fixes that we should do for our Docker content too.

**Comment by justineechen** [comment]
- Update Dockerfiles to use tar.gz and to use `ADD` to unpack the archive
- Remove use of Spotify maven plugin 
- Update README.adoc to ask users to use `docker build` instead of `mvn package` to build the image

**Comment by justineechen** [comment]
Guides involved:

- [ ] Getting started https://github.com/openliberty/guide-getting-started
- [ ] Docker (original) https://github.com/openliberty/guide-docker
- [ ] Sessions https://openliberty.io/guides/sessions.html

Kube guides:
- [ ] Istio https://openliberty.io/guides/istio-intro.html
- [ ] Kube Health https://openliberty.io/guides/kubernetes-microprofile-health.html
- [ ] Kube Config https://openliberty.io/guides/kubernetes-microprofile-config.html
- [ ] Kube Intro https://openliberty.io/guides/kubernetes-intro.html

- Cloud guides:
- [ ] AWS https://openliberty.io/guides/cloud-aws.html
- [ ] IBM Cloud https://openliberty.io/guides/cloud-ibm.html

**Comment by evelinec** [comment]
- have PR ready for `getting-started` guide in `qa` 
- start on the kube guides

**Comment by gkwan-ibm** [comment]
- the kube guide PR is ready to review

**Comment by gkwan-ibm** [comment]
- working on istio, kube config and kube health guides

**Comment by justineechen** [comment]
- working on IBM Cloud

**Comment by gkwan-ibm** [comment]
- working on azure and openshift

**Comment by gkwan-ibm** [comment]
- working on openshift, then rest-client async

**Comment by gkwan-ibm** [comment]
working on openshift

**Comment by gkwan-ibm** [comment]
- verifying the PRs

**Comment by gkwan-ibm** [comment]
published the changes on last Friday
