### ISSUE TITLE
Update guides to use Dev Mode

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#300]
- Enablement for using Dev Mode (e.g. update plugin version so one can use Dev Mode) -- MVP for OC1
- Demonstrate Dev Mode (+ Boost + Test Framework) with select set of guides
- Update all (relevant) guides to use Dev Mode

FYI, @ericglau @kathrynkodama @proubatsis.

**Plan:**
- Phase 1
  - [x] guide-getting-started* (Nimrah)
  - [x] guide-rest-intro* (Nimrah)
- Phase 2
  - [x] guide-cdi-intro* (Nimrah)
  - [x] guide-maven-intro* (Nimrah)
  - [x] guide-microprofile-fallback* (Nimrah & Eveline)
  - [x] guide-rest-client-java* (Nimrah)
  - [x] guide-microprofile-config* (Eveline)
  - [x] guide-microprofile-health* (Eveline)
  - [x] guide-microprofile-openapi* (Nimrah)
  - [x] guide-microshed-testing* (Andrew & Gilbert)
- Phase 3
  - [x] prototype a simple parent pom (Eveline)
- Phase 4
  - [x] guide-microprofile-istio-retry-fallback (Kartik)
  - [x] guide-cloud-ibm (Kartik - ready to publish)
    - addressed https://github.com/OpenLiberty/guide-cloud-ibm/issues/69
    - travis test failed the PR
  - [x] guide-cloud-aws (Danny)
  - [x] guide-gradle-intro (Mai)
  - [x] guide-microprofile-metrics (Nimrah & Eveline & Gilbert)
    - pending on https://github.com/OpenLiberty/ci.maven/issues/630
  - [x] guide-cloud-azure (Nimrah)
  - [x] guide-containerize (Gilbert)
  - [x] guide-istio-intro (Nimrah + Kartik)
  - [x] guide-cloud-openshift (Mai)
  - [x] guide-rest-hateoas (2 services) (Kartik)
  - [x] guide-microprofile-rest-client (Nimrah + Gilbert)
  - [x] guide-kubernetes-intro (Eveline)
  - [x] guide-kubernetes-microprofile-config (Nimrah)
  - [x] guide-kubernetes-microprofile-health (Nimrah)
  - [x] guide-maven-multimodules (Eveline)
  - [x] guide-bean-validation (Nimrah)
  - [x] guide-sessions (Nimrah)
  - [x] guide-cors (Eveline)
  - [x] guide-rest-client-angular (Eveline)
  - [x] guide-rest-client-angularjs* (Eveline)
  - [x] guide-security-intro (Nimrah)
  - [x] guide-spring-boot*
  - [x] guide-okd (Mai) 
- Phase 6 (pending)
  - [ ] guide-microprofile-jwt
    - need to investigate how to generate the keystore etc.
    - will be addressed by https://github.com/openliberty/guide-microprofile-jwt/issues/113
  - [ ] guide-docker (Nimrah - pending further discussion/design)
    - the new LMP may not work in this guide scenario, need further discussion
    - may need to study https://github.com/appsody/stacks/pull/573/files
    - will be addressed by https://github.com/OpenLiberty/guide-docker/issues/74
  - [ ] guide-arquillian-managed (Eveline)
    - pending on a ci.maven issue OpenLiberty/ci.maven#713
    - will be addressed by https://github.com/OpenLiberty/guide-arquillian-managed/pull/68
  - [ ] guide-microprofile-opentracing (Darren - ready for dev content review)
    - will be addressed by https://github.com/openliberty/guides-common/issues/360
  - [ ] guide-microprofile-rest-client-async (in progress)
    - will be addressed by https://github.com/OpenLiberty/guide-microprofile-rest-client-async/issues/53
  - [ ] guide-jpa-intro (Darren -reviewing dev content review again) 
    - pending on how LMP to support third party libraries
    - will be addressed by https://github.com/OpenLiberty/guide-jpa-intro/pull/127
      - https://github.com/OpenLiberty/guide-jpa-intro/issues/135

**Required changes:**
- use the ideal(simplified) pom.xml
- update the Readme content to use dev mode
  - keep the flow same (let discuss if the flow not work)
- convert `*Test` class to `*IT`
- convert to use JUnit 5
  - use JUnit5 test order if need
- make sure to correctly configure the ports in test classes, server.xml, and pom.xml
- update travis test
   - `mvn install` cannot be used to verify anymore

**Comment by gkwan-ibm** [comment]
- working on
  -  https://github.com/OpenLiberty/guide-getting-started/pull/95
  - bootstrap.properties
  - hotspots
  - create the runnable jar

**Comment by gkwan-ibm** [comment]
working on 
- bootstrap.properties
- update the README

Note: liberty:run has issue to run loose application

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/ci.maven/issues/541

**Comment by gkwan-ibm** [comment]
FYI, Up to now, 5 issues for dev-mode
```
Getting Started guide
- Mac (OK)
- Linux
  1. Ctrl+C issue in RHEL (?)
    - may work on Ubantu
    - [ ] https://github.com/OpenLiberty/ci.maven/issues/582
  2. timeout issue (?)
    - [ ] https://github.com/OpenLiberty/ci.maven/issues/586
    - mvn package liberty:dev -DverifyTimeout=120
  3. core dump ((MUST)
    - [ ] https://github.com/OpenLiberty/ci.maven/issues/589
- Windows
  4. Not work (MUST)
    - [ ] https://github.com/OpenLiberty/ci.maven/issues/580
    - https://github.com/OpenLiberty/open-liberty/pull/8140
- All
  5. stop command issue (?)
    - [ ] https://github.com/OpenLiberty/ci.maven/issues/572

Rest Intro guide
- same except core dump
```

**Comment by evelinec** [comment]
- following up list of verifications

**Comment by gkwan-ibm** [comment]
**Verify LMP 3.1-SNAPSHOT, 190010 GM Candidate **

** Preparation **
- Clean local maven repository
  - rm ~/.m2/repository/io/openliberty/tools
- Build liberty maven plugin (LMP) locally
  - git clone https://github.com/OpenLiberty/ci.common.git
  - cd ci.common
  - mvn install
  - git clone https://github.com/OpenLiberty/ci.maven.git
  - cd ci.maven
  - mvn install
- clone the guide
  - for Getting Started
    - git clone https://github.com/OpenLiberty/guide-getting-started.git -b qa
  - for Rest Intro 
    - git clone https://github.com/OpenLiberty/guide-rest-intro.git
- add LMP version in the pox.xml as
```
            <plugin>
                <groupId>io.openliberty.tools</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>3.1-SNAPSHOT</version>
            </plugin>
```
- Verify the Readme and run End-to-End
  - for Getting Started
    - http://lgdev1.fyre.ibm.com:4060/guides/getting-started.html
  - for Rest Intro 
    - http://lgdev1.fyre.ibm.com:4060/guides/rest-intro.html

** Verification **
- OpenJ9 JDK11 latest release, Rest Intro
 - [ ] Mac (Jonathan)
 - [ ] Linux (Eveline)
 - [ ] Windows (Mai)
- OpenJ9 JDK11 latest release, Getting Started
 - [ ] Mac (Jonathan)
 - [ ] Linux (Eveline)
 - [ ] Windows (Mai)
- [ ] Verify https://github.com/OpenLiberty/ci.maven/issues/586 (Danny)
- [ ] Verify https://github.com/OpenLiberty/ci.maven/issues/629 (Danny)
- [ ] Verify https://github.com/OpenLiberty/ci.maven/issues/589 (Nimrah)
- [ ] Verify https://github.com/OpenLiberty/ci.maven/issues/572 (Nimarh)
- [ ] Verify https://github.com/OpenLiberty/ci.maven/issues/609 (Gilbert)

**Comment by gkwan-ibm** [comment]
@yeekangc would you review dev mode?
for Getting Started
   http://lgdev1.fyre.ibm.com:4060/guides/getting-started.html
for Rest Intro
   http://lgdev1.fyre.ibm.com:4060/guides/rest-intro.html

**Comment by evelinec** [comment]
Linux test info: 

```[INFO] --- liberty-maven-plugin:3.0.2-SNAPSHOT:dev (default-cli) @ guide-getting-started ---```

```[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_US)```

**Comment by NimG98** [comment]
Regarding core dump issue OpenLiberty/ci.maven#589:

- Eveline's error above is related to this core dump issue
- Reproduced that the same error occurs with jdk11 openj9 nightly on linux

Other verifications:

OpenJ9 JDK8 latest release (DONE - 1.8.0_222-b10, **FAILED**)
OpenJ9 JDK8 latest nightly (DONE - 1.8.0_232-201910010340-b07, passed)
OpenJ9 JDK11 latest release (DONE - 11.0.4+11, **FAILED**)
OpenJ9 JDK11 latest nightly (DONE - 11.0.5+9, passed)
Hotspot JDK8 latest release (DONE - 1.8.0_222-b10, passed)
Hotspot JDK8 latest nightly (DONE - 1.8.0_232-201910010329-b01, passed)
Hotspot JDK11 latest release (DONE - 11.0.4+11, passed)
Hotspot JDK11 latest nightly (DONE - 11.0.5+9-201910011809, passed)

**Comment by jonathanxue** [comment]
MAC Test info: 

- rest-intro
`[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_CA)`

`[INFO] --- liberty-maven-plugin:3.0.2-SNAPSHOT:dev (default-cli) @ guide-rest-intro ---`


- getting started
`[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_CA)`

`[INFO] --- liberty-maven-plugin:3.0.2-SNAPSHOT:dev (default-cli) @ guide-getting-started ---`

Everything works now.

**Comment by MaiHameed** [comment]
**Verify Liberty Maven Plugin (LMP) 3.0.2-SNAPSHOT with OL 19.0.0.10 GM Candidate* *

On Windows:

Getting Started
---
```
[INFO] --- liberty-maven-plugin:3.0.2-SNAPSHOT:dev (default-cli) @ guide-getting-started ---
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:19.0.0.10:zip.
```
`java -version` produces:
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
End-to-end completed, everything works as expected.

**Comment by gkwan-ibm** [comment]
**Verify the published Liberty Maven Plugin (LMP) 3.1 with OL 19.0.0.10 GM**

**_Preparation:_**
- Clean local maven repository
  - `rm -fr ~/.m2/repository/io/openliberty`
- remove `rm ~/.m2/settings.xml`
- clone the guide (don't reuse)
  - for Getting Started
    - `git clone https://github.com/OpenLiberty/guide-getting-started.git -b qa`
  - for Rest Intro 
    - `git clone https://github.com/OpenLiberty/guide-rest-intro.git -b qa`

**_Verification:_**
- Verify the Readme and run End-to-End from QA site
  - for Getting Started
    - https://qa-guides.mybluemix.net/guides/getting-started.html
  - for Rest Intro 
    - https://qa-guides.mybluemix.net/guides/rest-intro.html
  - make sure the `liberty-maven-plugin:3.1` and `19.0.0.10` are used (being shown in the console)
  - try `mvn clean liberty:run` in the "Building and running the application" section of the Getting started guide
- OpenJ9 JDK8 latest release, Getting Started
  - [ ] Mac (Jonathan)
- Hotspot JDK8 latest release, Rest Intro
  - [ ] Mac (Danny)
- OpenJ9 JDK11 latest release, Rest Intro
  - [ ] Mac (Jonathan)
  - [ ] Windows (Mai)
- OpenJ9 JDK11 latest nightly, Rest Intro
  - [ ] Linux (Nimrah)
- Hotspot JDK11 latest release, Getting Started
  - [ ] Mac (Danny)
  - [ ] Linux (Nimrah)
  - [ ] Windows (Mai)

**Comment by gkwan-ibm** [comment]
**Verify the published Liberty Maven Plugin (LMP) 3.1 with OL 19.0.0.10 GM**

**_Preparation:_**
- Clean local maven repository
  - `rm -fr ~/.m2/repository/io/openliberty`
- remove `rm ~/.m2/settings.xml`
- clone the guide (don't reuse)
  - for Getting Started
    - `git clone https://github.com/OpenLiberty/guide-getting-started.git -b qa`
  - for Rest Intro 
    - `git clone https://github.com/OpenLiberty/guide-rest-intro.git -b qa`

**_Verification:_**
- Verify the Readme and run End-to-End from QA site
  - for Getting Started
    - https://qa-guides.mybluemix.net/guides/getting-started.html
  - for Rest Intro 
    - https://qa-guides.mybluemix.net/guides/rest-intro.html
  - make sure the `liberty-maven-plugin:3.1` and `19.0.0.10` are used (being shown in the console)
- OpenJ9 JDK8 latest release, Getting Started
  - [ ] Mac (Jonathan)
- Hotspot JDK8 latest release, Rest Intro
  - [ ] Mac (Danny)
- OpenJ9 JDK11 latest release, Rest Intro
  - [ ] Mac (Jonathan)
  - [ ] Windows (Mai)
- OpenJ9 JDK11 latest nightly, Rest Intro
  - [ ] Linux (Nimrah)
- Hotspot JDK11 latest release, Getting Started
  - [ ] Mac (Danny)
  - [ ] Linux (Nimrah)
  - [ ] Windows (Mai)

**Comment by yeekangc** [comment]
Should consider having the instructions for launching into dev mode (development mode) as a common include under "Getting Started" as a sub-section after "Try what you'll build".  Should offer proper context/intro to dev mode there too.

**Comment by yeekangc** [comment]
Ref https://github.com/OpenLiberty/guides-common/issues/300#issuecomment-539717496, I filed issues and made comments where appropriate with my feedback.  I am fine for us to move forward to push out the updates.

**Comment by NimG98** [comment]
### Liberty Maven Plugin (LMP) 3.1-SNAPSHOT with OL 19.0.0.10 GM Candidate

**Verifying OpenJ9 JDK11 latest nightly, Rest Intro**:

- Ran end-to-end on qa, looks good to me

- 19.0.0.10 GM:
    `[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.5+9-201910101810 (en_US)`

- 3.1-SNAPSHOT:
    `[INFO] --- liberty-maven-plugin:3.1-SNAPSHOT:dev (default-cli) @ guide-rest-intro ---`


- OpenJ9 JDK11 latest nightly:
    ```
    java -version
    openjdk version "11.0.5" 2019-10-15
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+9-201910101810)
    Eclipse OpenJ9 VM AdoptOpenJDK (build master-0739a278d, JRE 11 Linux amd64-64-Bit . 
    Compressed References 20191010_353 (JIT enabled, AOT enabled)
    OpenJ9   - 0739a278d
    OMR      - 34bbcd21
    JCL      - 642d34017c based on jdk-11.0.5+9)
    ```

**Comment by MaiHameed** [comment]
Liberty Maven Plugin (LMP) 3.1-SNAPSHOT with OL 19.0.0.10 GM Candidate
---
* Ran end-to-end on Windows
* Everything works as expected

From the console:
```
[INFO] --- liberty-maven-plugin:3.1-SNAPSHOT:dev (default-cli) @ guide-getting-started ---
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:19.0.0.10:zip.
```

`messages.log`:
```
product = Open Liberty 19.0.0.10 (wlp-1.0.33.cl191020191002-0300)
java.home = C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-openj9
java.version = 11.0.4
java.runtime = OpenJDK Runtime Environment (11.0.4+11)
os = Windows 10 (10.0; amd64) (en_CA)
```

**Comment by DannyS03** [comment]
### Liberty Maven Plugin (LMP) 3.1-SNAPSHOT with OL 19.0.0.10 GM Candidate
***Getting Started***

```
[INFO] --- liberty-maven-plugin:3.1-SNAPSHOT:dev (default-cli) @ guide-getting-started ---
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:19.0.0.10:zip.
```
- tested end-to-end on qa 

```
product = Open Liberty 19.0.0.10 (wlp-1.0.33.cl191020191002-0300)
java.home = /Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.4.jdk/Contents/Home
java.version = 11.0.4
java.runtime = OpenJDK Runtime Environment (11.0.4+11)
os = Mac OS X (10.14.6; x86_64) (en_CA)
```

**Comment by jonathanxue** [comment]
## Liberty Maven Plugin (LMP) 3.1-SNAPSHOT with OL 19.0.0.10 GM Candidate

rest-intro - OpenJ9 - JDK11 - Mac
- Everything works as expected

Console output:

`[INFO] --- liberty-maven-plugin:3.1-SNAPSHOT:run (default-cli) @ guide-rest-intro ---`
`[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_CA)`

Version output
```openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190823_327 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)```

**Comment by NimG98** [comment]
## Liberty Maven Plugin (LMP) 3.1 with OL 19.0.0.10 GM

**Getting Started: Hotspot JDK 11 latest release, Linux**
- ran end-to-end on qa
- console output:
    `[INFO] --- liberty-maven-plugin:3.1:run (default-cli) @ guide-getting-started ---`

    `[INFO] --- liberty-maven-plugin:3.1:dev (default-cli) @ guide-getting-started ---`

    `[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_US)`

    `[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:19.0.0.10:zip.`

- java version:

    ```
    openjdk version "11.0.4" 2019-07-16
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
    ```

**Rest Intro: OpenJ9 JDK11 latest nightly, Linux**
- ran end-to-end on qa
- console output:

    `[INFO] --- liberty-maven-plugin:3.1:run (default-cli) @ guide-rest-intro ---`

    `[INFO] --- liberty-maven-plugin:3.1:dev (default-cli) @ guide-rest-intro ---`

    `[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:19.0.0.10:zip.`

    `[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.5+9-201910101810 (en_US)`

- java version:

    ```
    openjdk version "11.0.5" 2019-10-15
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+9-201910101810)
    Eclipse OpenJ9 VM AdoptOpenJDK (build master-0739a278d, JRE 11 Linux amd64-64-Bit 
    Compressed References 20191010_353 (JIT enabled, AOT enabled)
    OpenJ9   - 0739a278d
    OMR      - 34bbcd21
    JCL      - 642d34017c based on jdk-11.0.5+9)
    ```

**Comment by MaiHameed** [comment]
Liberty Maven Plugin (LMP) 3.1 with OL 19.0.0.10 GM
---

**Rest Intro:**
* Windows 10
* OpenJ9 JDK11

Console output:
```
[INFO] --- liberty-maven-plugin:3.1:dev (default-cli) @ guide-rest-intro ---
[INFO] CWWKM2102I: Using artifact based assembly archive : io.openliberty:openliberty-kernel:null:19.0.0.10:zip.
```
 
`java -version` output:
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Windows 10 amd64-64-Bit Compressed References 20190717_282 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```
End-to-end completed and everything works as expected.

**Comment by jonathanxue** [comment]
## Rest-Intro (OpenJ9 JDK11) - Mac

`[INFO] --- liberty-maven-plugin:3.1:run (default-cli) @ guide-rest-intro ---`
`[INFO] --- liberty-maven-plugin:3.1:dev (default-cli) @ guide-rest-intro ---`
`[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_CA)`

```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190823_327 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

## Getting Started (OpenJ8 JDK8) - Mac

`[INFO] --- liberty-maven-plugin:3.1:run (default-cli) @ guide-getting-started ---`
`[INFO] --- liberty-maven-plugin:3.1:dev (default-cli) @ guide-getting-started ---`

```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190717_298 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - f147086df1 based on jdk8u222-b10)
```


## ctl-c Error - mvn:liberty-dev

When using `ctl-c` to close the service, the following error appears. Exiting using liberty:stop works fine.

### rest-intro
```
[ERROR] An error occurred while starting the server: CWWKM2002E: Failed to invoke [/Users/jonathan.xueibm.com/Github/guide-rest-intro/finish/target/liberty/wlp/bin/server, debug, defaultServer]. RC= 130 but expected=[0].
org.apache.tools.ant.BuildException: CWWKM2002E: Failed to invoke [/Users/jonathan.xueibm.com/Github/guide-rest-intro/finish/target/liberty/wlp/bin/server, debug, defaultServer]. RC= 130 but expected=[0].
```

### Getting started

```
[ERROR] An error occurred while starting the server: CWWKM2002E: Failed to invoke [/Users/jonathan.xueibm.com/Github/guide-getting-started/start/target/liberty/wlp/bin/server, debug, defaultServer]. RC= 255 but expected=[0].
org.apache.tools.ant.BuildException: CWWKM2002E: Failed to invoke [/Users/jonathan.xueibm.com/Github/guide-getting-started/start/target/liberty/wlp/bin/server, debug, defaultServer]. RC= 255 but expected=[0].
```



- The rest of the guide works normally

**Comment by gkwan-ibm** [comment]
completed expect the following guides which will be handled by individual issues
 - guide-microprofile-jwt
    - need to investigate how to generate the keystore etc.
    - will be addressed by https://github.com/openliberty/guide-microprofile-jwt/issues/113
  - guide-docker (Nimrah - pending further discussion/design)
    - the new LMP may not work in this guide scenario, need further discussion
    - may need to study https://github.com/appsody/stacks/pull/573/files
    - will be addressed by https://github.com/OpenLiberty/guide-docker/issues/74
  - guide-arquillian-managed (Eveline)
    - pending on a ci.maven issue OpenLiberty/ci.maven#713
    - will be addressed by https://github.com/OpenLiberty/guide-arquillian-managed/pull/68
  - guide-microprofile-opentracing (Darren - ready for dev content review)
    - will be addressed by https://github.com/openliberty/guides-common/issues/360
  - guide-microprofile-rest-client-async (in progress)
    - will be addressed by https://github.com/OpenLiberty/guide-microprofile-rest-client-async/issues/53
  - guide-jpa-intro (Darren -reviewing dev content review again) 
    - pending on how LMP to support third party libraries
    - will be addressed by https://github.com/OpenLiberty/guide-jpa-intro/pull/127
      - https://github.com/OpenLiberty/guide-jpa-intro/issues/135
