### ISSUE TITLE
SystemData.java file doesn't have a license header

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guides-common#301]
In both finish and start directories, the `SystemData.java` file doesn't have a license header.

This issue occurs in all cloud guides and kubernetes guides, and might exist in other guides as well.

**Comment by gkwan-ibm** [comment]
In which guide or most guides?

**Comment by NimG98** [comment]
- [ ] cloud-ibm
- [ ] cloud-aws
- [ ] kubernetes-intro
- [ ] kubernetes-microprofile-config
- [ ] kubernetes-microprofile-health
- [ ] cdi-intro

**Comment by evelinec** [comment]
- reviewing the PRs

**Comment by evelinec** [comment]
- one remaining PR in the `master pipeline`, need review - Eveline

**Comment by evelinec** [comment]
- reviewed the last PR for the `cdi` guide, looks good.

**Comment by evelinec** [comment]
Closed.
