### ISSUE TITLE
Guide on using Open Liberty Operator

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#303]
Consider a guide on how to use Open Liberty Operator: https://operatorhub.io/operator/open-liberty

**Comment by gkwan-ibm** [comment]
- prototyping still in progress

**Comment by bschrammIBM** [comment]
It would be good to have this done for CP4Apps 4.2 in June.

**Comment by yeekangc** [comment]
We will integrate usage of Operator(s) particularly the Open Liberty Operator into existing guides (e.g. Deploy to OpenShift guide).  That's where it is most relevant to users/developers.

Actual documentation for Open Liberty Operator should be its repo and should be covered by Open Liberty documentation too.

FYI, @arthurdm @leochr @lauracowen.

**Comment by yeekangc** [comment]
See #411 where we will update the existing OpenShift guide.
