### ISSUE TITLE
Guide for caching microservices with Hazelcast in kubernetes

### ISSUE THREAD

**Issue by enozcan** [OpenLiberty/guides-common#305]
I've just created a guide upon 

- how to use Hazelcast distributed caching with Microprofile,
- deploy it to a local Kube cluster, 
- creating a Kubernetes Service which load balance between containers 
- verifying the data is shared between Microservices.

The guide can be seen [here](https://github.com/enozcan/guide-kubernetes-caching-hazelcast-microprofile). After review, if it's OK for you we can publish it via PR to OpenLiberty repo or something.

**Comment by evelinec** [comment]
Hi @enozcan, thank you for providing the draft content on this topic! Would you take a look at our guide's template repo, https://github.com/OpenLiberty/draft-guides-template, which has the instruction and layout for contributing an OpenLiberty guide. We'll also review the draft content and get back to you. Thank you.

**Comment by evelinec** [comment]
@gkwan-ibm @yeekangc FYI.

**Comment by enozcan** [comment]
@evelinec I've checked the template you've sent and the .adoc file resides under */guides* in my repo more or less conforms to the template. When a repo is initialized for the guide under OpenLiberty, I'll modify the necessary parts (actually a few lines) as explained in the template.

**Comment by evelinec** [comment]
The latest content is located [here](https://github.com/evelinec/caching-microprofile-microservices-on-kubernetes/pull/1).

**Comment by yeekangc** [comment]
Hazelcast team now has a set of guides at https://guides.hazelcast.org/home/.

Closing.  The issue can be re-opened and revisited later as appropriate.
