### ISSUE TITLE
Docker Daily Build Enhancement - Rerun job with same parameters

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guides-common#307]
The Docker Daily Build job job cannot be rerun with the same parameters, if the docker image that a job was run with is not within the 4 hours period. ie, the failed job #291 couldn't be rerun. This is not good for problem investigation and determination.

This might be difficult for the following reason: if we run the job and the test fails using the docker daily build container that contains OL Build Level x, when we try to re-run the job, it is possible that a new docker daily build was pushed so the container now contains OL Build Level y. 

Issue was raised here: https://github.com/OpenLiberty/guides-common/issues/265

**Comment by gkwan-ibm** [comment]
close
- test is migrating to use github action
- if issue/requirement is still valid, will open a new issue
