### ISSUE TITLE
Guide naming convention to match repository name

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/guides-common#308]
for our liberty guides, could we make the `artifactId` be the same thing as the git repo name, which follows the `guide-XXXX` naming convention?
This determines the name of the project when it gets imported into an IDE such as Eclipse. I think it's common for people to have many projects in their workspace, and it can be hard to find the project you just imported. Additionally, if multiple guides are imported, they will be all grouped together

**Comment by yeekangc** [comment]
@gkwan-ibm, let us see what does this mean and what's the scope of the work.

**Comment by gkwan-ibm** [comment]
@aguibert

Yes, not all the guides match to the repo name. I agree to update them.

I tried the guide-cdi-intro. "cdi-intro" is used as the project name. Is it what you suggest? Or you suggest "guide-cdi-intro" as the project name?


![Screen Shot 2019-07-11 at 11 39 08 AM](https://user-images.githubusercontent.com/29576299/61064909-ad728780-a3d0-11e9-8402-c96013d73f49.png)

**Comment by aguibert** [comment]
yes, I would suggest `guide-cdi-intro` in that case. 

The case where I noticed this was for the repo `guide-rest-intro` which just had a project name of `rest`
