### ISSUE TITLE
Create a guide for securing web application/Java EE Security 1.0

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#31]
Securing web application using basic application security.

**Comment by yeekangc** [comment]
This should cover appSecurity-3.0 and hence, Java EE Security 1.0.

**Comment by justineechen** [comment]
Guide Idea A:
Building off the existing events app, make the application multi-paged and emphasize the use of the following security constraints:
- **url-pattern**
- **auth-constraint**
- **user-data-constraint**
- **LTPA**

Guide Idea B:
Building off the existing events app, _keep_ the application single-paged and emphasize the use of new Java EE 1.0 features:
- **EmbeddedIdentityStoreDefinition**
- **Rememberme**

**Comment by evelinec** [comment]
@rhpeters Just as a record, this guide was ready for your review. 

Repo: https://github.com/OpenLiberty/draft-guide-security-intro

**Comment by evelinec** [comment]
Guide is published here: https://openliberty.io/guides/security-intro.html
