### ISSUE TITLE
Test the guides with the 19007 candidate build

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#311]
- [x] Automated tests with jdk8 and jdk11 for all published guides (Eveline)

Manual test the guides against GM with Java11OpenJ9:
- [ ] Getting Start (Andrew)
- [x] Kube Intro (Mai)
- [x] Gradle (Danny)
- [x] Maven Intro (Nirmah)
- [x] JWT (Eveline HotspotJDK8 + Java11OpenJ9)
- [x] Docker (Danny) 
- Make sure to run the `docker pull open-liberty` command before running the `docker build` command to make sure the latest docker image is being pulled in and used in the test.
- [x] IBM Cloud (Andrew)
- [x] Azure draft (Eveline)
- [x] new docker draft (Eveline)
- [x] Sessions draft (Gilbert)

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform
- for any guide using docker, make sure to use the GM candidate docker image

**Comment by evelinec** [comment]
Since the `security-intro` automation test history was missing (see #310), it's tested manually with the candidate build and JDK11. 

Launching defaultServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_CA)

**Comment by evelinec** [comment]
Tested JWT guide: 
Launching defaultServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_CA)

**Comment by DannyS03** [comment]
**`Docker Guide`** 
- Tested end-to-end in the `start` directory with `19.0.0.7-cl190720190711-1115` candidate build using `openjdk 11`.
- macOS Mojave version 10.14.5 

```
Launching defaultServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```
```
Sending build context to Docker daemon  151.9MB
Step 1/6 : FROM guidesbot/olguides:cl190720190711-1115
 ---> a66fd7669626
Step 2/6 : USER root
 ---> Using cache
 ---> 4197e195074d
Step 3/6 : RUN ln -s /opt/ol/wlp/usr/servers /servers
 ---> Using cache
 ---> 2cd557ad15e9
Step 4/6 : USER 1001
 ---> Using cache
 ---> 17e6e076043e
Step 5/6 : ENTRYPOINT ["/opt/ol/wlp/bin/server", "run"]
 ---> Using cache
 ---> 5a0f36648e04
Step 6/6 : CMD ["defaultServer"]
 ---> Using cache
 ---> 516f1d3d8d06
Successfully built 516f1d3d8d06
Successfully tagged ol-runtime:latest
```

**Comment by DannyS03** [comment]
**`Gradle Guide`** 
- Tested end-to-end in the `finish` directory with `19.0.0.7-cl190720190711-1115` candidate build using `openjdk 11`.
- macOS Mojave version 10.14.5 
```
Launching defaultServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```

**Comment by NimG98** [comment]
Maven Intro Guide:

- followed guide and tested end-to-end with jdk 11
- Tested on Mac
- Tested with GM build `19.0.0.7-cl190720190711-1115`


From console.log:
```
Launching ServletSampleServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```

**Comment by andrewdes** [comment]
Getting-Started Guide

- followed guide and tested end-to-end with jdk 11
- Tested on Mac
- Tested with GM build 19.0.0.7-cl190720190711-1115

From console.log:
`Launching GettingStartedServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on OpenJDK 64-Bit Server VM, version 11.0.3+7 (en_CA)`


**Issues while running this guide**: 
I ran `mvn install liberty:run-server` and when I got to the part in the image below, I followed the instructions and all the outputs were the same. However, when accessing the `/health` endpoint again, it never updated. After stopping and then restarting the server, I got the correct output from the `/health` endpoint. But **not** after running `mvn compile` and then accessing the endpoint as the guide instructs.
![image](https://user-images.githubusercontent.com/22628575/61241942-8e4a6180-a712-11e9-8229-a9207ad8c516.png)

**Comment by evelinec** [comment]
Tested `docker image` guide with: 

Launching defaultServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_CA)

**Comment by evelinec** [comment]
Tested the Azure guide: 

[INFO] --- liberty-maven-plugin:2.7:install-server (create-server) @ inventory ---
[INFO] CWWKM2102I: Using installDirectory : /Users/evelinec/OLG/testing/19007/draft-guide-cloud-azure/finish/inventory/target/liberty/wlp.
[INFO] CWWKM2102I: Using serverName : defaultServer.
[INFO] CWWKM2102I: Using serverDirectory : /Users/evelinec/OLG/testing/19007/draft-guide-cloud-azure/finish/inventory/target/liberty/wlp/usr/servers/defaultServer.
[INFO] CWWKM2185I: The liberty-maven-plugin configuration parameter "appsDirectory" value defaults to "dropins".
[INFO] Getting: http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-07-11_1115/openliberty-all-19.0.0.7-cl190720190711-1115.zip

docker build -t system system/.
Sending build context to Docker daemon  169.9MB
Step 1/2 : FROM guidesbot/olguides:cl190720190711-1115
cl190720190711-1115: Pulling from guidesbot/olguides


docker build -t inventory inventory/.
Sending build context to Docker daemon  170.8MB
Step 1/2 : FROM guidesbot/olguides:cl190720190711-1115

**Comment by andrewdes** [comment]
IBM Cloud:
- followed guide and tested end-to-end with jdk 11
- Tested on Mac
- Tested with GM build 19.0.0.7-cl190720190711-1115

From console.log:
`Launching defaultServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on OpenJDK 64-Bit Server VM, version 11.0.3+7 (en_CA)`

**Comment by MaiHameed** [comment]
`kube-intro`

Launching defaultServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190820190715-1900) on IBM J9 VM, version 8.0.5.37 - pxa6480sr5fp37-20190618_01(SR5 FP37) (en_US)

**Comment by evelinec** [comment]
> Getting-Started Guide
> 
> * followed guide and tested end-to-end with jdk 11
> * Tested on Mac
> * Tested with GM build 19.0.0.7-cl190720190711-1115
> 
> From console.log:
> `Launching GettingStartedServer (Open Liberty 19.0.0.7/wlp-1.0.30.cl190720190711-1115) on OpenJDK 64-Bit Server VM, version 11.0.3+7 (en_CA)`
> 
> **Issues while running this guide**:
> I ran `mvn install liberty:run-server` and when I got to the part in the image below, I followed the instructions and all the outputs were the same. However, when accessing the `/health` endpoint again, it never updated. After stopping and then restarting the server, I got the correct output from the `/health` endpoint. But **not** after running `mvn compile` and then accessing the endpoint as the guide instructs.
> ![image](https://user-images.githubusercontent.com/22628575/61241942-8e4a6180-a712-11e9-8229-a9207ad8c516.png)

@andrewdes I tried the guide and couldn't reproduced the problem you described. Not sure if you had started the server at this prior step, "Updating the server configuration without restarting the server -> Try updating the server configuration while the server is running. If you stopped the server, start it again before you proceed." I had the server running, then when making changes and running the `mvn compile` command, it's able to show the new result, as described in the guide. 

Note, I only tried with the release build.

**Comment by evelinec** [comment]
Looks like the 19007 build does have this problem. @andrewdes can you investigate further?

**Comment by evelinec** [comment]
We need to test the other mp health guide(s) to see if the same problem exists. Will work with @andrewdes

**Comment by gkwan-ibm** [comment]
- need an issue for OL
- need a workaround for getting start guide
- need to try the mp health guide

**Comment by evelinec** [comment]
@andrewdes will investigate this issue as described above.

**Comment by evelinec** [comment]
Issue opened for the problem found: https://github.com/OpenLiberty/open-liberty/issues/8304

**Comment by evelinec** [comment]
@andrewdes did you test how many guides are impacted by this issue?

**Comment by andrewdes** [comment]
@evelinec working on it now, will update the issue with my findings

**Comment by andrewdes** [comment]
The mp-health guide and Kube-health have been tested and are successful.

**Comment by evelinec** [comment]
Potentially, user checking out those two guides (mp health check, and kube health), if they happen to go through this path: start the server to visit the /health endpoint, create the health check, run `mvn compile` (while the server is still running), then visit the /health endpoint again, they will run into this issue.

**Comment by evelinec** [comment]
Team is working on fixing this issues on the impacted guides.

**Comment by evelinec** [comment]
Regression issue is closed. I believe this is completed now. Closed.
