### ISSUE TITLE
Daily build tests

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#315]
This task is to monitor the daily build CI tests for the guides:

- Published Guides Dashboard
- Daily Docker Images Dashboard

**Comment by evelinec** [comment]
Issues for today: 
- investigate the missing 8/4 build tests
- investigate the failed 8/5 build tests
- find out why there haven't been any new daily docker image?

**Comment by justineechen** [comment]
-  Build tests may be hanging, Mai will investigate
