### ISSUE TITLE
Modify introductory paragraph of Cloud guides

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guides-common#317]
Based off of review feedback, the introduction of the cloud guides has been modified. The rest of the cloud guides should be updated for consistency.

Change the following paragraph:

> There are different cloud-based solutions for running your workloads in a Kubernetes cluster. A cloud-based infrastructure enables you to focus on developing your microservices without worrying about details related to the servers you deploy them to. Using a cloud helps you to easily scale and serve your microservices in a high-availability setup.

To:

> There are different cloud-based solutions for running your Kubernetes workloads. 
A cloud-based infrastructure enables you to focus on developing your microservices without worrying about low-level infrastructure details for deployment. Using a cloud helps
you to easily scale and manage your microservices in a high-availability setup.

Guides to change:

- [x] cloud-ibm
- [x] cloud-aws
- [x] cloud-azure
- [x] cloud-openshift

**Comment by justineechen** [comment]
Updated cloud-ibm, cloud-azure, cloud-openshift on docker-update branches
