### ISSUE TITLE
Further emphasis for switching between finish and start folders

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#318]
We have found that users might be confused with switching between the finish and start directories even if the instructions are provided in the guides.

We should see how we can improve to emphasize or clarify (via design or otherwise) the switch between the folders to avoid confusion and stress when working through the guides.

**Comment by gkwan-ibm** [comment]
We can consider to add a `cd` command box

**Comment by gkwan-ibm** [comment]
dup of https://github.com/OpenLiberty/guides-common/issues/514

**Comment by gkwan-ibm** [comment]
close
- addressed by #514
