### ISSUE TITLE
Maven parent pom from OpenLiberty org instead of WASdev

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#329]
In the MP JWT guide, the [pom.xml](https://github.com/OpenLiberty/guide-microprofile-jwt/blob/master/start/pom.xml) references the Maven parent pom. We now have the [`ci.maven` repo in the OpenLiberty Github org](https://github.com/openliberty/ci.maven). So should the guide (and any other guides) be updated to use the OpenLiberty org's version of the Maven parent pom?

**Comment by stephenpatten** [comment]
I have found numerous places in the guides both Maven and Gradle based where the was dev was used and out dated to boot! :)

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
@stephenpatten, we are converting the guides to use the latest Liberty Maven Plugin 3.1+. In this moment, not all the guides were converted.

**Comment by gkwan-ibm** [comment]
will be addressed by https://github.com/OpenLiberty/guide-microprofile-jwt/issues/113

**Comment by gkwan-ibm** [comment]
close
- OpenLiberty/guide-microprofile-jwt#113 was done
- the pom.xml files of the MP JWT guide are not using parent pom and the new Liberty Maven Plugin 3.3.1
