### ISSUE TITLE
Git clone in Jenkins is not working properly

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#341]
Git clone in Jenkins for the `was-liberty/olguides-automation` repo: 

/home/jenkins/workspace/ECTestingJob/scripts/jenkins-automation/test-all-dhe-dev-builds
total 28
-rwxrwxr-x 1 jenkins jenkins 4411 Sep 11 20:43 generateTestReport.sh
-rwxrwxr-x 1 jenkins jenkins 1609 Sep 11 20:43 getAllDHEDailyBuilds.sh
**-rwxrwxr-x 1 jenkins jenkins 8072 Sep 11 20:43 testADHEDailyBuildForAllRepos.sh
-rwxrwxr-x 1 jenkins jenkins 5568 Sep 11 20:43 testADHEDailyBuildForDraftRepos.sh**
#!/bin/bash

Actual script file size today: 

-rwxr-xr-x  1 evelinec  staff  4411 11 Sep 16:47 generateTestReport.sh
-rwxr-xr-x  1 evelinec  staff  1609 11 Sep 16:47 getAllDHEDailyBuilds.sh
**-rwxr-xr-x  1 evelinec  staff  8250 11 Sep 16:47 testADHEDailyBuildForAllRepos.sh
-rwxr-xr-x  1 evelinec  staff  5371 11 Sep 16:47 testADHEDailyBuildForDraftRepos.sh**

The `testADHEDailyBuild*` scripts are different size. 

Potentially the `git` credential in Jenkins may need to be updated. Need to investigate this problem further.

**Comment by DannyS03** [comment]
- Credentials seem fine and so does configuration but it might have something to do with the Jenkins`shallow` cloning the repos. Still looking into it.

**Comment by gkwan-ibm** [comment]
The reason was that Test-A-DHE-Daily-Build-Linux-DRAFT used test-draft-guides branch.  It was fixed to use master branch.
