### ISSUE TITLE
Jakarta EE 8 updates

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#354]
Update guides to use Jakarta EE 8 dependencies.

**Comment by gkwan-ibm** [comment]
Most guides were updated except following:
- [ ] guide-microprofile-health
- guide-docker
  - https://github.com/OpenLiberty/guide-docker/issues/74
- guide-microprofile-opentracing
  - https://github.com/OpenLiberty/guides-common/issues/360
- guide-microprofile-jwt
  - https://github.com/OpenLiberty/guide-microprofile-jwt/issues/113
- guide-jpa-intro
   - https://github.com/OpenLiberty/guide-jpa-intro/issues/135
- guide-arquillian-managed
  - https://github.com/OpenLiberty/guide-arquillian-managed/issues/71
- guide-microprofile-rest-client-async
  - https://github.com/OpenLiberty/guide-microprofile-rest-client-async/issues/53

**Comment by gkwan-ibm** [comment]
Most guides were addressed. The remaining guides will be addressed by individual issue. See https://github.com/OpenLiberty/guides-common/issues/354#issuecomment-632935531
