### ISSUE TITLE
Formatting of XML tags in hotspots inconsistent

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guides-common#355]
Different guides use different formatting to display an XML tag hotspot. For example, in the [Containerizing Microservices](https://openliberty.io/guides/containerize.html) guide, it just displays the start tag:

![image](https://user-images.githubusercontent.com/26514093/66074581-876c0780-e527-11e9-8816-c24a231aa847.png)

While other guides such as the [Docker](https://openliberty.io/guides/docker.html#building-your-application) guide mostly use the following:

![image](https://user-images.githubusercontent.com/26514093/66074665-b6827900-e527-11e9-8123-218824d823a7.png)

It doesn't seem to match the usual style of an XML tagging style: `<tag>...</tag>` so shouldn't we keep formatting of XML tags as such: `</tag>` instead of `<tag/>`?

**Comment by gkwan-ibm** [comment]
we should use `<tag/>`
