### ISSUE TITLE
Test the guide with 190010 candidate build

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#356]
- [x] Automated tests with jdk8 and jdk11 for all published guides (Nimrah)

Manual test the guides against GM with Java11OpenJ9:
- [x] Getting Start - Dev Mode (Nimrah)
- [x] Kube Intro  (Nimrah)
- [x] Gradle (Danny)
- [x] Maven Intro  (Danny)
- [x] JWT (Mai)
- [x] Docker-intro (Mai)
- Make sure to run the `docker pull open-liberty` command before running the `docker build` command to make sure the latest docker image is being pulled in and used in the test.

- [x] Rest Intro Dev Mode (Jonathan)
- [x] FT (Eveline)
- [x] Metrics (Eveline)

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform
- for any guide using docker, make sure to use the GM candidate docker image

**Comment by gkwan-ibm** [comment]
- GM candidate cl191020191002-0300

**Comment by MaiHameed** [comment]
JWT
---
```
Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_CA)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKF0012I: The server installed the following features: [el-3.0, jsp-2.3, servlet-3.1].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 4.186 seconds.
```

**Comment by jonathanxue** [comment]
## Rest Intro Dev Mode

- Used cl191020191002-0300
- OpenJ9 v11
- Ran on Mac OS

```
[INFO] Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_CA)
[INFO] [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[INFO] [AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[INFO] [AUDIT   ] CWWKT0016I: Web application available (default_host): http://jonathans-mbp.war.can.ibm.com:9080/LibertyProject/
```

**Comment by NimG98** [comment]
### **Getting Started (Dev Mode):**

- followed guide and tested end-to-end with java11openj9
- Tested on Mac
- Tested with GM build `openliberty-19.0.0.10-cl191020191002-0300`

From dev mode output:
```
Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```

From `docker logs gettingstarted-app`:
```
Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on IBM J9 VM, version 8.0.5.41 - pxa6480sr5fp41-20190919_01(SR5 FP41) (en_US)
```

**Comment by evelinec** [comment]
Tested FT and Metrics guides (with the latest update to mpMetrics-2.0): 

Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)

**Comment by MaiHameed** [comment]
Docker Intro
---
- Used `cl191020191002-0300`
- OpenJ9 v11
- Ran on Mac OS
```
Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_CA)
```

**Comment by DannyS03** [comment]
### **Maven Intro:**

- Tested end-to-end with `19.0.0.10-cl191020191002-0300` candidate.
- macOS Mojave version 10.14.6.

```
Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```

**Comment by NimG98** [comment]
### **Kube Intro:**

- followed guide and tested end-to-end with java11openj9
- Tested on Mac
- Tested with GM build `openliberty-19.0.0.10-cl191020191002-0300`

From `kubectl logs <pod-name>`:
```
Launching defaultServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on IBM J9 VM, version 8.0.5.41 - pxa6480sr5fp41-20190919_01(SR5 FP41) (en_US)
```

**Comment by DannyS03** [comment]
### **Gradle:**

- Tested end-to-end with `19.0.0.10-cl191020191002-0300` candidate.
- macOS Mojave version 10.14.6.

```
Launching GradleSampleServer (Open Liberty 19.0.0.10/wlp-1.0.33.cl191020191002-0300) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```

**Comment by gkwan-ibm** [comment]
Do manually test the following with GM build and Docker image created by guidesbot (Nimrah):
- [ ] guide-microprofile-istio-retry-fallback JDK8 
- [ ] guide-microprofile-istio-retry-fallback JDK11
- [ ] guide-kubernetes-microprofile-health JDK11
