### ISSUE TITLE
Guide to cover OKD

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#358]
- Cover OKD as the upstream open source option
- Update title, abstract and front matter to reflect coverage for OKD
- Setup structure to cover OpenShift Container Platform down the road

@gkwan-ibm @MaiHameed

**Comment by evelinec** [comment]
- Peer review in progress - Nimrah

**Comment by gkwan-ibm** [comment]
- SME review in progress
- simplifying the pom.xml

**Comment by gkwan-ibm** [comment]
- addressing SME review
- user review can be started soon

**Comment by gkwan-ibm** [comment]
- SME review completed
- addressing user review

**Comment by ankitagrawa** [comment]
On hold for final content review.

**Comment by gkwan-ibm** [comment]
- addressing the final content review feedback
- then ID review

**Comment by gkwan-ibm** [comment]
- ID review in progress

**Comment by gkwan-ibm** [comment]
- addressed ID review feedback
- addressing final review feedback and Jimmy will help to review

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/okd.html.
