### ISSUE TITLE
Add DCO contributor file to all guides for text contributions

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#359]
For external contributors to the guides text, it would be good to adopt an approach similar to this https://github.com/bndtools/bnd/blob/master/CONTRIBUTING.md#sign-your-work using the DCO.

 Discussed with @gcharters and @yeekangc  Just double-checking with @NottyCode .

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by yeekangc** [comment]
We are good to go with this so we will update contribution guidelines accordingly.

@NottyCode indicated that @cbridgha is looking at electronic CLA too.  Can batch up the updates to cover electronic CLA (if it's ready) as well.

**Comment by gkwan-ibm** [comment]
Contributing to the guide:
- Raising issues
- Text or content contribution
- Code contribution

 indicate where can they go for help too.

**Comment by gkwan-ibm** [comment]
- The Contribution.md file is ready review

**Comment by gkwan-ibm** [comment]
- addressing dev content review feedback

**Comment by gkwan-ibm** [comment]
- waiting stakeholder to approve the final change

**Comment by yeekangc** [comment]
Great and thank you, @gkwan-ibm @DannyS03.

I suppose it doesn't hurt to have one for guides-common repo though it will require special instructions to work with the content/assets under guides-common.
