### ISSUE TITLE
Incorrect Grammar on the "contribute to this guide" page

### ISSUE THREAD

**Issue by amyreit** [OpenLiberty/guides-common#36]
The sentence on the "contribute to this guide" page uses incorrect grammar - "Is something missing or needs to be fixed?" The subject is "something" and the verb is "is" which makes it "something is missing" and "something is needs" - should be "needing". This is used throughout interactive and static guides.

OpenLiberty/iguides-common#98 is the same

**Comment by yeekangc** [comment]
@bcpswope @sishida, FYI and please take a look at this issue.

**Comment by bcpswope** [comment]
Parallelism problem. I need to find this page so I can see it and I will rewrite.
