### ISSUE TITLE
Create a guide for MP Open Tracing to use Jaeger

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#360]
@fmhwong commented on [Tue Oct 22 2019](https://github.com/OpenLiberty/open-liberty/issues/9417)

LG-37: Jaeger support in MicroProfile Open Tracing https://github.com/OpenLiberty/open-liberty/issues/6906

Please create a new OpenTracing guide and use Jaeger as the tracing backend.

also,
- dev mode
- mp 3.3
- jakartaee 
- ideal pom

**Comment by yeekangc** [comment]
Open Tracing is going away so we will update existing guide to cover Jaeger, which is the default for Kube/Istio, as opposed to creating a brand new guide.

Should queue up another item for the replacement for MP Open Tracing (may be MP Open Telemetry) when it's ready.

**Comment by gkwan-ibm** [comment]
- made the app work
- will update the readme

**Comment by gkwan-ibm** [comment]
- addressing dev content review

**Comment by gkwan-ibm** [comment]
- addressed dev content review feedback
- next peer review

**Comment by gkwan-ibm** [comment]
When this is resolved, the following issues can be closed:
- https://github.com/OpenLiberty/guide-microprofile-opentracing/issues/11
- https://github.com/OpenLiberty/guide-microprofile-opentracing/issues/40
- https://github.com/OpenLiberty/guide-microprofile-opentracing/issues/58
- https://github.com/OpenLiberty/guide-microprofile-opentracing/issues/74
- https://github.com/OpenLiberty/guide-microprofile-opentracing/issues/75

**Comment by gkwan-ibm** [comment]
- trying to use screenshot to show the spans instead of text

**Comment by gkwan-ibm** [comment]
- addressing the peer review feedback

**Comment by gkwan-ibm** [comment]
- peer review completed
- next SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by meswan** [comment]
- Waiting on SME

**Comment by gkwan-ibm** [comment]
- need to create a new repo

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- addressing SME review feedback

**Comment by gkwan-ibm** [comment]
- draft guide repo was created

**Comment by k-rtik** [comment]
repo: https://github.com/OpenLiberty/draft-guide-microprofile-opentracing-jaeger

**Comment by gkwan-ibm** [comment]
- addressed SME feedback and waiting approval
- next user review

**Comment by gkwan-ibm** [comment]
- need to address the additional prereq section and to mention the env vars in pom.xml

**Comment by gkwan-ibm** [comment]
- ready to review again. After, it is ready for the final content review

**Comment by gkwan-ibm** [comment]
- addressing GK feedback

**Comment by gkwan-ibm** [comment]
- user review review completed
- next final content review

**Comment by gkwan-ibm** [comment]
- addressing final content review feedback

**Comment by gkwan-ibm** [comment]
- final content review completed
- next is ID review

**Comment by gkwan-ibm** [comment]
- ID review in progress

**Comment by meswan** [comment]
Addressing ID review feedback

**Comment by yeekangc** [comment]
Should update the existing guide to reflect that it's for Zipkin.

**Comment by gkwan-ibm** [comment]
@yeekangc 
PR https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/113 to update the existing opentracing guide will be published together

**Comment by yeekangc** [comment]
Thank you, team!  Let us proceed to publish this guide.

**Comment by gkwan-ibm** [comment]
https://openliberty.io/guides/microprofile-opentracing-jaeger.html
