### ISSUE TITLE
Test the guide with 190011 candidate build

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#361]
- [x] Automated tests with jdk8 and jdk11 for all published guides (Nimrah)

Manual test the guides against GM with Java11OpenJ9:
- [x] Getting Start (Mai) Linux
- [x] Kube Intro  (Nimrah)
- [x] Gradle (Danny) Win
- [x] Maven Intro   (Mai)
- [x] JWT (Danny) Win
- [x] Docker-intro (Nimrah) 
- Make sure to run the `docker pull open-liberty` command before running the `docker build` command to make sure the latest docker image is being pulled in and used in the test.

- [x] FT (Eveline) + dev mode
- [x] Metrics (Eveline) + dev mode
- [x] Rest Client (Eveline) 
- [x] Spring Boot (Jonathan)

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform
- for any guide using docker, make sure to use the GM candidate docker image

**Comment by DannyS03** [comment]
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-10-31_0300/

**Comment by evelinec** [comment]
Tested Metrics guide on MacOS: 

`[INFO] Launching defaultServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)`

**Comment by evelinec** [comment]
Tested the Fallback guide on MacOS with dev mode: 

`[INFO] Launching defaultServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)`

**Comment by DannyS03** [comment]
## JWT
- tested on windows 
```
Launching backendServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)
```

**Comment by NimG98** [comment]
### **Kube Intro:**

- followed guide and tested end-to-end with java11openj9
- Tested on Mac
- Tested with GM build `openliberty-19.0.0.11-cl191120191031-0300`

From `docker build` command output:
```
Step 1/2 : FROM guidesbot/olguides:cl191120191031-0300
```

From `kubectl logs <pod-name>`:
```
Launching defaultServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on IBM J9 VM, version 8.0.5.41 - pxa6480sr5fp41-20190919_01(SR5 FP41) (en_US)
```

**Comment by evelinec** [comment]
Tested Rest Client guide on MacOS (without dev mode): 

`Launching defaultServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)`

**Comment by NimG98** [comment]
### **Docker Guide:**

- followed guide and tested end-to-end
- Tested on Mac
- Tested with GM build `openliberty-19.0.0.11-cl191120191031-0300`

From `console.log`:
```
Launching defaultServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```
From `docker logs <container>`:
```
Launching defaultServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on IBM J9 VM, version 8.0.5.41 - pxa6480sr5fp41-20190919_01(SR5 FP41) (en_US)
```

**Comment by jonathanxue** [comment]
Spring Boot

```
product = Open Liberty 19.0.0.11 (wlp-1.0.34.cl191120191031-0300)
wlp.install.dir = /Users/jonathan.xueibm.com/Github/draft-guide-spring-boot/start/target/liberty/wlp/
java.home = /Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home
java.version = 11.0.4
java.runtime = OpenJDK Runtime Environment (11.0.4+11)
os = Mac OS X (10.14.6; x86_64) (en_CA)
```
Docker logs

```
Sending build context to Docker daemon  17.65MB
Step 1/6 : FROM guidesbot/olguides:cl191120191031-0300 as staging
---> 7dd000c0297c
Step 2/6 : COPY --chown=1001:0 target/guide-spring-boot-0.1.0.jar                     /staging/fat-guide-spring-boot-0.1.0.jar
---> d6903b591019
Step 3/6 : RUN springBootUtility thin  --sourceAppPath=/staging/fat-guide-spring-boot-0.1.0.jar  --targetThinAppPath=/staging/thin-guide-spring-boot-0.1.0.jar  --targetLibCachePath=/staging/lib.index.cache
---> Running in 5569a33a932a
Creating a thin application from: /staging/fat-guide-spring-boot-0.1.0.jar
Library cache: /staging/lib.index.cache
Thin application: /staging/thin-guide-spring-boot-0.1.0.jar
Removing intermediate container 5569a33a932a
---> bb88de0e163e
Step 4/6 : FROM guidesbot/olguides:cl191120191031-0300
---> 7dd000c0297c
Step 5/6 : COPY --from=staging /staging/lib.index.cache /lib.index.cache
---> Using cache
---> 4b6cafe96de2
Step 6/6 : COPY --from=staging /staging/thin-guide-spring-boot-0.1.0.jar                     /config/dropins/spring/thin-guide-spring-boot-0.1.0.jar
```

NOTE: docker logs -f springBootContainer throws an error when following the guide

The server.xml file doesn't exist when the guide calls for this command the very first time.

`[ERROR   ] CWWKZ0005E: The server is not configured to handle the resource at location /opt/ol/wlp/usr/servers/defaultServer/dropins/spring/thin-guide-spring-boot-0.1.0.jar.`

**Comment by MaiHameed** [comment]
# Getting Started

- Ran on a Linux VM hosted on Fyre
```
  Operating System: CentOS Linux 7 (Core)
            Kernel: Linux 3.10.0-957.12.2.el7.x86_64
      Architecture: x86-64
```
- Used JDK11 Open J9
```
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

console.log
```
********************************************************************************
product = Open Liberty 19.0.0.10 (wlp-1.0.33.cl191020191002-0300)
wlp.install.dir = /root/guide-getting-started/start/target/liberty/wlp/
java.home = /root/okd/dependencies/jdk-11.0.4+11
java.version = 11.0.4
java.runtime = OpenJDK Runtime Environment (11.0.4+11)
os = Linux (3.10.0-957.12.2.el7.x86_64; amd64) (en_CA)
process = 19227@172.16.42.205
********************************************************************************
```

Everything works as expected.

**Comment by MaiHameed** [comment]
# Maven Intro
- Ran on MacOS 10.15 Catalina
- Open J9 JDK 11

console.log
```
********************************************************************************
product = Open Liberty 19.0.0.11 (wlp-1.0.34.cl191120191031-0300)
wlp.install.dir = /Users/maihameed@ibm.com/Documents/GUIDES/guide-maven-intro/finish/target/liberty/wlp/
java.home = /Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home
java.version = 11.0.3
java.runtime = OpenJDK Runtime Environment (11.0.3+7)
os = Mac OS X (10.15; amd64) (en_CA)
process = 35620@mais-mbp.war.can.ibm.com
********************************************************************************
```
