### ISSUE TITLE
Create common adocs for dev mode guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#364]
The current dev mode converted guides aren't using any commonly shared adocs for the information that are the same on all guides. It'd be good to create common adocs for common steps.

**Comment by NimG98** [comment]
**Try what you’ll build**
- [ ] beginning:

    ![image](https://user-images.githubusercontent.com/46586499/69071880-b9aec700-09f8-11ea-9040-7eb2ce3f4fbd.png)

- [ ] ending:    

    ![image](https://user-images.githubusercontent.com/46586499/69071921-caf7d380-09f8-11ea-98f9-46b2eeb66253.png)


**Other**
- [ ] starting dev mode:

    ![image](https://user-images.githubusercontent.com/46586499/69071991-ee228300-09f8-11ea-9887-84906bd9f9f7.png)

**Building and running the application**
- [ ] beginning:

    ![image](https://user-images.githubusercontent.com/46586499/69072084-15795000-09f9-11ea-8f6b-61e8061ebad4.png)

**Running the tests**:
- [ ] beginning:

    ![image](https://user-images.githubusercontent.com/46586499/69072155-32158800-09f9-11ea-9d46-5b54742feb15.png)

- [ ] exit dev mode

    ![image](https://user-images.githubusercontent.com/46586499/69072233-52454700-09f9-11ea-8ea1-00f3708ec21a.png)

**Comment by evelinec** [comment]
Discussed with @NimG98, she'll work on this issue.

**Comment by evelinec** [comment]
Changes verified. Closed.
