### ISSUE TITLE
Some dev mode conversion impacts on the guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#367]
Just thought to list the observations from dev mode conversion for the guides. 

### 1. The console error messages is displayed on the test results for `unknown` hostname test cases. ie, 
```
[INFO] Running it.io.openliberty.guides.inventory.InventoryEndpointIT
[INFO] [WARNING ] Interceptor for {http://client.inventory.guides.openliberty.io/}SystemClient has thrown exception, unwinding now
[INFO] Could not send Message.
[INFO] [err] The specified host is unknown.
```
**Guides impacted:**
- [x] guide-microprofile-rest-client
- [x] guide-microprofile-config
- [x] guide-cdi-intro
- [x] guide-microprofile-openapi

### 2. The warning messages is displayed on the test results when a service is `DOWN`. ie, 
```
[INFO] Running it.io.openliberty.guides.health.HealthIT
[INFO] [WARNING ] CWMH0052W: The class com.ibm.ws.microprofile.health.impl.HealthCheckResponseImpl implementing HealthCheckResponse in the guide-microprofile-health application in module guide-microprofile-health.war, reported a DOWN status with data Optional[{services=not available}].
```
**Guides impacted:**
- [x] guide-microprofile-health

### 3. Some intermediate error messages while building the code in the `start`. ie, 
```
[INFO] [ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty private io.openliberty.guides.system.SystemConfig.email InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property io_openliberty_guides_email was not found in the configuration.
[INFO] 	at com.ibm.ws.microprofile.config.impl.AbstractConfig.getValue(AbstractConfig.java:175)
[INFO] 	at [internal classes]
```
**Guides impacted:**
- [x] guide-microprofile-config

### 4. Creating blank server.xml using `touch` command:
```
[INFO] [AUDIT   ] CWWKG0016I: Starting server configuration update.
[INFO] [ERROR   ] CWWKG0014E: The configuration parser detected an XML syntax error while parsing the root of the configuration and the referenced configuration documents. Error: Premature end of file. File: file:/Users/Nimrah.Gill@ibm.com/dev-mode-testing/guide-sessions/start/target/liberty/wlp/usr/servers/defaultServer/server.xml Line: 1 Column: 1
```
**Guides impacted:**
- [ ] guide-session

**Comment by jj-zhang** [comment]
### Guide checklist:

-  [ ] guide-microprofile-rest-client

```
[INFO] [WARNING ] Interceptor for {http://client.inventory.guides.openliberty.io/}SystemClient has thrown exception, unwinding now
[INFO] Could not send Message.
[INFO] [err] The specified host is unknown.
```

- [ ] guide-microprofile-health

```
[INFO] [WARNING ] CWMH0052W: The class com.ibm.ws.microprofile.health.impl.HealthCheckResponseImpl implementing HealthCheckResponse in the guide-microprofile-health application in module guide-microprofile-health.war, reported a DOWN status with data Optional[{}].
```

- [ ] guide-cdi-intro

```
[INFO] Running it.io.openliberty.guides.inventory.InventoryEndpointIT
[INFO] [WARNING ] Interceptor for {http://badhostname:9080/system/properties}WebClient has thrown exception, unwinding now
[INFO] Could not send Message.
[INFO] [err] Runtime exception: java.net.UnknownHostException: UnknownHostException invoking http://badhostname:9080/system/properties: badhostname
```

**Comment by tt-le** [comment]
### 1. The console error messages is displayed on the test results for unknown hostname test cases. 
- [x] guide-microprofile-rest-client addressed in https://github.com/OpenLiberty/guide-microprofile-rest-client/pull/138
- [x] guide-microprofile-config addressed in https://github.com/OpenLiberty/guide-microprofile-config/pull/153
- [x] guide-cdi-intro addressed in https://github.com/OpenLiberty/guide-cdi-intro/pull/157
- [x] guide-microprofile-openapi addressed in https://github.com/OpenLiberty/guide-microprofile-openapi/pull/101
### 2. The warning messages is displayed on the test results when a service is `DOWN`.
- [x] guide-microprofile-health addressed in https://github.com/OpenLiberty/guide-microprofile-health/pull/128
### 3. Some intermediate error messages while building the code in the `start`.
- [x] guide-microprofile-config addressed in https://github.com/OpenLiberty/guide-microprofile-config/pull/154
### 4. Creating blank server.xml using `touch` command:
- [ ] guide-session 
 Status: Unable to recreate issue when following the guide. I suspect that it was caused when running `mvn liberty:dev` before creating the `server.xml` file. However, when following the guide, we are expected to create the file before running `mvn liberty:dev`

**Comment by gkwan-ibm** [comment]
For 3.,
- microprofile-openapi
```
[ERROR   ] CWWKO1659E: Failed to parse the OpenAPI document for application: guide-microprofile-openapi.
```
- microprofile-config
```
[ERROR   ] CWMCG5003E: The [BackedAnnotatedField] @Inject @ConfigProperty private io.openliberty.guides.system.SystemConfig.email InjectionPoint dependency was not resolved. Error: java.util.NoSuchElementException: CWMCG0015E: The property io_openliberty_guides_email was not found in the configuration.
```
- bean-validation
```
[ERROR   ] CWWKO1650E: Validation of the OpenAPI document produced the following error(s):
```
- jpa-intro

```
/Users/gkwan/tasks/CNAI/guides/master/guide-jpa-intro/start/backendServices/src/main/java/io/openliberty/guides/event/resources/EventResource.java:43: error: cannot find symbol
    private EventDao eventDAO;
            ^
  symbol:   class EventDao
  location: class EventResource
3 errors
```

**Comment by gkwan-ibm** [comment]
close
- issues were addressed
