### ISSUE TITLE
Best Practices on creating docker images for Open Liberty

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#370]
@Emily-Jiang commented on [Wed Nov 13 2019](https://github.com/OpenLiberty/open-liberty/issues/9754)

We need a guide to demonstrate how to create a small docker image and demonstrate the best practices mentioned by Arthur and Leo such as:
1. layers
2. Users and Labels
3. Container immutability
4. Multi-stage
5. Start from the kernel image and run config.sh, etc.

**Comment by yeekangc** [comment]
Need to see how we best present "best practices" (as a guide or otherwise).  Tagging @lauracowen if she has thoughts.

@arthurdm @leochr, as you know, we do have a guide on containerizing already -- https://openliberty.io/guides/containerize.html.  We do attempt to show best practices there.  If there are appropriate improvements that we should make in that guide, we can make directly there.

Otherwise, if another dedicated asset is needed, we can discuss and see what is best.  Any and all input and ideas welcome.

FYI, @gkwan-ibm.

**Comment by lauracowen** [comment]
In general, the guides show best practice anyway, don't they? So wouldn't it just be a case of making sure our guides are up-to-date then designing new guides to show them where there's a gap? (which I think is what you've said above anyway :) )

**Comment by yeekangc** [comment]
+1 to update existing guide(s) to capture the relevant best practices as the first option.

Per @realModusOperandi, best practices are noted here: https://github.com/OpenLiberty/ci.docker 

And, @aguibert noted the below:
1 - make libs/config/app as separate layers (applies for any container, not just liberty)
2 - at the end of your Dockerfile do RUN configure.sh to get a pre-warmed container which will improve start time

There is also the Docker section of the OpenLiberty cheat sheet:
https://aguibert.github.io/openliberty-cheat-sheet/#_docker

@arthurdm @leochr, do we have best practices elsewhere or a consolidated list somewhere?  Who on the team can we work with further on this?

**Comment by yeekangc** [comment]
@gkwan-ibm, can someone review what we have (based on information provided above), work with Arthur/Leo and team to see what is needed, and then figure out how to best reflect them in the guide(s)?

**Comment by gkwan-ibm** [comment]
Guides to be updated:
- [ ] guide-getting-started
- [ ] guide-spring-boot
- [ ] guide-sessions
- [ ] guide-containerize
- [ ] guide-docker
- [ ] guide-okd
- [ ] guide-kubernetes-intro
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-kubernetes-microprofile-config
- [ ] guide-istio-intro
- [ ] guide-microprofile-istio-retry-fallback
- [ ] guide-microprofile-rest-client-async
- [ ] guide-cloud-openshift
- [ ] guide-cloud-aws
- [ ] guide-cloud-ibm
- [ ] guide-cloud-azure

**Comment by leochr** [comment]
@yeekangc I am not aware of any other materials. I can assist your team with any questions they have on the best practices mentioned above.

**Comment by yeekangc** [comment]
Besides updating the guides to use and show best practices, we should have the relevant guides updated to talk about the best practices and why.

Thank you, @gkwan-ibm @leochr.

**Comment by gkwan-ibm** [comment]
completed except the following and they will be addressed by individual issues:
- guide-docker
  - https://github.com/OpenLiberty/guide-docker/issues/74
- guide-microprofile-rest-client-async
  - https://github.com/OpenLiberty/guide-microprofile-rest-client-async/issues/53
