### ISSUE TITLE
Test the guide with 190012 candidate build

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#374]
- [x] Automated tests with jdk8 and jdk11 for all published guides (Mai)

Manual test the guides against GM with Java11OpenJ9:
- [x] Getting Start (Ankit)
- [x] Kube Intro  (Nimrah)
- [x] Gradle (Danny) Win
- [x] Maven Intro  in `qa` branch on qa site (Ankit) 
- [x] JWT (Danny) Win
- [x] Docker-intro (Jonathan) 
- Make sure to run the `docker pull open-liberty` command before running the `docker build` command to make sure the latest docker image is being pulled in and used in the test.

- [x] guide-rest-client-java  + dev mode (Eveline)
- [x] guide-microprofile-config + dev mode (Nimrah)
- [x] guide-microprofile-health + dev mode (Jonathan) 

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform
- for any guide using docker, make sure to use the GM candidate docker image

**Comment by evelinec** [comment]
Tested the `rest-client-java` on Mac with `dev-mode` branch. 

`[INFO] Launching defaultServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)`

**Comment by NimG98** [comment]
### **guide-microprofile-config (Dev Mode):**

- followed guide and tested end-to-end with java11 openj9
- Tested on Mac
- Tested with GM build `openliberty-19.0.0.12-cl191220191120-0300`

From dev mode output:
```
INFO] Launching defaultServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
```

**Comment by DannyS03** [comment]
http://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2019-11-20_0300/

**Comment by DannyS03** [comment]
## JWT
- tested end-to-end on Windows
```
Launching backendServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)
```

**Comment by jonathanxue** [comment]
## Docker Intro

* Tested on Mac
* end-to-end with java11 openj9
* GM build openliberty-19.0.0.12-cl191220191120-0300

From `console.log`
```
Launching defaultServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_CA)
```

From `docker logs <container>`
```
Launching defaultServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on Eclipse OpenJ9 VM, version 1.8.0_232-b09 (en_US)

```

**Comment by jonathanxue** [comment]
## guide-microprofile-health - devmode

- Tested on `qa` and `dev-mode` branches
- Tested on Mac
- end-to-end with java11 openk9


```[INFO] Launching defaultServer (Open Liberty 19.0.0.11/wlp-1.0.34.cl191120191031-0300) on Eclipse OpenJ9 VM, version 11.0.4+11 (en_CA)```

**Comment by NimG98** [comment]
### **Kube Intro:**

- followed guide and tested end-to-end
- Tested on Mac
- Tested with GM build `openliberty-19.0.0.12-cl191220191120-0300`

From `docker build` command output:
```
Step 1/2 : FROM guidesbot/olguides:cl191220191120-0300
```

From `kubectl logs <pod-name>`:
```
Launching defaultServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on Eclipse OpenJ9 VM, version 1.8.0_232-b09 (en_US)
```

**Comment by ankitagrawa** [comment]
Tested the getting-started guide.

Launching defaultServer (Open Liberty 19.0.0.12/wlp-1.0.35.cl191220191120-0300) on Eclipse OpenJ9 VM, version 13.0.1+9 (en_US)

**Comment by ankitagrawa** [comment]
Maven Intro guide

`product = Open Liberty 19.0.0.12 (wlp-1.0.35.cl191220191120-0300)`
