### ISSUE TITLE
Update groupId for LMP on pom.xml files

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guides-common#379]
I noticed that a lot of guides still look in the https://repo.maven.apache.org/maven2/net/wasdev/wlp/maven/plugins/liberty-maven-plugin/ repository for the LMP, however it seems that latest versions get pushed to this repo: https://repo.maven.apache.org/maven2/io/openliberty/tools/liberty-maven-plugin/. This poses an issue since the automated bot that looks for newer dependancy versions look inside the same repository as outlined in the pom.xml (at least I assume). We might have to update the guides to look at the newer repository for the LMP.

**Comment by evelinec** [comment]
This is done as part of the dev mode conversion.

**Comment by MaiHameed** [comment]
Yep, I looked and saw that there is a new package method, since we're addressing this with dev mode I can close the issue. Thanks :)
