### ISSUE TITLE
Create a guide on MicroProfile Fault Tolerance

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#38]
Intro guide on MP Fault Tolerance focussing on Retry and Fallback.

**Comment by evelinec** [comment]
Adding "ID require" tag for team to plan. 
Repo link will be added when guide is ready for ID review.

**Comment by sishida** [comment]
Please add the link to the issue when it's ready for ID review. I think this is the correct link, so this is the one I will edit today: https://github.com/OpenLiberty/draft-guide-microprofile-faulttolerance-intro/blob/master/README.adoc Thanks!

**Comment by sishida** [comment]
I created a pull request here: https://github.com/OpenLiberty/draft-guide-microprofile-faulttolerance-intro/pull/17

**Comment by evelinec** [comment]
@sishida Thanks for your initial review. This guide is ready for full review. Thanks. 

Repo link: https://github.com/OpenLiberty/draft-guide-microprofile-faulttolerance-intro

**Comment by evelinec** [comment]
@sishida Actually, if you could hold on to reviewing this guide, there're some more feedback that need to be incorporated. Sorry for the confusion. If you already started, no a problem. Thanks.

**Comment by sishida** [comment]
@evelinec Thanks for letting me know! I'll hold off on editing the guide for now. :)

**Comment by sishida** [comment]
@evelinec Could you please post a new link when this guide is ready for review? Thank you! :)

**Comment by evelinec** [comment]
@sishida The FT guide is good with some ID review now. Here's the repo link: https://github.com/OpenLiberty/draft-guide-microprofile-faulttolerance-intro
Thanks.

**Comment by yeekangc** [comment]
https://openliberty.io/guides/microprofile-fallback.html
