### ISSUE TITLE
Create a guide how to use Kafka 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#380]
Explain how to use Kafka APIs KafkaProducer and  KafkaConsumer to generate and consume messages in a microservices application

**Comment by evelinec** [comment]
- creating repo
- draft and content is ready to push to repo
- dev content review can start

**Comment by jonathanxue** [comment]
https://github.com/OpenLiberty/draft-guide-kafka-intro/tree/dev

Repo created here

**Comment by gkwan-ibm** [comment]
- need dev content review

**Comment by gkwan-ibm** [comment]
- dev content review in progress

**Comment by yeekangc** [comment]
This is a duplicate of an existing issue?

**Comment by yeekangc** [comment]
This is now superseded by the series of guides on MP Reactive Messaging.
