### ISSUE TITLE
Test the guide with 20001 candidate build

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#381]
- [x] Automated tests with jdk8 and jdk11 for all published guides (Nimrah)

Manual test the guides against GM with Java11OpenJ9:
- [x] Getting Start (Ankit)
- [x] Kube Intro  (Nimrah) dev-mode branch
- [x] Gradle (Danny) Mac and Win on working branch
- [x] Maven Intro (Ankit) 
- [x] JWT (Danny) Win
- [x] Docker-intro (Mai) 
- Make sure to run the `docker pull open-liberty` command before running the `docker build` command to make sure the latest docker image is being pulled in and used in the test.

Additional guides:
- N.A.

Current tests instructions:
- follow the guide to test it end-to-end
- test on any platform
- for any guide using docker, make sure to use the GM candidate docker image

**Comment by MaiHameed** [comment]
`guide-docker` tested on Mac, JDK 8 & 11, GM build. `product = Open Liberty 19.0.0.12 (wlp-1.0.35.cl191220191120-0300)`

Everything works as expected.

**Comment by ankitagrawa** [comment]
**Getting Started guide**

[INFO] Launching defaultServer (Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on Eclipse OpenJ9 VM, version 13.0.1+9 (en_CA)

Waiting for the latest docker image.

**Comment by ankitagrawa** [comment]
**Maven Intro Guide**

Tested on Mac

[INFO] Launching guideServer (Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on Eclipse OpenJ9 VM, version 13.0.1+9 (en_CA)

**Comment by NimG98** [comment]
### **Kube Intro:**

- followed guide and tested end-to-end
- Tested on Mac
- Tested with GM build `openliberty-20.0.0.1-cl200120200108-0300`

From `docker build` command output:
```
Step 1/4 : FROM guidesbot/olguides:cl200120200108-0300
```

From `kubectl logs <pod-name>`:
```
Launching defaultServer (Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on Eclipse OpenJ9 VM, version 1.8.0_232-b09 (en_US)
```

**Comment by DannyS03** [comment]
## JWT
- tested end-to-end on Windows
```
Launching backendServer (Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)
```

## Gradle
- tested end-to-end using gradle wrapper `gradlew.bat` on Windows
```
Launching backendServer (Open Liberty 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on OpenJDK 64-Bit Server VM, version 11.0.4+11 (en_CA)
```
