### ISSUE TITLE
SEO improvements

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/guides-common#382]

**Comment by NimG98** [comment]
The following are notes for each guide needing seo improvements:

**Comment by NimG98** [comment]
### MP + Getting Started guides:
- [ ] microprofile-fallback
- [ ] microprofile-config
- [x] microprofile-health
- [ ] microprofile-rest-client-async
    - OL blog page search results good compared to OL guide
        - blog seo:
            > Asynchronous REST with JAX-RS and MicroProfile

        - blog seo description: 
            > JAX-RS and MicroProfile Rest Client make writing and consuming RESTful services both easy and powerful, especially when using their asynchronous capabilities. Take a look at how to use asynchronous JAX-RS resource methods on the client and server.
    - add microprofile in title
    - remove 2nd related guide doesnt exist
- [ ] microprofile-rest-client
- [ ] getting-started
    - add maven, docker, java, or microservices
    - possible title: 
        > Getting started with Maven and Docker to deploy an OpenLiberty application”
    - possible description 
        > A tutorial on how to run Java microservices on Open Liberty
- [ ] docker
    - add microservice/ REST service in title
    - remove period in title
- [ ] rest-intro
    - add jax rs, jsonb to title
- [ ] security-intro
    - put jakarta ee security api in title
    - mention user registry?
- [ ] maven-intro
- [ ] cdi-intro


### Containers/Kube/Istio guides:
- [ ] containerize
    - add Docker in title
- [ ] kubernetes-intro
    - add Getting Started
    - put more then just Kubernetes tutorial
- [ ] kubernetes-microprofile-health
    - add MicroProfile in seo title
- [ ] kubernetes-microprofile-config
    - needs to be more like health seo
    - maybe 
        > Configuring microservices using ConfigMaps and Secrets in Kubernetes
- [ ] istio-intro
    - add mentions of Kubernetes
- [x] microprofile-istio-retry-fallback
- [ ] sessions
    - add mentions of Kubernetes
- [ ] spring-boot


### Cloud guides:
- [ ] cloud-aws
    - no mention of aws in title
- [ ] ibm-cloud
- [x] cloud-azure
- [x] cloud-openshift

### Other guides:
- [ ] rest-client-java
    - add Java in title
- [ ] rest-client-angular
    - add microservices
- [ ] rest-client-angularjs
    - extra space in seo description
- [ ] bean-validation
    - add java/ jakarta ee
    - talk about javabeans
- [ ] cors
    - remove “write tests to validate that the CORS configurations work.”
    - talk about simple and preflight requests
- [ ] jpa-intro
    - add JPA in seo title
- [x] microshed-testing
- [x] arquillian-managed
- [x] microprofile-openapi

**Comment by gkwan-ibm** [comment]
- finished the first batch for MP
- working of the second batch

**Comment by gkwan-ibm** [comment]
- waiting PR review for the second batch

**Comment by gkwan-ibm** [comment]
- the second batch is ready to merge and verify
- working on the third batch

**Comment by gkwan-ibm** [comment]
- the second batch is ready to merge master
- working on the third batch

**Comment by gkwan-ibm** [comment]
- the second batch is ready to review
- working on the third batch

**Comment by NimG98** [comment]
Noticed that `guide-sessions` had pretty good rankings on google search.
And `guide-sessions` is the one of the only guides with search keyword metadata:
 ```
:page-search-keywords: ['sessions', 'session persistence', 'sessionCache', 'Hazelcast', 'JCache']
```

Considering adding `:page-search-keywords:` to other guides' metadata

**Comment by gkwan-ibm** [comment]
- the third batch PRs are ready to review

**Comment by gkwan-ibm** [comment]
- just need to verify the last guide - rest client angular
