### ISSUE TITLE
Development work flows

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#384]
Make sure the Liberty Maven Plugin (LMP) can achieve the following development work flows:
- [ ] Develop a microservice
  - [ ] create a new maven project (min set of files and idea pom, etc)
  - [ ] start and develop the microservice (mvn liberty:dev)
    - [ ] change code - with compilation error
    - [ ] change configuration 
    - [ ] remote debug
    - [ ] run unit and integration tests
    - [ ] stop the development with error and resume on next day 
  - [ ] add 3rd party library
- [ ] Develop 2+ microservices simultaneously
  - [ ] remote debug
  - [ ] run integration tests across microservices
- [ ] Build microservice by automation (Travis and/or Jenkin)
- [ ] Repackage microservice (e.g. update for new OL release, new dependencies, etc)

Including:
- open issues to enhance the LMP if necessary
- give suggestions to the guides
- document the detail of the above findings

**Comment by meswan** [comment]
Repo: https://github.com/meswan/dev-mode-pipeline-integration

**Comment by meswan** [comment]
Added a `Findings` section to the box note: https://ibm.ent.box.com/notes/566302666687

**Comment by yeekangc** [comment]
This maps to https://github.com/OpenLiberty/open-liberty/issues/9890.

**Comment by meswan** [comment]
- [ ] Create a simple RESTful microservice
   - [ ] Cover HTTP methods: GET, PUT, POST & DELETE.
   - [ ] Add regular tests with plain java.
      - [ ] @DisplayName.
      - [ ] @Order.
      - [ ] Test all 4 HTTP methods.
   - [ ] Add MST using @RESTclient annotation
      - [ ] @DisplayName.
      - [ ] @Order.
      - [ ] Test all 4 HTTP methods.
   - [ ] Add liveness & readiness checks.
   - [ ] Use a microprofile configuration file to set maintenance to true or false.
   - [ ] Also defined in server.xml for dynamic changes.
   - [ ] Use Open API
      - [ ] Add Annotations

**Comment by meswan** [comment]
Codewind template update PR: https://github.com/codewind-resources/openLibertyTemplate/pull/6

**Comment by meswan** [comment]
Codewind template changes merged to master.

**Comment by meswan** [comment]
Bluemix template update PR: https://github.com/IBM/java-liberty-app/pull/44

**Comment by gkwan-ibm** [comment]
https://github.com/PurpleLiberty

Update the following project with junit5, LMP 3.2.4, mpHealth-2.2, microprofile 3.3, latest version of features and plugins
- [ ] example-health-check
- [ ] example-configmap
- [ ] example-rest-http-secured 
- [ ] example-rest-http-crud
- [ ] example-circuit-breaker 
- [ ] example-rest-http
- [ ] example-cache

**Comment by meswan** [comment]
RH folks are looking into the issue that prevents the OL samples from Purple Liberty to be deployed on OS v4. (Currently broken in production)

Issue: https://groups.google.com/u/3/g/fabric8-launcher/c/w5A7tewzFCE

Once it is fixed, we can test our changes.

**Comment by meswan** [comment]
The templates have been fixed and the updates merged for Purple Liberty.

**Comment by gkwan-ibm** [comment]
close
- [feature]( https://github.com/OpenLiberty/open-liberty/issues/9890) was closed
- updated different tools (see https://github.com/OpenLiberty/open-liberty/issues/9890#issuecomment-748180946)
