### ISSUE TITLE
Create a new guide using CRC to run OpenShift 4.x locally

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/guides-common#387]
We have just released a guide for OKD/Minishift - https://openliberty.io/guides/okd.html . 

Minishift is limited to OpenShift 3.xx.  For later versions the answer appears to be CodeReady Containers - https://github.com/code-ready/crc/issues/284 .  It would be good to have an equivalent guide for CRC.

**Comment by MaiHameed** [comment]
We have an Open Liberty Operators guide in the works which will use CRC to deploy an OpenShift cluster. Keep an eye out for it soon!

**Comment by yeekangc** [comment]
@MaiHameed, can you elaborate on your thinking there?

**Comment by yeekangc** [comment]
Created #467 to track updating OpenShift guide to indicate CRC as a local option.

**Comment by yeekangc** [comment]
Consider a new guide using CRC for OKD 4.x. Retain the current guide with Minishift updating it to indicate it's for OKD 3.x. Update OpenShift guides (via #467 or as appropriate) to indicate local (dev) option(s) and point to relevant guides if appropriate.

**Comment by griffinhadfield** [comment]
Renamed this issue to accurately reflect the work being done. A new guide using CRC is in development: https://github.com/openliberty/draft-guide-crc-openshift

**Comment by gkwan-ibm** [comment]
ready to sign off

**Comment by yeekangc** [comment]
Consider guide-openshift-codeready-containers for the guide on openliberty.io.  Code repo can be shorter (e.g., guide-openshift-crc).

**Comment by yeekangc** [comment]
Thank you all.  Let us proceed to publish this guide.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/openshift-codeready-containers.html.
