### ISSUE TITLE
Refactor the application in the guides to follow the new project structure

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#39]
See project structure on https://github.com/OpenLiberty/guides-common/wiki/Getting-started for how to structure your project. We’re using a new structure from today. We need to refactor the guides.

**Comment by yeekangc** [comment]
@evelinec, is this done?

**Comment by evelinec** [comment]
@yeekangc We had used the new structure for the recent guides. The previously published guides will still need these changes. But perhaps we can do that all together when there's new layout.

**Comment by yeekangc** [comment]
@evelinec, thank you.  Can you please call out what needs to be done still?  This will help us track and prioritize the work.

**Comment by evelinec** [comment]
@yeekangc Those are: Docker, Gradle, AngularJS, CORS, multi-module, consuming RESTful web service, rest-intro, hypermedia, microprofile-intro, maven. More or less in all of those previously published guides.

**Comment by evelinec** [comment]
I believe this has been covered in multipane conversion of the guides.
