### ISSUE TITLE
Update guides to use MicroProfile 3.3

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guides-common#395]
MicroProfile 3.3 will be released in 20.0.0.4. The Open Liberty guides referred to the older mp versions need to be updated to use the latest.

**Comment by gkwan-ibm** [comment]
completed except following:
- guide-docker will be addressed by https://github.com/OpenLiberty/guide-docker/issues/74
- guide-jwt will be addressed by https://github.com/OpenLiberty/guide-microprofile-jwt/issues/113
- guide-arquillian-managed will be addressed by https://github.com/OpenLiberty/guide-arquillian-managed/issues/71
