### ISSUE TITLE
Create a guide about MP Reactive Messaging with Kafka

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#401]
Create a guide to talk about MP Reactive Messaging among microservices with Kafka

**Comment by gkwan-ibm** [comment]
github repo is created at https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging

**Comment by gkwan-ibm** [comment]
- almost ready for SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- addressing SME review
- externalized some content to the guides-common repo

**Comment by gkwan-ibm** [comment]
- after addressed Andrew's feedback, will need an end-to-end test
- then ask SME to approve the guide

**Comment by gkwan-ibm** [comment]
- SME will do review on today
- peer review pending on SME review
  - Mac (Darren)
  - Linux (Kartik)
  - Win (Danny)

**Comment by gkwan-ibm** [comment]
- addressing SME review

**Comment by gkwan-ibm** [comment]
peer review
- https://draft-guides.mybluemix.net/guides/microprofile-reactive-messaging.html (refreshing)
- dev branch on https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging
- Mac (@MaiHameed )
- Linux (@k-rtik )
- Win (@DannyS03 )

**Comment by gkwan-ibm** [comment]
- addressed peer review feedback
- ready for final content and user review

**Comment by gkwan-ibm** [comment]
- final content and user review in progress
- need to address  some feedback from YK

**Comment by gkwan-ibm** [comment]
- revised the guide with the simple sys and inv app
- next step should be peer review

**Comment by gkwan-ibm** [comment]
- peer review in progress
  - Mac (Mai): completed with feedback
  - Linux (Nimrah): completed with feedback
  - Win (Danny): completed with feedback

**Comment by gkwan-ibm** [comment]
- addressed peer review feedback
- addressing SME review feedback
- next: post the guide in to the channel and ask someone to do user review

**Comment by gkwan-ibm** [comment]
- user review completed
- next final content review

**Comment by gkwan-ibm** [comment]
- addressing final content review from different people

**Comment by gkwan-ibm** [comment]
- addressed the final content review
- ID review in progress
- Final approval will be done on tomorrow and sync up the app and tests with the testing guide
- target to publish on Wed

**Comment by yeekangc** [comment]
@Charlotte-Holt reviewed for ID.  @lauracowen @yeekangc reviewed final content and signed off for publishing.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/microprofile-reactive-messaging.html.
