### ISSUE TITLE
Create a guide for MP Reactive Messaging Acknowledgement

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#402]
Create a guide to talk about/explain MP Reactive Messaging Acknowledgement

**Comment by gkwan-ibm** [comment]
- studying how acknowledgement work

**Comment by gkwan-ibm** [comment]
- ~50% to 60% drafted

**Comment by gkwan-ibm** [comment]
- updating the app according SME feedback

**Comment by gkwan-ibm** [comment]
- dev content review in progress

**Comment by gkwan-ibm** [comment]
- draft repo created and available on draft site

**Comment by gkwan-ibm** [comment]
- revising the guide to use the new reactive system/inventory app

**Comment by gkwan-ibm** [comment]
- enhanced the app, will start to draft the README

**Comment by gkwan-ibm** [comment]
- need to update the guide and app to use PUT endpoint as the reactive rest guide

**Comment by gkwan-ibm** [comment]
- updating the app with the reactive rest app changes

**Comment by gkwan-ibm** [comment]
- wait for SME review

**Comment by gkwan-ibm** [comment]
- drafting the readme

**Comment by gkwan-ibm** [comment]
- peer review 
  - [ ] Mac (Tiago)
  - [ ] Linux (Griffin)
  - [ ] Win (Austin)

http://lgdev1.fyre.ibm.com:4020/guides/microprofile-reactive-messaging-acknowledgement.html
branch `format-changes`

**Comment by gkwan-ibm** [comment]
- there is a test issue for MST

**Comment by gkwan-ibm** [comment]
- addressed peer review feedback and waiting approvals
- MST issue is not resolved yet

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- addressing SME review feedback

**Comment by gkwan-ibm** [comment]
- met Laura and addressed her feedback

**Comment by gkwan-ibm** [comment]
- addressing more Laura's feedback
- waiting SME to review

**Comment by meswan** [comment]
still addressing Laura's feedback

**Comment by gkwan-ibm** [comment]
- addressing more feedback from SME

**Comment by gkwan-ibm** [comment]
- addressed the feedback and wait SME and stakeholder approval

**Comment by gkwan-ibm** [comment]
- next user review

**Comment by gkwan-ibm** [comment]
- ID review completed
- final end-to-end test (Gilbert)

**Comment by yeekangc** [comment]
Thank you, team.  Please proceed to publish this guide.

**Comment by gkwan-ibm** [comment]
The guide was published at https://openliberty.io/guides/microprofile-reactive-messaging-acknowledgment.html
