### ISSUE TITLE
Create a guide for testing MP Reactive Messaging microservice

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#404]
Create a guide to talk about how to test MP Reactive Messaging microservice by using MST and Kakfa test container

**Comment by gkwan-ibm** [comment]
- need to determine the best way to test, either using Kafka api or using `@Outgoing` and `@Incoming`
- need to confirm the app template

**Comment by gkwan-ibm** [comment]
- Dev content review 1 
  - https://github.com/MaiHameed/draft-guide-reactive-mst/issues/3

**Comment by ankitagrawa** [comment]
Addressed the dev content feedback.

**Comment by gkwan-ibm** [comment]
- waiting the final version of the main app

**Comment by gkwan-ibm** [comment]
- Dev content review 2
  - https://github.com/OpenLiberty/draft-guide-reactive-service-testing/issues/1

**Comment by gkwan-ibm** [comment]
- Dev content review 3
  - https://github.com/OpenLiberty/draft-guide-reactive-service-testing/issues/2

**Comment by gkwan-ibm** [comment]
- addressing dev content review

**Comment by ankitagrawa** [comment]
dev content review feedback addressed.

**Comment by gkwan-ibm** [comment]
Peer review
- https://draft-guides.mybluemix.net/guides/reactive-service-testing.html (refreshed)
- dev branch on https://github.com/OpenLiberty/draft-guide-reactive-service-testing
- Mac (Darren)
- Linux
- Win (Danny)

**Comment by gkwan-ibm** [comment]
- addressed peer review feedback
- ready for SME review - target Mar 30

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- dev content review 5
  - https://github.com/OpenLiberty/draft-guide-reactive-service-testing/issues/11

**Comment by gkwan-ibm** [comment]
- revising the app and readme

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
- travis  test failure
- peer review in progress 
  - Mac (Darren) - in progress
  - Linux (Kartik) - in progress
  - Win (Danny)

**Comment by gkwan-ibm** [comment]
- travis test passed
- peer review in progress 
  - Mac (Darren) - verify a fix
  - Linux (Kartik) - completed
  - Win (Danny) - verify a fix
- next SME review

**Comment by gkwan-ibm** [comment]
- peer review completed
- SME in progress

**Comment by gkwan-ibm** [comment]
- addressing SME review
- next user review

**Comment by gkwan-ibm** [comment]
- user review in progress
- addressing some other feedback

**Comment by gkwan-ibm** [comment]
- user review in progress
- cleaning up feedback
- addressing travis.sh issue

**Comment by ankitagrawa** [comment]
- User review completed and addressed. 
- travis.sh issue addressed.
- feedback addressed.

**Comment by gkwan-ibm** [comment]
- the final content review in progress

**Comment by gkwan-ibm** [comment]
- addressing the final content review
- next is ID review

**Comment by gkwan-ibm** [comment]
- addressed the final content review
- ID review in progress

**Comment by gkwan-ibm** [comment]
- addressing ID review feedback

**Comment by yeekangc** [comment]
Let us proceed to publish this guide.  Thank you, team!

**Comment by MaiHameed** [comment]
Published on master + presented at EOI

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/reactive-service-testing.html.
