### ISSUE TITLE
Create a guide to push reactive messages to frontend application

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#405]
Create a guide to talk about how to push reactive messages to frontend application via SSE or Websockets

**Comment by gkwan-ibm** [comment]
- investigating the frontend solution

**Comment by ankitagrawa** [comment]
- Merge Gilbert's code with Jimmy's

**Comment by ankitagrawa** [comment]
Drafting the guide.

**Comment by gkwan-ibm** [comment]
- draft is ready to review
- waiting the final version of the main app

**Comment by gkwan-ibm** [comment]
**Dev content review 1**

- **What you’ll learn**
  - [ ] need to spell out BFF
- **Configuring the server**
  - [ ] need to navigate the readers to the start directory
  - [ ] in the command arrow box, the font is not our usual font
  - [ ] "Replace the OpenLibertyCafe server.xml configuration file." -> "Replace the OpenLibertyCafe server configuration file."
  - [ ] "Configure the server ..." -> "Configure the `OpenLibertyCafe` BBF server ...
  - [ ] no need to have "The rest of the microservices have server.xml already configured."
- **Creating the SSE resource**
  - [ ] "... you will create a new resource ...". I am not sure "resource" is a right word to descibe the `OpenLibertyCafeSSEResource` class. May we say to create REST API for SSE?
  - [ ] in the command arrow box, the font is not our usual font
  - [ ] "Create the OpenLibertyCafeSSEResource.java file" -> "Create the OpenLibertyCafeSSEResource class."
  - [ ] Format the OpenLibertyCafeSSEResource.java so that no lines are wrapped in the right pane
  - [ ] "The `subscribeToOrders` function..." -> "The `subscribeToOrders()` function..."
  - [ ] Can hotspot `GET api/sse`?
  - [ ] Instead of hotspot `method parameters`, hotspot `SseEventSink` and `Sse`
  - [ ] Can add more hotspots to `SseBroadcaster`, `Sse#newEvent`, ... etc?
  - [ ] Update "Then, the function checks if the sse and broadcaster instance ..."
    - spell out which function
    - backtick the words `sse` and `broadcaster`
    - can add hotspot to `sse` and `broadcaster`
  - [ ] Can make "Lastly, the sink is registered to the broadcaster." clear? e.g add hotspots
  - Then, I lost the flow of the content. Would you reorganize this section, so that the readers, whoever has no knowledge about SSE, can follow the logic/flow?
- **Creating the JavaScript Resource**
  - [ ] in the command arrow box, the font is not our usual font
  - I will review again because I need to understand the above section first
- **Closing the connection**
  - [ ] any hotspot?
  - I will review again because I need to understand the above 2 sections first
- **Building the application**
  - [ ] the list of Order, Kitchen, Bar, ServingWindow, Status, and OpenLibertyCafe should be in alphabetical order
- It is ok to create the draft repo in github.

**Comment by gkwan-ibm** [comment]
- addressed dev content review 1 feedback and ready to be reviewed again

**Comment by gkwan-ibm** [comment]
- dev content review 2
  - https://github.com/OpenLiberty/draft-guide-reactive-messaging-sse/issues/1

**Comment by gkwan-ibm** [comment]
- addressing the dev content review

**Comment by gkwan-ibm** [comment]
- addressed the dev content review

**Comment by gkwan-ibm** [comment]
- dev content review 3
  - https://github.com/OpenLiberty/draft-guide-reactive-messaging-sse/issues/2

**Comment by gkwan-ibm** [comment]
- addressing the dev content review 3

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
- dev content review 5
  - https://github.com/OpenLiberty/draft-guide-reactive-messaging-sse/issues/8

**Comment by gkwan-ibm** [comment]
- revising the guide to use the new reactive system/inventory app

**Comment by TiagoF99** [comment]
Application transfer from the Cafe model to the system/inventory model can be found with this PR: https://github.com/OpenLiberty/draft-guide-reactive-messaging-sse/pull/9

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
- prototyping the app

**Comment by gkwan-ibm** [comment]
- prototyped the app by using system and frontend services
- designing the outline of the guide

**Comment by gkwan-ibm** [comment]
- design review meeting was scheduled on next Fri
- drafting the README

**Comment by yeekangc** [comment]
LGTM.  Let us proceed to publish this guide.  Thank you, @griffinhadfield @gkwan-ibm.

This should be associated with "Reactive", "MicroProfile" and "Jakarta EE" and go under the "Reactive" category.

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/reactive-messaging-sse.html.
