### ISSUE TITLE
Add "Try what you’ll build" section

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#410]
For consistence, add "Try what you’ll build" section to the following guides:
- [ ] https://openliberty.io/guides/microprofile-rest-client-async.html#getting-started
- [ ] https://openliberty.io/guides/rest-client-angular.html#getting-started
- [ ] https://openliberty.io/guides/rest-client-angularjs.html#getting-started
- [ ] https://openliberty.io/guides/cors.html#getting-started
- [ ] https://openliberty.io/guides/maven-multimodules.html#getting-started
- ...

**Comment by gkwan-ibm** [comment]
@jj-zhang would you study all guides to find out which guides should add the  "Try what you’ll build" section?

**Comment by jj-zhang** [comment]
Guides that should be added "Try what you'll build":
- [ ] https://openliberty.io/guides/microprofile-rest-client-async.html#getting-started
- [ ] https://openliberty.io/guides/rest-client-angular.html#getting-started
- [ ] https://openliberty.io/guides/rest-client-angularjs.html#getting-started
- [ ] https://openliberty.io/guides/cors.html#getting-started
- [ ] https://openliberty.io/guides/maven-multimodules.html#getting-started
- [ ] https://openliberty.io/guides/getting-started.html#getting-started
