### ISSUE TITLE
Improve the Blue Liberty Board

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#420]
**Objective:** present clone data for each guide repository

**Plan:**
1. blue liberty board: collect github data for each guide repository
   1. reducing the api calls because excess the quote
1. collect data for daily build test automation and PR changes (they cause a git clone)
   1. trying/prototype to call Travis api to collect data
   1. implement 2.i into the blue liberty board python app
   1. normalize the data from 1 by data 2.ii
1. generate monthly report / graph data
   - through blue liberty dashboard in kibana (or other alternative, e.g. excel)
     - total guides clone graph
     - individual guide clone graph

**Comment by gkwan-ibm** [comment]
- completed 1
- working on 2.i

**Comment by NimG98** [comment]
May need to fix:
- PRs looking high (possibly due to PRs from bots)
- clones on a few days look really low (close to 0)

**Comment by gkwan-ibm** [comment]
- 2.i was completed
- working on 2.ii

**Comment by gkwan-ibm** [comment]
- working on 2.ii and 2.iii
