### ISSUE TITLE
Guide for MP GraphQL 1.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/guides-common#423]
The MicroProfile GraphQL 1.0 spec released, and the Open Liberty `mpGraphQL-1.0` feature is currently in beta, but I am hoping that we make it GA in the 20.0.0.6 release.  The epic issue for MP GraphQL 1.0 in OL is https://github.com/OpenLiberty/open-liberty/issues/7956 - if possible, it would be great to have the guide release concurrent with the product code since GraphQL is a new API.

I wrote a sample (that currently works on the OL daily development builds) that might be useful for the guide: https://github.com/OpenLiberty/sample-mp-graphql

In chatting with @yeekangc, we thought it might be good to have two guides - one as an intro, and another that covers more advanced features.

**Comment by gkwan-ibm** [comment]
- prototyping the app 
- ask SME to review the app and design the content

**Comment by gkwan-ibm** [comment]
- completed the prototype of the app but it not work in dev mode

**Comment by gkwan-ibm** [comment]
- SME approved the app
- identified an issue for OL

**Comment by gkwan-ibm** [comment]
- drafting the README

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by gkwan-ibm** [comment]
- draft guide repo was created

**Comment by gkwan-ibm** [comment]
- addressing dev content review feedback

**Comment by gkwan-ibm** [comment]
- working on the design

**Comment by gkwan-ibm** [comment]
- design meeting on tomorrow

**Comment by gkwan-ibm** [comment]
- need to redesign the app by using system and inventory
- Latest OL supports GraphQL GUI
- will consider another new guide for GraphQL client

**Comment by gkwan-ibm** [comment]
- the guide was rewritten
- dev content review in progress

**Comment by gkwan-ibm** [comment]
- dev content and peer review completed
- SME review in progress

**Comment by gkwan-ibm** [comment]
ready to sign off

**Comment by AustinSeto** [comment]
Currently have two drafts prepared for the guide after recent reviews and feedback. 

The first draft tries to start the guide application with a simple REST endpoint to retrieve all system properties. Then it adds a GraphQL endpoint to get the same data, but through GraphQL instead. The goal is to try to do a basic comparison between the two methods. Its PR is here: https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/26

The second draft is based off of Gilbert's app, which develops a GraphQL service, and then a client service that will make queries to the GraphQL service. The goal is to try to show a basic example of a GraphQL service and how one can make requests to it from another application or service. Its PR is here: https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/27

I wonder if some kind of combination of the two would be appropriate or if that would be too lengthy for an introductory guide.

**Comment by gkwan-ibm** [comment]
the graphql client guide will be addressed by #718

**Comment by yeekangc** [comment]
Thanks, team.  Let us proceed to publish (the GraphQL service guide).

**Comment by gkwan-ibm** [comment]
close
- the guide was published at https://openliberty.io/guides/microprofile-graphql.html
