### ISSUE TITLE
Create a guide to about trigger reactive message by REST

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#424]
Create a guide to talk about how to trigger reactive message by REST API

**Comment by gkwan-ibm** [comment]
- drafting

**Comment by gkwan-ibm** [comment]
- the first draft is ready for dev content review

**Comment by gkwan-ibm** [comment]
- dev content review feedback
  - https://github.com/ankitagrawa/guide-microprofile-reactive-messaging-rest/issues/1

**Comment by gkwan-ibm** [comment]
- addressing dev content review feedback

**Comment by gkwan-ibm** [comment]
- next peer review
  - Mac (Nimrah)
  - Linux (Meswan)
  - Win (Danny)

**Comment by gkwan-ibm** [comment]
- addressed the peer review feedback 
- next is SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- updated the POST api
- addressing SME feedback
- update the tests to use MST 0.9

**Comment by gkwan-ibm** [comment]
- addressing an issue related to group

**Comment by gkwan-ibm** [comment]
- prototyping another approach for the app - reservation

**Comment by gkwan-ibm** [comment]
- revised the app to use PUT
- will be reviewed by GK and then a test

**Comment by gkwan-ibm** [comment]
- addressing the feedback for the revised app

**Comment by gkwan-ibm** [comment]
- ready for dev content review
- next SME review

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- will address SME review feedback

**Comment by gkwan-ibm** [comment]
- addressing SME review

**Comment by gkwan-ibm** [comment]
- proceed to do user view

**Comment by gkwan-ibm** [comment]
- addressing user review

**Comment by gkwan-ibm** [comment]
- SME and user review completed
- requesting final content review

**Comment by gkwan-ibm** [comment]
- addressing the  final content review feedback

**Comment by gkwan-ibm** [comment]
- ID review in progress

**Comment by AustinSeto** [comment]
End to end test completed on dev branch, all looks good

**Comment by yeekangc** [comment]
Consider a repo name and slug like "microprofile-reactive-messaging-rest-integration".

**Comment by yeekangc** [comment]
Signed off.  Great work, team, and please proceed to publish.

**Comment by gkwan-ibm** [comment]
https://openliberty.io/guides/microprofile-reactive-messaging-rest-integration.html
