### ISSUE TITLE
Update all pom.xml as the template

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#436]
1. Remove the  following properties and specify the version at the plugin directly:
```
        <!-- Plugin versions -->
        <version.liberty-maven-plugin>3.2</version.liberty-maven-plugin>
        <version.maven-failsafe-plugin>2.22.2</version.maven-failsafe-plugin>
        <version.maven-war-plugin>3.2.3</version.maven-war-plugin>
        <version.maven-surefire-plugin>2.22.2</version.maven-surefire-plugin>
```

2. remove `<failOnMissingWebXml>false</failOnMissingWebXml>` 

3. Update dependencies to include following as the best practice:
```
    <!-- Provided dependencies -->
    <dependency>
      <groupId>jakarta.platform</groupId>
      <artifactId>jakarta.jakartaee-api</artifactId>
      <version>8.0.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.microprofile</groupId>
      <artifactId>microprofile</artifactId>
      <version>3.3</version>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
```

3. If the `pom.xml` includes the following similar dependency, remove it, since it will be replaced with the aforementioned `jakarta` dependency:
```
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-web-api</artifactId>
            <version>8.0.0</version>
            <scope>provided</scope>
        </dependency>
```

4. Once you made a PR to `qa`, make a PR to update the automation script [here](https://github.ibm.com/was-liberty/olguides-automation/blob/master/scripts/jenkins-automation/test-all-dhe-dev-builds/testADHEDailyBuildForAllRepos.sh) to reflect the new pom changes

5. Create a card on the Wekan board with the two PRs

**Comment by gkwan-ibm** [comment]
- [ ] guide-getting-started
- [ ] guide-gradle-intro
- [ ] guide-maven-intro
- [ ] guide-microshed-testing
- [ ] guide-spring-boot
- [ ] guide-microprofile-jwt
- [ ] guide-bean-validation
- [ ] guide-maven-multimodules
- [ ] guide-rest-client-angular
- [ ] guide-rest-client-angularjs
- [ ] guide-security-intro
- [ ] guide-jpa-intro
- [ ] guide-arquillian-managed
- [ ] guide-sessions
- [ ] guide-docker
- [ ] guide-rest-intro
- [ ] guide-cdi-intro
- [ ] guide-microprofile-rest-client
- [ ] guide-microprofile-fallback
- [ ] guide-microprofile-opentracing
  - inventory
  - system
- [ ] guide-microprofile-openapi
- [ ] guide-microprofile-health
- [ ] guide-microprofile-metrics
- [ ] guide-microprofile-config
- [ ] guide-rest-client-java
- [ ] guide-cors
- [ ] guide-rest-hateoas
- [ ] guide-kubernetes-intro
  - inventory
  - system
- [ ] guide-kubernetes-microprofile-config
  - inventory
  - system
- [ ] guide-kubernetes-microprofile-health
  - inventory
  - system
- [ ] guide-istio-intro
- [ ] guide-cloud-ibm
  - inventory
  - system
- [ ] guide-cloud-aws
  - inventory
  - system
- [ ] guide-containerize
  - inventory
  - system
- [ ] guide-cloud-azure
  - inventory
  - system
- [ ] guide-microprofile-istio-retry-fallback
  - inventory
  - system
- [ ] guide-microprofile-rest-client-async
  - inventory
  - system
  - job
  - gateway
- [ ] guide-cloud-openshift
  - inventory
  - system
- [ ] guide-okd
  - inventory
  - system
- [ ] guide-cloud-google
  - inventory
  - system
- [ ] guide-microprofile-reactive-messaging
  - inventory
  - system

**Comment by MaiHameed** [comment]
Once the changes are live, we'll need to update the automation scripts to reflect the changes to the pom.

**Comment by TiagoF99** [comment]
For (2) in this issue, refer to https://github.com/OpenLiberty/guides-common/issues/446 for repositories that were pushed to master but overlooked it
