### ISSUE TITLE
Update guides which using docker to pull the latest OL image

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#439]
Make the following guides to 
- pull latest OL docker image
  - `include::{common-includes}/ol-docker-pull.adoc[]`or
  - `include::{common-includes}/ol-kernel-docker-pull.adoc[]`
- use the `openliberty/open-liberty:kernel-java8-openj9-ubi` in Dockerfile
  - use the best practice Dockerfile like: https://github.com/OpenLiberty/guide-getting-started/blob/master/finish/Dockerfile
   - Make sure it works and update readme if necessary

See, https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Dockerfile-Structure-and-Format

Guides use docker:
- [x] guide-getting-started (Nimrah)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-getting-started/pull/173
- [x] guide-docker (Austin)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-docker/pull/75
  - https://github.com/OpenLiberty/guide-docker/pull/76
- [x] guide-kubernetes-intro (Nimrah)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-kubernetes-intro/pull/141
- [x] guide-kubernetes-microprofile-config (Nimrah)
  - may need to update Dockerfile
  -  https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/pull/98
- [x] guide-kubernetes-microprofile-health (Darren)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-kubernetes-microprofile-health/pull/89/
- [x] guide-istio-intro (Danny)
  - ~may need to update Dockerfile~
  - https://github.com/OpenLiberty/guide-istio-intro/pull/96
- [x] guide-containerize (Danny)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-containerize/pull/37
- [x] guide-sessions (Darren)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-sessions/pull/79
- [x] guide-microprofile-rest-client-async (Darren)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-microprofile-rest-client-async/pull/55
- guide-microshed-testing
  - assumed no need to do pull
- [x] guide-spring-boot (Danny)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-spring-boot/pull/52
- [x] guide-okd (Austin)
  - may need to update Dockerfile
  - https://github.com/OpenLiberty/guide-okd/pull/36
- [x] guide-microprofile-istio-retry-fallback (Nimrah)
  - https://github.com/OpenLiberty/guide-microprofile-istio-retry-fallback/pull/43
- [x] guide-cloud-openshift (Nimrah/Danny)
  - https://github.com/OpenLiberty/guide-cloud-openshift/pull/56
- [x] guide-cloud-ibm (Danny)
  - https://github.com/OpenLiberty/guide-cloud-ibm/pull/85
- [x] guide-cloud-aws (Danny)
  - https://github.com/OpenLiberty/guide-cloud-aws/pull/85
- [x] guide-cloud-azure (Nimrah)
    - https://github.com/OpenLiberty/guide-cloud-azure/pull/29
- [x] guide-cloud-google (Nimrah)
    - doesn't use Docker, uses Google Cloud Build. So no need for pull OL instruction
- [x] guide-microprofile-reactive-messaging. (Nimrah)
     - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging/pull/88
- [x] guide-reactive-service-testing (Mai)

**Comment by DannyS03** [comment]
- PR's to master are pending successful build automation.

**Comment by DannyS03** [comment]
Something to be aware of is that the command could be formatted better:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/25497083/84426396-2ede2580-abf1-11ea-9225-0547e7ca7a97.png">

**Comment by DannyS03** [comment]
In general, other docker commands too: 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/25497083/84426630-8b414500-abf1-11ea-805f-d01021213a3a.png">

**Comment by DannyS03** [comment]
Update complete and remaining PR's merged to master.
