### ISSUE TITLE
Update MST related guides to use 0.9

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/guides-common#444]
- MST updated to 0.9 which includes an annotation change from `@KafkaProducerConfig` to `@KafkaProducerClient` and `@KafkaConsumerConfig` to `@KafkaConsumerClient`
 - Remove the `slf4j-log4j12` dependency
   - Remove `log4j.properties` file
   - Note that MST uses the `TestContainers` dependency, which relies on `log4j` for their logs. Since we've removed the `log4j` dependency, we get warning messages from `TestContainers` complaining that it can't find the `log4j` dependency. MST has a fix for this by printing to sysout if it can't find `log4j` but we will not be able to remove the warning messages unless `TestContainers` themselves fixes this.

Affected guides:
- [x] guide-microshed-testing (Austin) - in progress
    - https://github.com/OpenLiberty/guide-microshed-testing/pull/47
- [x] guide-reactive-service-testing (Tiago) - in progress
    - https://github.com/OpenLiberty/guide-reactive-service-testing/pull/62
- [x] guide-microprofile-reactive-messaging (Griffin) - in progress
   - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging/pull/89
- [x] draft-guide-microprofile-reactive-messaging-rest (Mai)
    - https://github.com/OpenLiberty/draft-guide-microprofile-reactive-messaging-rest/commit/30caca6b196d4f23ce066cab30cabe40d693273e
- [x] draft-guide-microprofile-reactive-messaging-acknowledgement (Mai)
- [x] draft-guide-reactive-messaging-sse (Griffin)
- [x] draft-guide-operator-openshift (Mai)

This is not an exhaustive list, there may be more guides, feel free to add to the list. See https://github.com/OpenLiberty/draft-guide-operator-openshift/commit/f5e7a4195c54c2a6a724914cb4c2633c68b4e0ee#diff-6f14a84e53dd7d0ddde3b62bd82112c4R69 and https://github.com/OpenLiberty/draft-guide-operator-openshift/commit/f24cb58915ad1775f7d7a13ca746ba178dc353d0 for an example of the update

**Comment by gkwan-ibm** [comment]
close
- all guides were updated
