### ISSUE TITLE
remove '<failOnMissingWebXml>false</failOnMissingWebXml>'

### ISSUE THREAD

**Issue by TiagoF99** [OpenLiberty/guides-common#446]
- [x] guide-getting-started
    - https://github.com/OpenLiberty/guide-getting-started/pull/176
- [x] guide-maven-intro
    - https://github.com/OpenLiberty/guide-maven-intro/pull/93
- [x] guide-rest-intro
    - https://github.com/OpenLiberty/guide-rest-intro/pull/130

**Comment by NimG98** [comment]
All PRs have been merged to master.

Closing.
