### ISSUE TITLE
Pre-reqs placement on guides - user feedback

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#449]
@yeekangc and I spoke with someone who had been using the guides (Getting started and then REST intro) to learn the basics of Open Liberty (as a newbie). She was familiar with Maven but hadn't realised she didn't have Maven on her laptop. So she had to go off and install it. However, she commented that it would've been useful to have the prereqs listed at the start of the guide.

When we pointed to them at the top of the right-hand column:

![image](https://user-images.githubusercontent.com/3322532/82071393-f0c31400-96cd-11ea-8add-157a630ce5d4.png)

she said she'd expected to see them inline in the text/instructions panel. Anything over on the right she assumed was part of what she did in the terminal etc.

So the question is: Should the pre-reqs be listed as a Pre-requisite software section in the instructions panel instead? Either at the top (after the intro first line) or after the What You'll Learn section.

(I don't have a strong feeling either way. I see the problem but I don't know how big it is.)

cc @mdenby

**Comment by yeekangc** [comment]
@mbroz2 @mdenby

**Comment by mbroz2** [comment]
We've received another feedback that a user can miss the Prerequisites section.
Consider calling out the Prerequisites banner in the beginning of the 'Getting started' section.

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guides-common/issues/46#issuecomment-644290760
https://github.com/OpenLiberty/guides-common/issues/116

**Comment by mdenby** [comment]
Thinking out loud here...We could move it to the Getting Started section. My worry, as a designer, is what's the right side look like without the prereqs? I guess we could just have the code blurred out still without prereqs there...it just felt like having something there to look at explained why the rest of the code was blurry and not a mistake.

**Comment by mbroz2** [comment]
I think we should keep the section where it is, as it allows it to grow without impacting the length of the guide.  Instead I think we should just do something in the 'Getting started' to just 'point out' the prereqs section.  For example, have a sentence like 
"Before beginning, make sure you have all the necessary **prerequisites**."  
and when the user hovers over "prerequisites" we 'highlight' the prerequisites section by changing the border color

**Comment by mdenby** [comment]
I like that idea!

**Comment by lauracowen** [comment]
Maybe helps with accessibility too? Even if the prereq section is navigable to, it might not be obvious that the reader needs to navigate there. Having something flag it up in the GS section would alert all readers that there's something over to the right.

**Comment by yeekangc** [comment]
I am fine with what @mbroz2 suggested.  Will be good to visually highlight the Prereqs section further if possible.

Speaking of accessibility, if there will be a hover-over for the Prereqs link in the GS section, we should ensure that is fine too.

**Comment by gkwan-ibm** [comment]
We will add a statement to at the beginning of the Getting started section.
"Before beginning, make sure you have all the necessary prerequisites."

Do we need to add more text to tell readers that the prerequisites links are located at the right top?

@mbroz2 When hover the buttons, currently, the button background color is changed. Would you open an issue to UI for highlighting the prerequisites section, because you can describe the exact behavior?

**Comment by mbroz2** [comment]
Yes, I'll open an issue in the openliberty.io repo.  I think the easiest approach might be to just leverage hotspots, and just have a special case for one references "prerequisites" to do the highlight action (this would then also reuse the hotspot highlighting in the text)

**Comment by steven1046** [comment]
Can we add [.prerequisites] or a similar class right before the keyword that will highlight the section so the javascript can listen for the hover over that word to highlight the prereqs section?

**Comment by gkwan-ibm** [comment]
@steven1046  you mean like following?

- adoc will be
```
Before beginning, make sure you have all the necessary  [.prerequisites]prerequisites.
```

- The word "prerequisites" will have a different style. When hover it, the prerequisites section at the right top will be highlighted

**Comment by steven1046** [comment]
Yes, that looks good @gkwan-ibm.

**Comment by mbroz2** [comment]
We need to consider what to do in the single pane guides.

**Comment by steven1046** [comment]
> @steven1046 you mean like following?
> 
> * adoc will be
> 
> ```
> Before beginning, make sure you have all the necessary  [.prerequisites]prerequisites.
> ```
> 
> * The word "prerequisites" will have a different style. When hover it, the prerequisites section at the right top will be highlighted

https://github.com/openliberty/openliberty.io/issues/1701 is blocked until the getting started section has the text added.

**Comment by gkwan-ibm** [comment]
The statement was added by https://github.com/OpenLiberty/guides-common/pull/658
