### ISSUE TITLE
Add a step to check that kubernetes is running on docker desktop

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/guides-common#450]
![image](https://user-images.githubusercontent.com/33457590/82358329-5f58e800-99d4-11ea-9376-4747b00216cc.png)

A developer was running through the istio guide and ran `kubectl get nodes` to check the readiness status of kubernetes but received an error `Error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`. The guide says `This command should return a Ready status for the master node.` but does not explain what to do if it does fail and the error is not very obvious.

It was found out later that it was because kubernetes was not enabled on docker desktop by default. The guide has a section on setting up docker desktop and kubernetes, but it might still be good to add a line to ensure that kubernetes is running in the `starting and preparing your cluster for deployment` section incase the user missed an instruction. Also, it says kubernetes comes pre-installed and _enabled_, which is kind of misleading in the below image.

![image](https://user-images.githubusercontent.com/33457590/82358794-063d8400-99d5-11ea-8ffb-70d7b6333fd2.png)

Perhaps we can add `Ensure that Kubernetes is running on Docker Desktop and the context is set to docker-for-desktop` somewhere in the first image. A good place might be after we tell the user to ensure they have allocated enough RAM to also check that k8 is running, or as a debugging step after telling the user they should receive the `READY` status and they do not.

see: 
https://github.com/OpenLiberty/guides-common/blob/master/kube-prereq.adoc
https://github.com/OpenLiberty/guides-common/blob/master/kube-start.adoc

**Comment by meswan** [comment]
Waiting on Gilbert's review.

**Comment by jj-zhang** [comment]
https://github.com/OpenLiberty/guide-microprofile-openapi/pull/91

**Comment by gkwan-ibm** [comment]
> [OpenLiberty/guide-docker#79](https://github.com/OpenLiberty/guide-docker/pull/79)

Not for docker but for https://github.com/OpenLiberty/guide-istio-intro/pull/99
