### ISSUE TITLE
Expose "reactive" as a visible tag

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#451]
We have more than 1 guide on "reactive" now and more is on the way.  Useful to make this a visible tag so users can easily find the whole set of "reactive" guides.

@gkwan-ibm

**Comment by gkwan-ibm** [comment]
Added to the guides but when I click on the tag, the site returns more than expected. Asked UI team to take a look.

**Comment by gkwan-ibm** [comment]
UI fixed the problem
