### ISSUE TITLE
inconsistent use of shell session and command line

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/guides-common#455]
There is an inconsistent use of shell session and command line. We should choose one and be consistent with it.

**Examples**:
- https://github.com/OpenLiberty/guides-common/blob/master/devmode-start.adoc
devmode-start uses command line

- https://github.com/OpenLiberty/guides-common/blob/master/devmode-quit.adoc
devmode-quit uses shell session

- https://github.com/OpenLiberty/guides-common/blob/master/kube-start.adoc
kube-start uses command line

- https://github.com/OpenLiberty/guides-common/blob/master/twyb-end.adoc
twyb-end uses shell session

_This is not an exhaustive list._

**Comment by gkwan-ibm** [comment]
@jimmy1wu would you give me an example, which guides are not same?

**Comment by jimmy1wu** [comment]
@gkwan-ibm I think most of the inconsistency is in the common adocs.
 e.g., devmode-start.adoc and devmode-quit.adoc are inconsistent so any guide that uses dev mode will have the inconsistency.

Example https://openliberty.io/guides/rest-intro.html:

![image](https://user-images.githubusercontent.com/33457590/82682096-b4873a80-9c1c-11ea-9078-336fb536a0ca.png)
===
![image](https://user-images.githubusercontent.com/33457590/82682005-8f92c780-9c1c-11ea-8376-65d77da7cba4.png)
===
![image](https://user-images.githubusercontent.com/33457590/82681953-7c7ff780-9c1c-11ea-9226-3283bab62a17.png)

Probably have to look in the common adocs and in the individual guides.

**Comment by gkwan-ibm** [comment]
hi @lauracowen, which do you suggest to use in the guides?

**Comment by gkwan-ibm** [comment]
ID recommended to use "command line"

**Comment by yeekangc** [comment]
"Command line session" works.

**Comment by gkwan-ibm** [comment]
- [ ] guides-common
  - devmode-quit.adoc
  - twyb-end.adoc
- [ ] guide-getting-started
- [ ] guide-docker
- [ ] guide-rest-client-java
- [ ] guide-rest-client-angularjs
- [ ] guide-maven-multimodules
- [ ] guide-rest-client-angular
- [ ] guide-containerize
- [ ] guide-microshed-testing
- [ ] guide-spring-boot
- [ ] guide-okd
- [ ] guide-reactive-service-testing
