### ISSUE TITLE
Guide for contract testing

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#456]
Create a guide to cover how to do contract testing using framework such as Pact.

**Comment by yeekangc** [comment]
This issue includes investigation on which framework/technology we should use and show for contract testing.

**Comment by gkwan-ibm** [comment]
- prototyped the artist app from rest-client-java guide
- prototyping another app by using system service
  - any interest properties, e.g. from OL
  - verify keys instead of values
  - consider other endpoint, e.g. reactive guides

**Comment by yeekangc** [comment]
What's the consideration for using the artist app?

**Comment by meswan** [comment]
The issue with the system app is that the return will be different based on machine, OS etc. This introduces a problem for pact to verify the contract.

Motivation to use Artist app:
1. The artist app maps to different endpoints as opposed to just 1 for system.
1. The .json return is consistent and therefore pact can easily enforce a contract.

**Comment by yeekangc** [comment]
I would think we want to come at this from what makes sense and should be demonstrated and then go from there to see what is best including building on top of System or other apps that we have.  Artist is used in a few guides only so we should consider carefully before we proceed.  I am interested in the broader thinking for the guide.

If it's prototyping only, I am fine for us to try with Artist.  I am uncertain if it's the best to showcase what we should here.

**Comment by gkwan-ibm** [comment]
- prototyped the application by using system service
- designing the scenario and flow

**Comment by gkwan-ibm** [comment]
- defined the scenario and flow
- drafting the guide outlines

**Comment by gkwan-ibm** [comment]
- the app can be reviewed
- working on the design

**Comment by yeekangc** [comment]
Thanks, team.  Let us proceed to publish this guide!

**Comment by yeekangc** [comment]
Published at https://openliberty.io/guides/contract-testing.html.
