### ISSUE TITLE
A guide to demonstrate how to use Open Liberty operator

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guides-common#464]
We need a guide to educate our customers how to use Open Liberty Operator for their cloud native application.

**Comment by yeekangc** [comment]
We are covering the use of Open Liberty Operator in OpenShift via #411, which is in progress.  Are you looking for more?

Or, you are looking for what developers should consider in their applications when they will be working with the operator?

**Comment by Emily-Jiang** [comment]
@yeekangc I read the current guide on operator and it is quite simple. Since operator is the mainstream and it has a lot of capabilities such as Knative support, service binding and liveness, readiness probe and OIDC and OAuth2.0. I am wondering whether you can use this guide to focus on some of the advanced topics?

**Comment by yeekangc** [comment]
Thanks, @Emily-Jiang.  Will take a closer look and see what we can make of what you mentioned.

**Comment by yeekangc** [comment]
@gkwan-ibm, I think we have delivered on what's needed?

**Comment by gkwan-ibm** [comment]
yes, we published
- https://openliberty.io/guides/openliberty-operator-intro.html
- https://openliberty.io/guides/openliberty-operator-openshift.html
