### ISSUE TITLE
Consider creating a Check your environment section

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/guides-common#465]
### Suggestion for better user experience:
- Users would benefit from a **`Check your environment`** subsection in the **`Getting started`** section.
  - The section would correspond to the guide prereqs.
  - Could create a new adoc or update the existing one to include the content (which should be kept minimal). 

- The  **`Getting started`** section already includes the **`Try what you’ll build`** subsection so it may be overload. In this case, the TWYB subsection could be updated to include an environment check before the user tries the application, or the TWYB subsection can be a main section in the guides.

- For more complex guides that include in a cloud environment setup, this section could be combined with the content that verifies the right setup for that cloud environment. 

Perhaps an option for https://github.com/OpenLiberty/guides-common/issues/449.

**Comment by yeekangc** [comment]
The prereqs needed should be typical for a developer machine so in theory, there shouldn't be extra setup needed.  Also, we introduced the Prereqs section on the RH pane to clearly identify what users need to have.

Moreover, we are moving in the direction of providing cloud-hosted guides that users can try directly from a browser.
