### ISSUE TITLE
Update OpenShift guide to indicate CodeReady Containers as local option

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#467]
Update the OpenShift guide to indicate the option to use CodeReady Containers as the local option (and link out to relevant instruction).

**Comment by griffinhadfield** [comment]
Addressed in https://github.com/OpenLiberty/guide-okd/pull/55. I added the following paragraph to the end of What You'll Learn. 
>Minishift is based on OKD 3.11. To run OKD 4.1 or newer on your local system, you can instead use the CodeReady Containers tool. To learn how to use CodeReady Containers, check out [Red Hat’s guide](https://developers.redhat.com/blog/2019/09/05/red-hat-openshift-4-on-your-laptop-introducing-red-hat-codeready-containers/).

**Comment by yeekangc** [comment]
Consider a new guide using CRC for OKD 4.x.  Retain the current guide with Minishift updating it to indicate it's for OKD 3.x.  Update OpenShift guides (via #467 or as appropriate) to indicate local (dev) option(s) and point to relevant guides if appropriate.

**Comment by yeekangc** [comment]
This goes hand-in-hand with #387.

**Comment by griffinhadfield** [comment]
When the [CRC guide](https://github.com/openliberty/draft-guide-crc-openshift) is complete, I will add update the OKD guide to link to it

**Comment by AustinSeto** [comment]
Mentioned changes to OKD guide are merged to `prod`, OKD guide now contains link to CRC guide.
