### ISSUE TITLE
More useful OL Guides descriptions 

### ISSUE THREAD

**Issue by megmulsy** [OpenLiberty/guides-common#48]
I wanted to touch base about the guides descriptions on the Open Liberty All Guides page ([openliberty.io/guides](url)) 

I’ve noticed that most of these descriptions just echo exactly what is said in the title, instead of giving additional information to the user to help them decide whether or not this particular guide is what they need (see examples below) 
<img width="752" alt="ol-guidedescrip1" src="https://user-images.githubusercontent.com/13803016/35941838-4dc21c6a-0c19-11e8-97c5-87722028ef84.png">
<img width="751" alt="ol-guidedescrip2" src="https://user-images.githubusercontent.com/13803016/35941839-4dd90952-0c19-11e8-83e0-1bb092edf4ef.png">

The descriptive titles are a great start, but the descriptions should be edited to make this second level of info more useful for users. Taking out the repetition of ‘Learn how’ would help as well - finding new ways to phrase what the content contains. 

I’d like to strive toward something more like this that gives a user more info - The following is a better example of what's out there currently. 
<img width="360" alt="ol-guidedescrip3_better" src="https://user-images.githubusercontent.com/13803016/35941840-4dee9722-0c19-11e8-907b-88b9a1e8db1d.png">

Thanks!
Megan Mulholland - Open Liberty Design Team 
(I'm also @megmulsy on slack)

**Comment by sishida** [comment]
I think that descriptions could benefit from
1. Including keywords to help users find the guides they want and
2. Explaining why the user would want to complete the guide ("Learn how to X to accomplish Y." To give a non-OL example, "Learn how to use the pen tool in Photoshop to digitally ink your artwork.")

Is there a way that folks could update the descriptions and have me approve them? That would be more efficient than for me to try to update all the descriptions myself. I'm still familiarizing myself with the OL product. :) Thanks!

**Comment by yeekangc** [comment]
Thank you, @sishida.  @evelinec can help organize the updates -- Yes, it will be best for the authors to provide the updates for you to review, edit and approve.

**Comment by evelinec** [comment]
We'd handled the recent set of MP guides to have proper descriptions on the card. The same thing needs to be verified for the previous guides. @JunyiSun @Kubik42 and @Ahmad-Ayyoub: can you check this out for those other published guides? Thanks.

**Comment by JunyiSun** [comment]
Updated the description for multi-modules guide

**Comment by evelinec** [comment]
@sishida @yeekangc can you review the description for the multi multiple module guide: 
Learn how to build an application consisting of JAR, WAR, and EAR modules with Maven

**Comment by evelinec** [comment]
@Kubik42 can you revisit the descriptions of some of the other guides?

**Comment by evelinec** [comment]
@megmulsy @sishida I was wondering if it's ok to have a long description that doesn't show up entirely on the card? For example, go to https://openliberty.io/guides/ and search for "fallback". You'll see 3 guides show up, but 2 of them having longer descriptions that doesn't fit entirely on the card. Let us know what you think. Thanks.

**Comment by sishida** [comment]
I looked up the fallback guides, but the descriptions looked like they were fitting on the cards just fine. I prefer that the descriptions fit on the cards, but if we want to make it mandatory, we should inform the guide writers what is needed to make them fit. For example, we'd need to specify something like, "Limit the descriptions to X number of characters."

I also noticed that some guides, such as "Consuming a RESTful web service," have different descriptions on the cards compared to in the guides themselves. The descriptions on the cards should match the descriptions in the guides. I wonder where these other descriptions are being pulled from?

**Comment by evelinec** [comment]
@sishida Thanks for reviewing and providing your feedback. We'll consider them, and look into the "Consuming a RESTful web service" guide.

**Comment by evelinec** [comment]
@andrewdes Can you take a look at this issue and propose the needed changes for each of the guides?

**Comment by evelinec** [comment]
@andrewdes can you give an update on this issue pls? Thanks.

**Comment by yeekangc** [comment]
Expect a review of all the descriptions -- they should provide appropriate additional context and optimized for search -- with proposed edits.  Issues be filed for the actual updates if not actual updates done.

**Comment by evelinec** [comment]
@gkwan-ibm this issue was assigned to @andrewdes who did the work. Can you reassign to the team. Thank you.

**Comment by gkwan-ibm** [comment]
close
- this issue was fixed a while ago
- if anyone found a guide that still has this issue, open a new issue against its github repository
