### ISSUE TITLE
Updated guide for MP Rest Client 2.0

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/guides-common#480]
This is mainly for planning at this point - I'll need to add more specifics later.  MP Rest Client 2.0 (Epic Issue https://github.com/OpenLiberty/open-liberty/issues/10786) adds the following new functionalities:

1. Java EE 7 -> Jakarta EE 8 dependencies (probably not worth mentioning in the guide)
2. Ability to specify the style of HTTP query parameters for collections (might be worth mentioning...)
3. SSE Support using reactive streams API (probably the biggest change - probably worth mentioning)
4. Spec-compliant way to specify HTTP proxy server host and port (maybe)
5. Spec-compliant way to specify JSON-B configuration for MP Rest Client instances (maybe) 
6. Configuration for automatically following redirects (probably a good thing to mention)
7. CDI-managed providers, if available (this is a change in behavior from previous versions, so worth noting, but maybe not worth a separate guide?)

**Comment by yeekangc** [comment]
FYI, @gkwan-ibm.

**Comment by gkwan-ibm** [comment]
Hi @andymc12, I suggest following:

1.  Java EE 7 -> Jakarta EE 8 dependencies (probably not worth mentioning in the guide)
    - Agree, nothing to change in the guides
2. Ability to specify the style of HTTP query parameters for collections (might be worth mentioning...)
    - update the microprofile-rest-client guide, add a new REST api to get multiple properties to demonstrate this ability
3. SSE Support using reactive streams API (probably the biggest change - probably worth mentioning)
    - a new guide (but need to be prioritized) or in https://github.com/OpenLiberty/guides-common/issues/119
4. Spec-compliant way to specify HTTP proxy server host and port (maybe)
    - no update
5. Spec-compliant way to specify JSON-B configuration for MP Rest Client instances (maybe)
    - no update
6. Configuration for automatically following redirects (probably a good thing to mention)
    - update the microprofile-rest-client guide,  add `.followRedirects(true or false)` to the code and explain it at https://openliberty.io/guides/microprofile-rest-client.html#building-the-client-with-restclientbuilder. 
    - Question is to set true or false ?
7. CDI-managed providers, if available (this is a change in behavior from previous versions, so worth noting, but maybe not worth a separate guide?)
    - no update

cc @yeekangc

**Comment by gkwan-ibm** [comment]
info - https://openliberty.io/blog/2021/03/24/whats-new-in-MP-Rest-Client2.0.html

**Comment by gkwan-ibm** [comment]
updated point 3 in my above comment

**Comment by gkwan-ibm** [comment]
Hi @andymc12, 

After I studied and tried the 2 new features of MP Rest Client 2.0, [QueryParamStyle](https://openliberty.io/blog/2021/03/24/whats-new-in-MP-Rest-Client2.0.html#query-param-style) and [followRedirects](https://openliberty.io/blog/2021/03/24/whats-new-in-MP-Rest-Client2.0.html#auto-redirects), I do not recommend to add them into the [microprofile-rest-client](https://openliberty.io/guides/microprofile-rest-client.html) guide. They are slightly advance topics and will be hardly injected into the content. The application does not require/demo redirect, therefore, it is better not to talk about followRedirects. If add them into the guide, it will make the application more complex and break the content flow of the guide.

cc @yeekangc

**Comment by andymc12** [comment]
Hi @gkwan-ibm - that makes sense.  It might still make sense to add the SSE support functionality to the SSE guide as @yeekangc suggested, but other than that we probably don't need to make any other changes to the guides for MP Rest Client 2.0.  Thanks for investigating this!

**Comment by gkwan-ibm** [comment]
hi @andymc12 
Currently, the sse guide does not have sse client annotated with `@RegisterRestClient`. Would you suggest to us what should be changed in the sse guide, so that it can demonstrate how [mp rest client supports sse](https://openliberty.io/blog/2021/03/24/whats-new-in-MP-Rest-Client2.0.html#sse-support)?
Thanks

**Comment by andymc12** [comment]
Hi @gkwan-ibm - this SSE guide (https://openliberty.io/guides/reactive-messaging-sse.html) uses a JavaScript client to consume SSE messages - which is good to show for HTML-based clients.  But maybe we could add some unit (or integration) tests that use the MP Rest Client - something like:
```
@RegisterRestClient(baseUri = "http://localhost:9084/bff")
public interface SystemLoadService {

    @GET
    @Path("/sse")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    Publisher<SystemLoad> getSystemLoad();
}
```

```
// ...
final int expectedSystemLoadEvents = 3; // set this to whatever is appropriate from the guide
RestClientBuilder builder = RestClientBuilder.newBuilder()
                                             .executorService(Executors.newFixedThreadPool(4))
                                             .baseUrl(baseUrl);
try (SystemLoadService client = builder.build(SystemLoadService.class)) {
    GenericSubscriber<SystemLoad> subscriber = new GenericSubscriber<>(expectedSystemLoadEvents);
    client.getSystemLoad().subscribe(subscriber);
    subscriber.request(expectedSystemLoadEvents);
    assertTrue("Timed out waiting for system load event", subscriber.latch.await(WAIT_TIME, TimeUnit.SECONDS));
    assertTrue("onComplete not called", subscriber.onCompleteCalled);
    assertEquals("Unexpected errors encounter", 0, subscriber.onErrors.size());
    List<SystemLoad> systemLoads = subscriber.onNexts;
    assertEquals("Unexpected number of onNext calls", expectedSystemLoadEvents, systemLoads.size());
    assertThat(/*systemLoads contains expected data from server*/);
}
// ...
```

See [GenericSubscriber.java](https://github.com/OpenLiberty/open-liberty/blob/release/dev/com.ibm.ws.microprofile.rest.client_fat/test-applications/sseApp/src/mpRestClient20/sse/GenericSubscriber.java) and related test case files for implementation suggestions.

The idea of this test case in the guide would be that it is possible for users to invoke and read SSEs both in a web page and in a Java client application.

**Comment by gkwan-ibm** [comment]
hi @andymc12 I tried the integration-test and doubt what you suggested can be achieved. The guide integration-test is different than the liberty fat. It has no mp-rest-clent implementation, so I got following error:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.031 s <<< FAILURE! - in it.io.openliberty.guides.bff.BffServiceIT
[ERROR] testCpuStatus  Time elapsed: 0.02 s  <<< ERROR!
java.lang.IllegalStateException: No RestClientBuilderResolver implementation found!
	at it.io.openliberty.guides.bff.BffServiceIT.testCpuStatus(BffServiceIT.java:45)
```

**Comment by gkwan-ibm** [comment]
Also, in the reactive sse guide, the existing sse events are non-stop. It may not fit to implement an mp rest client to consume.

**Comment by andymc12** [comment]
@gkwan-ibm No worries.  You might be able to pull in the Apache CXF dependencies directly in order to have a MP Rest Client 2.0 implementation for the test cases, but it's not necessary.  Thanks for the update.

**Comment by gkwan-ibm** [comment]
hi @andymc12 
So, is it worth to address 6.? 

> 6. Configuration for automatically following redirects (probably a good thing to mention)
>     - update the microprofile-rest-client guide,  add `.followRedirects(true or false)` to the code and explain it at https://openliberty.io/guides/microprofile-rest-client.html#building-the-client-with-restclientbuilder.

**Comment by andymc12** [comment]
Hi @gkwan-ibm - I think we can probably skip that too.  It has some value, but it's more of an advanced feature, and users can learn about it from the javadocs or spec docs, etc.  Thanks!

**Comment by gkwan-ibm** [comment]
close
- after investigation and discussion, no further work for this item, except #119
