### ISSUE TITLE
Daily Builds

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/guides-common#485]

**Comment by AustinSeto** [comment]
Had multiple failures due to requiring Docker credential updates. Issue resolved for now (credentials updated) but investigating better solutions for these credentials in the future.

**Comment by gkwan-ibm** [comment]
Analyze the following options to update the guidesbot credential:
 
- By travis yaml
  - travis CLI encrypt the user and password
    - simple
  - update the .travis.yaml with the encrypted user and password
    - create and clone branch 
    - update the file
    - create a PR
    - go through the process to qa and master
  - Configuration
    - remove the env DOCEKER_USER and DOCEKER_PASSWORD from travis setting for each guide/repo (1 time deal)
- Jenkin existing solution
  - update the password in travis setting for each guide/repo
- Use Jenkin credential
    - Pros: single place to update password
    - Crons: values expose in travis website
    - explore any solution:
        - is there any better docker login solution?
        - instead of echo password and pipe in the docker login command?

**Comment by k-rtik** [comment]
I found a way to use Jenkins credential without exposing the values in plaintext in Travis logs, config, etc.
 
We can use the `TRAVIS_TOKEN` to query the public key for a repository. Using this public key, we can encrypt the credentials and send them as a secure environment variable to Travis as part of the `POST` request. By default, Travis hides the value of the secure environment variable in the logs, config, etc (although the encrypted string is visible)

Given:
`$TRAVIS_TOKEN`
`$REPO_NAME`
`$DOCKER_USER`
`$DOCKER_PASS`

```
# First, get the public encryption key for the repo from Travis
curl \
    -s \
    -H "Travis-API-Version: 3" \
    -H "User-Agent: API Explorer" \
    -H "Authorization: token $TRAVIS_TOKEN" \
    https://api.travis-ci.org/v3/repo/OpenLiberty%2f$REPO_NAME/key_pair/generated | jq -r ".public_key" > public_key

# Next, encrypt a secret using the public key
ENCRYPTED_USER=$(echo -n "DOCKER_USERNAME=$DOCKER_USER" | openssl rsautl -encrypt -inkey public_key -pubin | base64)
ENCRYPTED_PASS=$(echo -n "DOCKER_PASSWORD=$DOCKER_PASS" | openssl rsautl -encrypt -inkey public_key -pubin | base64)

# Add to the body as secure environment variable
body='{
    "request": {
        "message": "Build message",
        "branch":"master",
        "config": {
            "merge_mode": "merge",
            "env": {
                "secure": "'$ENCRYPTED_USER'",
                "secure": "'$ENCRYPTED_PASS'"
            }
        }
    }
}'
```
Log when it is set:
![image](https://user-images.githubusercontent.com/7340905/86826098-4082e380-c05e-11ea-857c-98c65b43b748.png)

Log when it is used:
![image](https://user-images.githubusercontent.com/7340905/86826111-45479780-c05e-11ea-9afd-f29ee140a0e7.png)

**Comment by AustinSeto** [comment]
PR to update Travis test for guide-microprofile-istio-retry-fallback: https://github.com/OpenLiberty/guide-microprofile-istio-retry-fallback/pull/53

PR open on Enterprise Github to update and cleanup daily build scripts and implement above solution for Jenkins credentials

**Comment by AustinSeto** [comment]
Builds over the weekend failed for JDK 11. Testing by building just a single guide shows no problems. Problem seems to be with Travis' `install-jdk.sh` script.

**Comment by AustinSeto** [comment]
Builds for JDK11 now working

**Comment by AustinSeto** [comment]
Some builds failing over weekend due to not being able to find `olguides` manifest. Saw announcement on Slack about hardware issues affecting build infrastructure. May be related, watching for updates.

**Comment by AustinSeto** [comment]
Previous issue for manifest occurred again this weekend, will check daily builds tomorrow to see if issue resolves itself.

**Comment by AustinSeto** [comment]
Docker image daily build failed overnight because "too many requests".

Successfully rebuilt it this morning and re-running the builds as many guides failed builds without the Docker image.

**Comment by gkwan-ibm** [comment]
close
- this task for Jul and Sep
