### ISSUE TITLE
Create a guide for MicroProfile Config

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#5]
Create a guide on how to use MicroProfile Config.

**Comment by evelinec** [comment]
@bcpswope The static MP config guide is ready for ID review. Can you pls plan this for iteration 18.4?
Repo: https://github.com/OpenLiberty/draft-guide-microprofile-config

**Comment by yeekangc** [comment]
https://openliberty.io/guides/microprofile-config.html
