### ISSUE TITLE
Fix tags/tagging for all the guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#50]
So searching can work properly.

- microservices, microprofile -- Ensure that searching for microservices or microprofile will give us all the MP guides
- CDI for CDI guide -- The same for the rest of the guides and the technologies they will cover too

**Comment by kinueng** [comment]
Per chat on slack, we are going with the tag `microservices`.  No capitalization or spaces.

**Comment by evelinec** [comment]
We had added and verified the tags for these guides: rest-intro, CDI, FT, JWT, Config, Health, and Metrics.

**Comment by evelinec** [comment]
Also for OpenTracing and OpenAPI guides. We'll make sure the other new MP guide will have the proper tags when it's ready.

**Comment by evelinec** [comment]
Can we close this one now?

**Comment by evelinec** [comment]
Yes, changes had been verified for the list of static MP guides.

**Comment by evelinec** [comment]
@kinueng can we close this issue?

**Comment by steven1046** [comment]
Yes, the tags have been added for the interactive guides.

**Comment by evelinec** [comment]
Checked with @steven1046 and it's good to close.
