### ISSUE TITLE
Automated testing of code assets for guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#51]
We should have automated testing for the code assets of the guides e.g. what's under /finish of the guide repos to ensure that they continue to work on new levels of OL and to catch any regression or issue.

The work should mostly be defining and setting up the infrastructure.  We should be able to reuse the JUnit tests in each of the guide as the tests to run.  Should review test coverage though.

**Comment by evelinec** [comment]
@yeekangc to help think of a plan for this issue. Keep us posted. Thanks.

**Comment by evelinec** [comment]
Let's discuss a plan for this issue during collaboration tomorrow.

**Comment by kinueng** [comment]
Hello,
Out of my own curiosity, is this still work to enable automated tests still ongoing?  I noticed that there has been a lot of excellent work being done by @Ahmad-Ayyoub to add functional tests in each of the guides' `.travis.yml`.

An example commit here for the rest intro
https://github.com/OpenLiberty/guide-rest-intro/commit/5b292088e85fad83f98085c298f42ea0cc4efbf2#diff-354f30a63fb0907d4ad57269548329e3

**Comment by yeekangc** [comment]
@kinueng, yes, this is what drives the work that you saw.

**Comment by evelinec** [comment]
We're done with the initial plan of this automation.
