### ISSUE TITLE
Try what you build should include the step `cd finish`

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/guides-common#514]
Currently, the guides tell the user to "go to the finish directory" and then run the command `mvn liberty:run` however, because "go to the finish directory" is not a command, it's very easy to miss, which causes an error from trying to run mvn from the root directory.  We should add `cd finish` to the `mvn liberty:run` block, or add another block for `cd finish`

![image](https://user-images.githubusercontent.com/3076261/94601592-50732380-0259-11eb-8329-05d560e80681.png)

Looking at the common includes, it seems we have several adocs for this section, and the current being used by guides is https://github.com/OpenLiberty/guides-common/blob/master/twyb-intro.adoc which does not have this step, however, the https://github.com/OpenLiberty/guides-common/blob/master/trywhatyoubuild-intro.adoc does have it.

Perhaps this this been cause due to various copies/versions of that file? or because the wrong guides are pulling in the wrong common adoc?

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
- [ ] guides-common (xxx)
- [ ] guide-1111 (yyy)

**Comment by griffinhadfield** [comment]
- [ ] guide-rest-intro
- [ ] 
- [ ]

**Comment by griffinhadfield** [comment]
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by griffinhadfield** [comment]
**List of guides to check:**

- [ ] guide-rest-intro
- [ ] guide-maven-intro
- [ ] guide-microprofile-jwt
- [ ] guide-getting-started
- [ ] guide-microprofile-opentracing
- [ ] guide-microprofile-config
- [ ] guide-rest-client-java
- [ ] guide-microprofile-rest-client
- [ ] guide-kubernetes-intro
- [ ] guide-microprofile-openapi
- [ ] guide-jpa-intro
- [ ] guide-microprofile-metrics
- [ ] guide-rest-hateoas
- [ ] guide-cdi-intro
- [ ] guide-rest-client-angularjs
- [ ] guide-maven-multimodules
- [ ] guide-docker
- [ ] guide-microprofile-health
- [ ] guide-cloud-openshift
- [ ] guide-gradle-intro
- [ ] guide-cors
- [ ] guide-istio-intro
- [ ] guide-arquillian-managed
- [ ] guide-kubernetes-microprofile-config
- [ ] guide-microprofile-fallback
- [ ] guide-spring-boot
- [ ] guide-bean-validation
- [ ] guide-security-intro
- [ ] guide-sessions
- [ ] guide-containerize
- [ ] guide-cloud-aws
- [ ] guide-cloud-ibm
- [ ] guide-cloud-azure
- [ ] guide-rest-client-angular
- [ ] guide-microshed-testing
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-microprofile-reactive-messaging
- [ ] guide-microprofile-opentracing-jaeger
- [ ] guide-microprofile-istio-retry-fallback
- [ ] guide-microprofile-reactive-messaging-acknowledgment
- [ ] guide-microprofile-reactive-messaging-rest-integration
- [ ] guide-okd
- [ ] guide-rest-client-reactjs
- [ ] guide-cloud-google
- [ ] guide-reactive-service-testing
- [ ] guide-social-media-login
- [ ] guide-reactive-rest-client
- [ ] guide-microprofile-rest-client-async

**Comment by gkwan-ibm** [comment]
close
- all guides were updated either added the cd command or made clear the navigate instruction
