### ISSUE TITLE
Update the "Securing microservices with JSON Web Tokens" guide for MP JWT 1.2

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/guides-common#525]
Update the https://openliberty.io/guides/microprofile-jwt.html guide with the mpJwt-1.2 feature and the new MP Config properties.

The MP Config properties will replace some of the configuration from server.xml.

For the latest version of the guide, under "Configuring MicroProfile JWT", please add the following properties:

> The `mp.jwt.token.header` property allows you to control the HTTP request header which is expected to contain a JWT token. You can specify either Authorization (default) or Cookie values.
> 
> The `mp.jwt.token.cookie` property allows you to specify the name of the cookie which is expected to contain a JWT token. The default value is Bearer if not specified.
> 
> The `mp.jwt.verify.audiences` property allows you to create list of allowable audience (aud) values. At least one of these must be found in the claim. Previously, this had to be configured in the server.xml file.
> 
> The `mp.jwt.decrypt.key.location` property allows you to specify the location of the Key Management Key. It is a Private key used to decrypt the Content Encryption Key, which is then used to decrypt the JWE ciphertext. This private key must correspond to the public key that is used to encrypt the Content Encryption Key.
> 
> The `mp.jwt.verify.publickey.algorithm` property allows you to control the Public Key Signature Algorithm that is supported by the MicroProfile JWT endpoint. The default value is `RSA256` if not specified. Previously, this had to be configured in the server.xml file.

The microprofile-config.properties file should contain all those properties, in addition to the mp.jwt.verify.issuer that is in the draft version.

In addition to the new MP Config property, we want to also show that you are now able to create an encrypted token (JWE) using the JwtBuilder, using the public key of the private key configured in `mp.jwt.decrypt.key.location`.

**Comment by yeekangc** [comment]
This should be under #549.

**Comment by gkwan-ibm** [comment]
ref: https://openliberty.io/blog/2021/03/26/MP-JWT-1.2.html

**Comment by teddyjtorres** [comment]
You can use a relative file name for mp.jwt.decrypt.key.location,

> mp.jwt.decrypt.key.location=privatekey.pem

Then put the file in the WAR file in,

> /WEB-INF/classes/privatekey.pem

**Comment by gkwan-ibm** [comment]
hi @teddyjtorres 

In the mp-jwt guide, the application uses default keystore. In this case, there is no need to define `mp.jwt.decrypt.key.location`. Is that right?

I suggest to comment out that `#mp.jwt.decrypt.key.location=/path/to/privatekey.pem` property. In the guide, we still can explain it. What do you think? Or would you suggest a better idea?

**Comment by gkwan-ibm** [comment]
close
- the [mp-jwt guide](https://openliberty.io/guides/microprofile-jwt.html) was updated, mainly in the [Configuring MicroProfile JWT](https://openliberty.io/guides/microprofile-jwt.html#configuring-microprofile-jwt) section
