### ISSUE TITLE
Migrate guides to use GitHub action for testing

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#531]
Detail in https://ibm.ent.box.com/notes/737495994830
- [x] Investigate and prototype solution to use Github action for testing
- [x] Stage 1: Use Github action to test the qa branch, and keep use travis for master branch
  - 51/51 completed providing that JWT change will be merged later
- [x] Investigate/prototype a solution to use Github action for daily build
- [x] Stage 2:
   - Use Github Actions for daily builds to test master branch
   - See https://github.com/OpenLiberty/guide-getting-started/pull/206 for example of below
      - Remove `travis.yml` and `travisTest.sh` from each guide
      - Add `dailyBuild.sh` to each guide
         - Takes in date, driver, build level, docker username
         - `dailyBuild.sh` will contain appropriate `sed` commands
         - Will run tests similarly to previous `travisTest.sh`
- [x] Stage 3: Create scheduled Guthub action to test the OL Docker images
- [x] Stage 4: documentation

**Comment by AustinSeto** [comment]
Merge https://github.com/OpenLiberty/guides-common/pull/530 after merging PRs linked [here](https://github.com/OpenLiberty/guides-common/pull/530#issuecomment-733079305) so we can do a trial run with the guides listed.

**Comment by gkwan-ibm** [comment]
Updated draft-guides-template for the following files:
- .github/workflows/test.yml
- scripts/testApp.sh 
- scripts/dailyBuild.sh

**Comment by gkwan-ibm** [comment]
completed but need to document the infrastructure/setup

**Comment by gkwan-ibm** [comment]
close
- all tasks were done
- daily build result is available at https://github.com/OpenLiberty/guides-common/actions
