### ISSUE TITLE
Guide PR checker

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#532]
### Objective:
Investigate if we can keep both the action.yml and python script in one repository. [*](http://blog.marcnuri.com/triggering-github-actions-across-different-repositories/)
Else, we can possibly find/consider something similar to dependabot.
By using Github action, implement a checker to verify the PR for the following 
1. java file
    - [x] license year is updated
    - [x] java code lines no longer than 88 chars
1. the README.adoc follows the[ best practices](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles) (use [asciidoctorj](https://github.com/asciidoctor/asciidoctorj) if necessary)
    - [x] no "We ", "Our ", . "Blacklist", "whitelist", "master ", and "slave " with case insensitive  (can use asciidoctorj to walk through the content instead of parsing unnecessary lines) (in a json in guides-commons)
    - [x] no "I " with case sensitive 
    - [x] warning for the recommended words: "since ", "black" and "white"
    - [x] copyright content starting by `//` (cannot be done by asciidoctorj)
    - [x] `:page-releasedate:` must be a real date (better use asciidoctorj) 
    - [x] line too long warning 120? 100? 
    - [x] `:page-tags:` should only contain either tags (`"name"`) defined in https://github.com/OpenLiberty/guides-common/blob/master/guide_tags.json
    - ...
1. [ ] pom or gradle configuration file using latest plugins
1. [ ] compare the start and finish directories
1. ...

### Information:
- Get PR changed files: https://github.community/t/get-list-of-files-on-pull-request-merge/17226

**Comment by yeekangc** [comment]
Consider the use of https://github.com/github/super-linter or equivalent.

**Comment by gkwan-ibm** [comment]
- preparing PR for the getting started guide and review in progress

**Comment by gkwan-ibm** [comment]
- enabled 3/52 guides to use PR checker

**Comment by gkwan-ibm** [comment]
enabled 17/52 guides + a draft guide to use PR checker

**Comment by gkwan-ibm** [comment]
- enabled 27/52 guides + a draft guide to use PR checker
- PRs were created for the rest of the guides

**Comment by gkwan-ibm** [comment]
close
- all 52 guides were enabled PR check
