### ISSUE TITLE
Re-name Kafka topic names 

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/guides-common#536]
The Reactive Messaging SME pointed out that the Kafka topic names we are using are unconventional. The Kafka topic names of our guides should be renamed according to the following conventions: 
- https://riccomini.name/how-paint-bike-shed-kafka-topic-naming-conventions
or
-  https://devshawn.com/blog/apache-kafka-topic-naming-conventions/

Below is a list of all of the guides that include Kafka that need their topics renamed:
- [x] guide-microprofile-reactive-messaging
    - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging/pull/102
- [x] guide-microprofile-reactive-messaging-rest-integration
    - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-rest-integration/pull/37 (merged)
- [x] guide-microprofile-reactive-messaging-acknowledgment
    - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-acknowledgment/pull/41 (merged)
- [x] guide-reactive-rest-client
   - https://github.com/OpenLiberty/guide-reactive-rest-client/pull/81
- [x] guide-microprofile-rest-client-async
    - https://github.com/OpenLiberty/guide-microprofile-rest-client-async/pull/89
- [x] guide-reactive-service-testing
    - https://github.com/OpenLiberty/guide-reactive-service-testing/pull/75
- [x] guide-cloud-openshift-operator
    - https://github.com/OpenLiberty/guide-cloud-openshift-operator/pull/60

**Comment by gkwan-ibm** [comment]
close
- all reactive guides were updated
