### ISSUE TITLE
November Guide Daily Build and EjbDeploy Skillcase Monitoring

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#537]
- Monitor the guides Daily Build and Docker Daily Build Testing (including to investigate any failure)
- Monitor the EjbDeploy skillcases including L3 support
- Training Tien

**Comment by AustinSeto** [comment]
`info.json` at https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/ does not show the build `2020-11-11_0736/`, so daily builds for 2020-11-11 did not trigger properly. 

Manually triggered daily builds, and they are currently in progress.

**Comment by AustinSeto** [comment]
https://github.com/OpenLiberty/guide-arquillian-managed fails daily builds since last PR changed `pom.xml`, need to update automation script.

**Comment by gkwan-ibm** [comment]
close
- this issue is for internal use
