### ISSUE TITLE
Guide for Arquillian Remote

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/guides-common#54]
Guide on how to use the `configureArquillian` task in `liberty-gradle-plugin` and `configure-arquillian` goal in `liberty-maven-plugin`, as well as the Arquillian Liberty dependency bundles, with Arquillian Liberty Remote 1.0.0.Final (pending release).

**Comment by yeekangc** [comment]
This is the case where Arquillian will work with a Liberty server that is remote.  Both Maven and Gradle will be covered.

**Comment by yeekangc** [comment]
Consider if this should be done as a guide (when we are ready to work on it).

**Comment by gcharters** [comment]
We will get the Arquillian local out and see how much interest there is before committing to remote.

**Comment by yeekangc** [comment]
The plan is per https://github.com/OpenLiberty/guides-common/issues/54#issuecomment-408146328.  Closing for now and can re-open when there is interest or further feedback.
