### ISSUE TITLE
Container guides to cover good practices

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#540]
Guides that cover how to containerize should cover good/best practices for externalizing configuration and working with Liberty configuration in container-based deployments/Kubernetes environment.

> For example....
> Lets say I have a Liberty server running on a Linux server today.  And that Liberty server's server.xml has embedded configuration details about a connection to an LDAP server.  Like so;
```
>     <ldapRegistry id="GPLDServerLDAP" realm="GPLDRealm" host="gpld2s.example.com" port="636" sslEnabled="TRUE"
>         sslRef="defaultSSLSettings" ignoreCase="true" baseDN="dc=example,dc=com" loginProperty="uid"
>         bindDN="cn=ProdUser,ou=applications,dc=example,dc=com" bindPassword=""
>         ldapType="Sun Java System Directory Server">
>     ... snip ...
>     </ldapRegistry>
```
> I'd like to move my application into the RH Openshift environment.  So, I've built a container image with my application and the version of Liberty that I require.  But, I don't want to have a separate container image for Dev, Test, and Prod.  I'd like to use the same container image for each environment.  Then, depending on the environment, pass in details of the LDAP server to which the Liberty server should connect.  So, rather than hard-code the LDAP server details in the server.xml, I'd like to be able to pass those environment details into the container when the container is starting up in a cluster.

Candidate guides to update:
https://openliberty.io/guides/kubernetes-microprofile-config.html
https://openliberty.io/guides/containerize.html

Related issue: https://github.com/OpenLiberty/docs/issues/3275

**Comment by yeekangc** [comment]
See https://github.com/OpenLiberty/docs/issues/3275 for list of items and details of what should be reflected in our guides.

**Comment by yeekangc** [comment]
Consider what is noted in https://github.com/OpenLiberty/guides-common/issues/511 if appropriate too.

**Comment by gkwan-ibm** [comment]
- the containerize guide update
  - final content review in progress
- the kube config guide
  - addressing SME review feedback

**Comment by gkwan-ibm** [comment]
- the containerize guide updated
- the kube config guide
  - ready for ID review

**Comment by yeekangc** [comment]
@jamiecoleman92

**Comment by gkwan-ibm** [comment]
close
- both guides were updated
  - https://openliberty.io/guides/kubernetes-microprofile-config.html
  - https://openliberty.io/guides/containerize.html
