### ISSUE TITLE
Update testcontainers dependency for Kafka guides

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/guides-common#541]
With certain combinations of the Docker Desktop version and Mac OS version, the `org.testcontainers` dependency can cause the following error when attempting to run tests locally: 

```
[ERROR] it.io.openliberty.guides.query.QueryServiceIT  Time elapsed: 33.174 s  <<< ERROR!
java.lang.IllegalStateException: Can not connect to Ryuk at localhost:32771
```

I was receiving this error when trying to run tests on some of the Kafka guides.

According to this issue: https://github.com/testcontainers/testcontainers-java/issues/3166, updating testcontainers to version 1.15.0 fixes this. I have tested it and it seems to have fixed the issue for me. 

Below is a list of all of the guides that include Kafka, some or all of these guides use `org.testcontainers` so we should go through each, check if the dependency is used, and update the version to 1.15.0 if it is.

- [x] guide-microprofile-reactive-messaging
  - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging/pull/103
- [x] guide-microprofile-reactive-messaging-rest-integration
  - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-rest-integration/pull/38 (merged)
- [x] guide-microprofile-reactive-messaging-acknowledgment
  - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-acknowledgment/pull/42
- [x] guide-reactive-rest-client
    - https://github.com/OpenLiberty/guide-reactive-rest-client/pull/88 (merged)
- [x] guide-microprofile-rest-client-async
   - https://github.com/OpenLiberty/guide-microprofile-rest-client-async/pull/91 (merged)
- [x] guide-reactive-service-testing
   - Addressed along with other issue in https://github.com/OpenLiberty/guide-microprofile-rest-client-async/pull/89
- [x] guide-cloud-openshift-operator
    - Addressed along with other issue in https://github.com/OpenLiberty/guide-cloud-openshift-operator/pull/60
- [x] draft-guide-reactive-messaging-sse
    - https://github.com/OpenLiberty/draft-guide-reactive-messaging-sse/pull/22 (merged)

**Comment by gkwan-ibm** [comment]
close
- all guides were updated
