### ISSUE TITLE
Config for Diff Envs with MP Config Profile

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guides-common#548]
A new guide needs to be written to demonstrate MP Config 2.0
1. variable replacement
2. config profile
3. ConfigProperties

More info can be found [here](https://download.eclipse.org/microprofile/staging/microprofile-config-2.0/microprofile-config-spec-2.0.html#release_notes_20)

**Comment by gkwan-ibm** [comment]
hi @Emily-Jiang 
> More info can be found here

The here link return 404. Would you correct it so that we can get more information? Beside UFO, is there a blog to talk about MP Configure 2.0?

**Comment by Emily-Jiang** [comment]
@gkwan-ibm check out this [MP Config 2.0 blog](https://openliberty.io/blog/2021/03/31/microprofile-config-2.0.html). There was a video link to show you how to use MP Config 2.0 as well in the blog.

**Comment by gkwan-ibm** [comment]
ref:
- https://github.com/OpenLiberty/open-liberty/issues/11016

**Comment by yeekangc** [comment]
Thank you, team!  Let us proceed to publish.

**Comment by gkwan-ibm** [comment]
close
- the guide and its cloud-hosted were published
- https://openliberty.io/guides/microprofile-config-profile.html
