### ISSUE TITLE
Guide for Log4J

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guides-common#55]
Introduction to the popular Apache logging framework Log4j, and learn how to add logs to your Open Liberty applications using Log4j

**Comment by yeekangc** [comment]
https://github.com/OpenLiberty/draft-guide-log4j

**Comment by yeekangc** [comment]
Draft exists and help wanted to help complete it.

**Comment by evelinec** [comment]
Thank you for revisiting this topic. We will not be archiving this draft.

**Comment by fwji** [comment]
So we don't want to officially publish the guide now, as it will give the false impression that LogJ or Log4J2 is the recommended logging solution for developing Open Liberty java applications when there are no other logging guides out there. We still recommend the users to use the default java logging util whenever possible as it is the best-supported logging framework that also supports the new JSON logging. JSON logging is the foundation for Open Liberty to play nicely with cluster logging solution like ELK stack in a cloud environment. However, this writing still serves a good reference to point to when helping customer debugging their log4j configuration. So I would recommend archiving the draft for now. And if anything, creating a different document specifically on logging in Open Liberty. We can introduce our recommended setup as well as the popular alternatives such as log4j or the new logback and slf4j.

**Comment by yeekangc** [comment]
Thank you for the feedback and follow-up, @fwji @gkwan-ibm.

@evelinec @gkwan-ibm, please archive the repo when ready.

I will be closing this issue.

**Comment by evelinec** [comment]
The repository, https://github.com/OpenLiberty/archived-guide-log4j, is now archived.
