### ISSUE TITLE
Archive cloud-openshift guide at end of support for OpenShift 3.x

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#550]
Archive https://openliberty.io/guides/cloud-openshift.html when OpenShift 3.x reaches the end of full support.

According to https://access.redhat.com/support/policy/updates/openshift_noncurrent, OpenShift 3.x will reach end of full support by June 2021.

@gkwan-ibm

**Comment by yeekangc** [comment]
@gkwan-ibm is looking at a related item.  Assigning to Gilbert for now to consider (what's more that needs to be done).

**Comment by gkwan-ibm** [comment]
- [x] redirect `https://openliberty.io/guides/cloud-openshift.html` to `https://openliberty.io/guides/cloud-openshift-operator.html`
- [x] rename github repo `guide-cloud-openshift` to `archived-guide-cloud-openshift`
- [x] archived the github repo

**Comment by gkwan-ibm** [comment]
close
- all tasks were completed
