### ISSUE TITLE
Update guides for Fault Tolerance 3.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/guides-common#555]
The following guides should be updated for Fault Tolerance 3.0 when it is released (currently in beta):

* https://openliberty.io/guides/microprofile-fallback.html
* https://openliberty.io/guides/microprofile-istio-retry-fallback.html

These guides are interactive and don't appear to have been updated since Fault Tolerance 1.0. Should they be updated too or do we not update the interactive guides?
* https://openliberty.io/guides/retry-timeout.html
* https://openliberty.io/guides/bulkhead.html
* https://openliberty.io/guides/circuit-breaker.html

In each case the content of the guide doesn't need to change, just the versions of the features that are listed in the server.xml and pom.xml.

Here are the versions of features which should be used with mpFaultTolerance-3.0. If a guide is using a feature in conjunction with mpFaultTolerance-3.0, it should use the version listed here:
 - microprofile-4.0
 - mpFaultTolerance-3.0
 - mpConfig-2.0
 - mpRestClient-2.0
 - mpMetrics-3.0
 - cdi-2.0
 - jaxrs-2.1
 - jsonp-1.1
 - mpContextPropagation-1.1

**Comment by Azquelt** [comment]
Sorry, I've just noticed that there's already an epic for MP 4.0 updates in #549. If you don't need this issue, please close it.

**Comment by yeekangc** [comment]
Thank you, @Azquelt.  We should at least use this to figure out what we should do for interactive guides.

@steven1046 @k8vance88, any thoughts?

**Comment by yeekangc** [comment]
Cc @gkwan-ibm.

**Comment by steven1046** [comment]
I do think we should update the interactive guides. We can create issues in those repos to update the Fault Tolerance feature.

**Comment by gkwan-ibm** [comment]
close
- both static guides were updated
- opened https://github.com/OpenLiberty/iguides-common/issues/347 for iguides
