### ISSUE TITLE
Change OL runtime versions to "RELEASE" and test all guides

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guides-common#56]
`LATEST` and `RELEASE` version numbers don't make any different as of yet (since only GM guilds are pushed into the Maven repo), but we should stick to using `RELEASE` just in case this changes in the future.

So, lets make sure we're using `RELEASE` in all of the guides and that this versions works (ie. run the tests to verify).

Current guides not using `RELEASE` (this is based on whats currently on the dev site):

Please change the `version` tag to `RELEASE` in your pom.xml (**this includes under start and under finish!!!**):
```
<groupId>io.openliberty</groupId>
<artifactId>openliberty-runtime</artifactId>
<version>LATEST</version>
```

**Comment by evelinec** [comment]
Tested that both the "LATEST" and "RELEASE" version downloaded the same version. 

LATEST:
Open Liberty 17.0.0.4/wlp-1.0.19.201712061531

RELEASE:
Open Liberty 17.0.0.4/wlp-1.0.19.201712061531

**Comment by evelinec** [comment]
Looks like FT guide had been updated. @Ahmad-Ayyoub pls update Health and Metrics guide if they aren't already been done so. @JunyiSun pls update JWT and Config. Thanks.

**Comment by evelinec** [comment]
CDI - DONE.

**Comment by evelinec** [comment]
@JunyiSun pls update for jwt. Thanks.

**Comment by JunyiSun** [comment]
@evelinec JWT updated to RELEASE
