### ISSUE TITLE
Potential problems with Windows instructions when using Powershell

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/guides-common#566]
First observed [here](https://github.com/OpenLiberty/guide-containerize/pull/63#discussion_r542821469) during testing of a PR for the containerize guide on Windows 10.

The command being executed was

```
mvn failsafe:integration-test -Dsystem.ip=172.17.0.2 -Dinventory.http.port=9081 -Dsystem.http.port=9080
```

The command failed with the following error

```
[ERROR] Unknown lifecycle phase ".ip=172.17.0.2". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>.
```

***

After discussing with @griffinhadfield it turned out that this was a result of using Powershell, and the commands worked fine if using the command prompt. It's possible that this issue may be applicable to other guides, with similar failures occurring if using Powershell in Windows. 

Will keep a list of guides this was observed in here. 

- [ ] guide-containerize

**Comment by griffinhadfield** [comment]
We found that the specific cause of the issue was the presence of periods (`.`) in the variable names that were being set. It appears that Powershell was parsing them incorrectly and using the periods as some sort of operator, causing the command to fail.

**Comment by gkwan-ibm** [comment]
close
- powershell is not officially support
