### ISSUE TITLE
Update dependencies and evaluate reactive and Kafka guides 

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/guides-common#603]
There seems to be multiple, interconnected issues stemming from different dependency versions used in the reactive and Kafka guides.  

Rather than trying fixing these piecemeal, I think it would be most effective to update all involved dependencies across all effective guides to their latest version, re-evaluate any common issues, and determine what needs to be done to fix these problems. 

Procedure: 

   1. `mvn clean`
   2. `rm -r ~/.m2` Clear .m2 cache 
   3. `docker rmi -f $(docker images -q)` Remove any existing docker images
   4. Conduct end-to-end test from `finish` and run `mvn verify`
   5. Check for and record errors
   6. Repeat steps 1-3
   4. Update the following dependencies:
       - `LMP` -> `3.3.4`
       - `kafka-clients` -> `2.7.0`
       - `microshed-testing-liberty` -> `0.9.1`
       - `testcontainers` -> `1.15.1`
   5. Conduct end-to-end test from `finish` and run `mvn verify`
   6. Check for and record errors
   7. If no errors, create PR 

Potentially Impacted Guides: 

- [x] guide-microprofile-reactive-messaging
- [x] guide-microprofile-reactive-messaging-rest-integration
- [x] guide-microprofile-reactive-messaging-acknowledgment
- [x] guide-reactive-rest-client
- [x] guide-microprofile-rest-client-async
- [x] guide-reactive-service-testing
- [x] guide-cloud-openshift-operator
- [x] guide-reactive-messaging-sse

**Comment by griffinhadfield** [comment]
## guide-microprofile-reactive-messaging

**Before updating dependencies:** 

- Error during end-to-end test: NO
- Error during `mvn verify`: YES
    > `com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: quay.io/testcontainers/ryuk:0.2.3"}
`

**After updating dependencies:** 
- Error during end-to-end test: NO
- Error during `mvn verify`: NO
- PR: https://github.com/OpenLiberty/guide-microprofile-reactive-messaging/pull/111

**Comment by AustinSeto** [comment]
# guide-reactive-messaging-sse

In progress

**Before updating dependencies:**

- Error during end-to-end test: 
- Error during `mvn verify`:

After updating dependencies:

- Error during end-to-end test: 
- Error during mvn verify: 
- PR:

**Comment by griffinhadfield** [comment]
## guide-microprofile-reactive-messaging-rest-integration

**Before updating dependencies:** 

- Error during end-to-end test: NO
- Error during `mvn verify`: YES
    > `Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}`

**After updating dependencies:** 
- Error during end-to-end test: NO
- Error during `mvn verify`: NO
- PR: https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-rest-integration/pull/45

**Comment by griffinhadfield** [comment]
## guide-microprofile-reactive-messaging-acknowledgment

**Before updating dependencies:** 

- Error during end-to-end test: NO
- Error during `mvn verify`: YES
```
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: quay.io/testcontainers/ryuk:0.2.3"}
```

**After updating dependencies:** 
- Error during end-to-end test: NO
- Error during `mvn verify`: NO
- PR: https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-acknowledgment/pull/53

**Comment by AustinSeto** [comment]
# guide-cloud-openshift-operator

In progress

**Before updating dependencies:**

- Error during end-to-end test: 
- Error during `mvn verify`: 

After updating dependencies:

- Error during end-to-end test: 
- Error during mvn verify: 
- PR:

**Comment by AustinSeto** [comment]
# guide-reactive-service-testing

In progress

**Before updating dependencies:**

- Error during end-to-end test: 
- Error during `mvn verify`: 

After updating dependencies:

- Error during end-to-end test: 
- Error during mvn verify: 
- PR:

**Comment by griffinhadfield** [comment]
## guide-reactive-rest-client

**Before updating dependencies:** 

- Error during end-to-end test: NO
- Error during `mvn verify`: YES
```
com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
```

**After updating dependencies:** 
- Error during end-to-end test: NO
- Error during `mvn verify`: NO
- PR: https://github.com/OpenLiberty/guide-reactive-rest-client/pull/98

**Comment by AustinSeto** [comment]
# guide-microprofile-rest-client-async

In progress

**Before updating dependencies:**

- Error during end-to-end test: 
- Error during `mvn verify`: 

After updating dependencies:

- Error during end-to-end test: 
- Error during mvn verify: 
- PR:

**Comment by gkwan-ibm** [comment]
close
- all related guides were updated
