### ISSUE TITLE
MP Guides are missing the tests for the system service

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guides-common#61]
I'm not sure how we ended up not including these, but for the sake of consistency, let put them back in every guide.

I'm talking about these: https://github.com/OpenLiberty/guide-rest-intro/blob/master/finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java

Create a new directory `it/io/openliberty/guides/system` and put these tests there. Then run `mvn verify` and make sure these tests are run as part of the build.

**Comment by evelinec** [comment]
MP guides that already have he EndpointTtest: CDI, FT, Config, Health and Metrics.
Guides that are missing: JWT (not sure it's applicable here) @JunyiSun 
@Kubik42 If it makes sense for OpenTracing and OpenAPI, add include it there.

**Comment by yeekangc** [comment]
Good to have for regression testing and we should clearly which is for what endpoint.  Should have these as we look ahead to setup automated tests.

**Comment by JunyiSun** [comment]
@evelinec JWT has the EndpointTest which is called EndPointTestWithJWT, since it's the modified version with JWT features.

**Comment by Kubik42** [comment]
@evelinec Thats not the endpointtest I'm talking about. Please look at the link I posted.

**Comment by evelinec** [comment]
@Kubik42 Ah, the test cases are of the same name! I thought it was strange when I found most of the MP guides have the inventory endpoint tests already. Let's rename/rework them and include to the guides.

**Comment by evelinec** [comment]
CDI guide is updated.

**Comment by evelinec** [comment]
FT guide is updated.

**Comment by evelinec** [comment]
@Ahmad-Ayyoub @JunyiSun pls add for the other MP guides. Thanks.

**Comment by Ahmad-Ayyoub** [comment]
Metrics guide is updated

**Comment by Ahmad-Ayyoub** [comment]
Health guide is updated

**Comment by JunyiSun** [comment]
Updated for Config and JWT

**Comment by evelinec** [comment]
Regarding this issue, I think we're still missing a quick statement about the system endpoint test that we included in the guides. I think something like this, from @Kubik42's other guides, is good. Adjust it to fix the individual guide. @Ahmad-Ayyoub @JunyiSun 
```
A few tests have been included for you to test the basic functionality of the inventory service. If a test failure occurs, then you must have introduced a bug into the code. These tests will run automatically as a part of the Maven build process (when you run mvn install). You can also run these tests separately from the build using the mvn verify command, but make sure that the server is stopped beforehand.
```

For example, this is for the CDI guide: 
```
Finally, a `system` test class in the `src/test/java/it/io/openliberty/guides/system/SystemEndpointTest.java` file,
has been included for you to test the basic functionality of the `inventory` service.
If a test failure occurs, then you must have introduced a bug into the code.
```
Notice you need to update the test output to reflect the 2 or more test cases as well. 

I'll fix the FT guide as well.

**Comment by JunyiSun** [comment]
The JWT guide has different endpoint tests (with security tokens), therefore, there is no need to add this statement.

**Comment by evelinec** [comment]
Statement is added for the FT guide too. This will be reviewed together by ID.

**Comment by JunyiSun** [comment]
Added for Config.

**Comment by evelinec** [comment]
@Ahmad-Ayyoub can you confirm when the same are done for the other guides? Thanks.

**Comment by Ahmad-Ayyoub** [comment]
@evelinec I have added that for both health and metrics

**Comment by evelinec** [comment]
@Kubik42 can you take a final look? Altho the health and metrics guides fixes are still in the PR at this moment.

**Comment by Kubik42** [comment]
Just checked CDI, JWT, FT, health, config, metrics:

- start/.../inventory/EndpointTest in metrics should be start/.../inventory/InventoryEndpointTest (I didnt see this in the PR)

**Comment by evelinec** [comment]
@Ahmad-Ayyoub ^ take a look. Thanks.

**Comment by Ahmad-Ayyoub** [comment]
It is `InventoryEndpointTest` look at my Fork
