### ISSUE TITLE
Update scripts to test guides on GitHub Actions

### ISSUE THREAD

**Issue by AustinSeto** [OpenLiberty/guides-common#639]
Occasionally on our daily build tests for the guides, one or two guide tests will fail for the day, usually just on Java 8 or Java 11, but not on both. The error is usually something similar to the following, which has been taken from a run this morning:

```
Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.2.3:war (default-war) on project backendServices: Execution default-war of goal org.apache.maven.plugins:maven-war-plugin:3.2.3:war failed: Plugin org.apache.maven.plugins:maven-war-plugin:3.2.3 or one of its dependencies could not be resolved: Could not transfer artifact org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/sonatype/sisu/sisu-inject-plexus/1.4.2/sisu-inject-plexus-1.4.2.jar: Connection reset -> [Help 1]
```

A re-run of the daily build test for the single guide shows no issues. From what I can see, the issue lies in Maven, not the guide application or Open Liberty. From what I found after some research, it may have something to do with Maven and Azure and how connections are handled.

I have found other reports of this issue and a work around to implement is to add the following options when running Maven: 

```
-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 
```

As the GitHub Actions run out of https://github.com/OpenLiberty/guides-common simply runs a build script found in each guide repo (each guide may have a different structure), an update to each of those build scripts is required, using these options on the Maven commands. 

See the following issue and comment on GitHub Actions for details: https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080

Guides to do:

- [x] guide-getting-started
  - https://github.com/OpenLiberty/guide-getting-started/pull/237 
- [x] guide-arquillian-managed
  - https://github.com/OpenLiberty/guide-arquillian-managed/pull/103
- [x] guide-microprofile-opentracing
  - No PR needed
- [x] draft-guide-graphql-intro
  - https://github.com/OpenLiberty/draft-guide-graphql-intro/pull/28
- [x] guide-rest-client-java
  - https://github.com/OpenLiberty/guide-rest-client-java/pull/125
- [x] guide-reactive-messaging-sse
  - https://github.com/OpenLiberty/guide-reactive-messaging-sse/pull/61
- [x] guide-microprofile-rest-client
  - ~~https://github.com/OpenLiberty/guide-microprofile-rest-client/pull/168~~
  - https://github.com/OpenLiberty/guide-microprofile-rest-client/pull/169
- [x] guide-maven-intro
  - https://github.com/OpenLiberty/guide-maven-intro/pull/122
- [x] guide-maven-multimodules
  - https://github.com/OpenLiberty/guide-maven-multimodules/pull/89
- [x] guide-rest-client-angularjs
  - https://github.com/OpenLiberty/guide-rest-client-angularjs/pull/94
- [x] guide-microprofile-reactive-messaging-acknowledgment
  - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-acknowledgment/pull/72
- [x] guide-microshed-testing
  - https://github.com/OpenLiberty/guide-microshed-testing/pull/82
- [x] guide-security-intro
  - https://github.com/OpenLiberty/guide-security-intro/pull/125
- [x] guide-kubernetes-microprofile-health
  - https://github.com/OpenLiberty/guide-kubernetes-microprofile-health/pull/105
- [x] guide-microprofile-opentracing-jaeger
  - https://github.com/OpenLiberty/guide-microprofile-opentracing-jaeger/pull/38
- [x] guide-cdi-intro
  - https://github.com/OpenLiberty/guide-cdi-intro/pull/177
- [x] guide-contract-testing
  - https://github.com/OpenLiberty/guide-contract-testing/pull/33
- [x] guide-okd
  - https://github.com/OpenLiberty/guide-okd/pull/71
- [x] guide-cloud-azure
  - https://github.com/OpenLiberty/guide-cloud-azure/pull/48
- [x] guide-mongodb-intro
  - https://github.com/OpenLiberty/guide-mongodb-intro/pull/77
- [x] guide-cloud-ibm
  - https://github.com/OpenLiberty/guide-cloud-ibm/pull/114
- [ ] guide-cloud-google
  - https://github.com/OpenLiberty/guide-cloud-google/pull/43
- [x] guide-rest-client-angular
  - https://github.com/OpenLiberty/guide-rest-client-angular/pull/108
- [x] guide-gradle-intro
  - Not applicable, guide does not use Maven
- [x] guide-sessions
  - ~~https://github.com/OpenLiberty/guide-sessions/pull/113~~
  - https://github.com/OpenLiberty/guide-sessions/pull/114
- [x] guide-social-media-login
  - https://github.com/OpenLiberty/guide-social-media-login/pull/71
- [x] guide-microprofile-openapi
   - https://github.com/OpenLiberty/guide-microprofile-openapi/pull/125
- [x] guide-rest-hateoas
  - https://github.com/OpenLiberty/guide-rest-hateoas/pull/86
- [x] guide-microprofile-reactive-messaging
  - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging/pull/121
- [x] guide-istio-intro
  - https://github.com/OpenLiberty/guide-istio-intro/pull/126
- [x] guide-microprofile-health
  - https://github.com/OpenLiberty/guide-microprofile-health/pull/152
- [x] guide-spring-boot
  - https://github.com/OpenLiberty/guide-spring-boot/pull/76
- [x] guide-microprofile-jwt
  - https://github.com/OpenLiberty/guide-microprofile-jwt/pull/165
- [x] guide-microprofile-metrics
  - ~~https://github.com/OpenLiberty/guide-microprofile-metrics/pull/149~~
  - https://github.com/OpenLiberty/guide-microprofile-metrics/pull/150
- [x] guide-jpa-intro
  - https://github.com/OpenLiberty/guide-jpa-intro/pull/165
- [x] guide-reactive-service-testing
  - https://github.com/OpenLiberty/guide-reactive-service-testing/pull/93
- [x] guide-cloud-openshift-operator
  - https://github.com/OpenLiberty/guide-cloud-openshift-operator/pull/86
- [x] guide-reactive-rest-client
  - https://github.com/OpenLiberty/guide-reactive-rest-client/pull/116
- [x] guide-microprofile-config
  - https://github.com/OpenLiberty/guide-microprofile-config/pull/181
- [x] guide-rest-intro
  - https://github.com/OpenLiberty/guide-rest-intro/pull/170
- [x] guide-rest-client-reactjs
  - https://github.com/OpenLiberty/guide-rest-client-reactjs/pull/47
- [x] guide-cors
  - https://github.com/OpenLiberty/guide-cors/pull/76
- [x] guide-kubernetes-intro
  - https://github.com/OpenLiberty/guide-kubernetes-intro/pull/192
- [x] guide-cloud-aws
  - https://github.com/OpenLiberty/guide-cloud-aws/pull/111
- [x] guide-microprofile-fallback
  - https://github.com/OpenLiberty/guide-microprofile-fallback/pull/174
- [x] guide-containerize
  - https://github.com/OpenLiberty/guide-containerize/pull/94
- [x] guide-microprofile-rest-client-async
  - https://github.com/OpenLiberty/guide-microprofile-rest-client-async/pull/115
- [x] guide-cloud-openshift
  - https://github.com/OpenLiberty/guide-cloud-openshift/pull/88
- [x] guide-bean-validation
  - https://github.com/OpenLiberty/guide-bean-validation/pull/93
- [x] guide-microprofile-reactive-messaging-rest-integration
  - https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-rest-integration/pull/60
- [x] guide-docker
  - https://github.com/OpenLiberty/guide-docker/pull/118
- [x] guide-openshift-codeready-containers
  - https://github.com/OpenLiberty/guide-openshift-codeready-containers/pull/29
- [x] guide-kubernetes-microprofile-config
  - https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/pull/132
- [x] guide-microprofile-istio-retry-fallback
  - https://github.com/OpenLiberty/guide-microprofile-istio-retry-fallback/pull/80

**Comment by gkwan-ibm** [comment]
close
- all guides were fixed except the cloud-google guide. It will be fixed by https://github.com/OpenLiberty/guide-cloud-google/pull/43
