### ISSUE TITLE
Guide for Spring Boot WebSocket app on Liberty

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/guides-common#64]
Convert and update https://github.com/WASdev/sample.SpringBootWebsocket as an OL guide.

**Comment by yeekangc** [comment]
Draft repo: https://github.com/OpenLiberty/draft-guide-springboot-websocket

**Comment by yeekangc** [comment]
Need to work out if there are still relevant pieces in this guide that we should cover with #175 or in separate (new) guides.

@chyt, do let us know if you have any thoughts.  Thanks.

**Comment by yeekangc** [comment]
Superseded by #175.
