### ISSUE TITLE
Update all MP Health guides to use MP Health 3.1

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/guides-common#683]
A new mpHealth-3.1 feature will be available in OL for 21.0.0.8 (In 21.0.0.8-beta), all our current guides that use the mpHealth feature should be updated to use mpHealth-3.1.

- https://openliberty.io/guides/microprofile-health.html
- https://openliberty.io/guides/kubernetes-microprofile-health.html
- https://openliberty.io/guides/microprofile-health.html

In mpHealth-3.1 introduced a new annotation called `@Startup` and a new endpoint `/health/started`. We need to update our existing guides to have a code example of the usage of `@Startup` and the endpoint `/health/started`.

In our [Kubernetes Microprofile Health ](https://openliberty.io/guides/kubernetes-microprofile-health.html)guide, we need to update the the YAML file to include the configuration for the Kubernetes Startup Probe and have a usage example, with the new endpoint.

**mpHealth-3.1 Epic :** https://github.com/OpenLiberty/open-liberty/issues/16626

**Comment by gkwan-ibm** [comment]
hi @pgunapal 

May you or your team to update the guides by providing us the PRs? It may be more efficient.

**Comment by pgunapal** [comment]
Hi @gkwan-ibm 
We can definitely provide PRs for the changes described in this issue, we will wait till the `mpHealth-3.1` feature is in a GA build for the 21.0.0.9, to begin working on the guides.

**Comment by gkwan-ibm** [comment]
close
- most guides were updated to  mpHealth-4.0
- the reactive and graphql guides will be updated when the new mp reactive and graphql features are released on OL 22.0.0.6+  (by issue #759)
