### ISSUE TITLE
Switch java download in guides prereq to use semeru site

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/guides-common#703]
@k8vance88 commented on [Tue Aug 03 2021](https://github.com/OpenLiberty/openliberty.io/issues/2234)

adoptopenjdk is moving to https://developer.ibm.com/languages/java/semeru-runtimes/downloads

---

@steven1046 commented on [Wed Aug 11 2021](https://github.com/OpenLiberty/openliberty.io/issues/2234#issuecomment-897062553)

This is the guides prereqs at the top right

---

@mbroz2 commented on [Wed Aug 11 2021](https://github.com/OpenLiberty/openliberty.io/issues/2234#issuecomment-897063665)

Update the [java link in guides prereq](https://github.com/OpenLiberty/guides-common/blob/32d66ee7e8021df359f6611ce5f77b62b1f1548a/guide_prereqs.json#L5) to point at [Semeru downloads](https://developer.ibm.com/languages/java/semeru-runtimes/downloads)

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
Semerun Runtime for Mac is not ready yet. Switch at least when Mac download is ready.

**Comment by gkwan-ibm** [comment]
close
- the link was updated
