### ISSUE TITLE
Create a tag for cloud-hosted guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#705]
To make it easy for users to find guides that they can run in cloud.  This will allow for a URL to list all cloud-hosted guides too.

Consider "Run In Cloud", "RunInCloud" or "Run-In-Cloud" as the tag.

@gkwan-ibm

**Comment by gkwan-ibm** [comment]
- tag name “Run in cloud”?
- visible or invisible?
- add it to suggested tags?
- add an icon?

**Comment by gkwan-ibm** [comment]
close
- the **Run in cloud** tag is showing in  https://openliberty.io/guides/
