### ISSUE TITLE
Update to use dev mode with multi module project

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/guides-common#707]
https://github.com/OpenLiberty/ci.maven/issues/697 will add multi module support for dev mode.  It is currently only available in milestone releases of the Liberty Maven plugin (e.g. version 3.3.5-M2).  When it is available in a non-milestone release, update this guide to make use of dev mode.  

To run dev mode with a multi module project, run a command like the following from the top level multi module directory (e.g. the `finish` directory that contains the multi module `pom.xml`):
`mvn io.openliberty.tools:liberty-maven-plugin:3.3.5-M2:dev`

For other ways to run dev mode (which will be documented), see Slide 29 of the dev mode multi module UFO at https://ibm.box.com/s/lziitxx4jpsmekddi8p0nev90sevqv3l

(Note that the `run` goal will also work with multi module projects when invoked in the same way as `dev`)

**Comment by yeekangc** [comment]
LGTM.  Let us proceed to publish the updates.  Thanks all!

**Comment by yeekangc** [comment]
@gkwan-ibm, please close this issue when the updates are live.

**Comment by gkwan-ibm** [comment]
close
- the https://openliberty.io/guides/maven-multimodules.html was updated
