### ISSUE TITLE
Guide for GraphQL Client

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#718]
## Running GraphQL queries by GraphQL client
**What you’ll learn**
- Intro
- What is GraphQL client?
- Description of application with diagram as slide 3
- Ask user to study the Querying and modifying data by GraphQL

**Additional prerequisites**
- Docker

**Getting started**

**Implementing the Graphql client interface**
- Create the SystemClient interface
- Explain the detail

**Implementing Inventory service**
- Create the InventoryResource class 
- Explain how the InventoryResource use the SystemClient
- Configure the pom.xml, and server.xml
- Create the microprofile-config.properties to configure the GraphQL client url

**Building and running the application**
- Run scripts to build and start the application: two system, graphql, and inventory services in docker container
- Run the openapi ui to invoke the inventory APIs to queries the system information, update the note, and queries system loads

**Tearing down the environment**

**Comment by lauracowen** [comment]
I'm happy to approve this guide, subject to the style/clarity points in [this issue](https://github.com/OpenLiberty/draft-guide-graphql-client/issues/27) being addressed.

**Comment by yeekangc** [comment]
Signing off for Laura.  @lauracowen, thank you for the final review and approval!
