### ISSUE TITLE
Simpler guide for Deploying with Open Liberty Operator

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#736]
The current https://openliberty.io/guides/cloud-openshift-operator.html guide is relatively involved.  We can use a simpler and more focused version covering a straightforward scenario deploying an application using Open Liberty Operator to Kubernetes or OpenShift.

This can be a revision to https://openliberty.io/guides/kubernetes-intro.html.

**Comment by yeekangc** [comment]
Cc @gkwan-ibm

**Comment by gkwan-ibm** [comment]
published
- https://openliberty.io/guides/openliberty-operator-intro.html
- https://openliberty.io/guides/openliberty-operator-openshift.html

**Comment by gkwan-ibm** [comment]
@yeekangc it is OK to close
