### ISSUE TITLE
Guide for JMS

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#75]
Jakarka Messaging (JMS)
- instead of using 3rd party or IBM MQ, the guide can use OL embedded wasJmsClient-2.0 and wasJmsServer-1.0 features

**Comment by lauracowen** [comment]
Sorry - didn't meant to close it - got confused by the Zenhub UI. I've put it back in Prioritized but it might not be in the right place in the list now. :(

**Comment by yeekangc** [comment]
A CAB member indicated interest in a JMS guide.

**Comment by gkwan-ibm** [comment]
- Peer review:
  - https://github.com/OpenLiberty/draft-guide-jms-intro/issues/34
  - https://github.com/OpenLiberty/draft-guide-jms-intro/issues/35
  - https://github.com/OpenLiberty/draft-guide-jms-intro/issues/36
- SME review: https://github.com/OpenLiberty/draft-guide-jms-intro/issues/49

**Comment by gkwan-ibm** [comment]
- final content review: https://github.com/OpenLiberty/draft-guide-jms-intro/issues/72

**Comment by gkwan-ibm** [comment]
- final end-to-end test: https://github.com/OpenLiberty/draft-guide-jms-intro/issues/37

**Comment by gkwan-ibm** [comment]
- ID review: https://github.com/OpenLiberty/draft-guide-jms-intro/pull/71

**Comment by gkwan-ibm** [comment]
close
- the guide was published including the cloud-hosted version at https://openliberty.io/guides/jms-intro.html
