### ISSUE TITLE
Guide for Testcontainers

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#813]
Consider a guide that covers the use of Testcontainers with Jakarta EE, MicroProfile and Open Liberty.

**Comment by yeekangc** [comment]
Cc @gkwan-ibm

**Comment by gkwan-ibm** [comment]
Need this guide to replace the MST guide because MST is 
- idle 
- using docker image from dockerhub
- may hard-coded to use OL jdk8 image
- using EE8
- not able to run with JDK17

**Comment by gkwan-ibm** [comment]
peer reviews:
- https://github.com/OpenLiberty/draft-guide-testcontainers/issues/11
- https://github.com/OpenLiberty/draft-guide-testcontainers/issues/12
- https://github.com/OpenLiberty/draft-guide-testcontainers/issues/13

**Comment by gkwan-ibm** [comment]
- SME review: 
  - https://github.com/OpenLiberty/draft-guide-testcontainers/issues/16
- ID review:
  - https://github.com/OpenLiberty/draft-guide-testcontainers/pull/22

**Comment by gkwan-ibm** [comment]
- Final content review:
  -  https://github.com/OpenLiberty/draft-guide-testcontainers/issues/26
  - https://github.com/OpenLiberty/draft-guide-testcontainers/issues/25
- Final end-to-end test:
  - https://github.com/OpenLiberty/draft-guide-testcontainers/issues/14

**Comment by yeekangc** [comment]
Thank you, @shin19991207 @gkwan-ibm!

**Comment by yeekangc** [comment]
Please double check and update front matter before publishing.

**Comment by gkwan-ibm** [comment]
close
- the guide was published at https://openliberty.io/guides/testcontainers.html
