### ISSUE TITLE
How to deprecate and remove old guides?

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#814]
Work out a scheme to deprecate and remove old or dated guides

@gkwan-ibm

**Comment by yeekangc** [comment]
Cc @lauracowen

**Comment by gkwan-ibm** [comment]
The scheme will be:
- the deprecated guide will show a deprecated message on a banner
  - the message will provide a link to a new/other guide
  - the site will implement the banner by this [issue](https://github.com/OpenLiberty/openliberty.io/issues/3028)
- the guide will be removed from the ol.io/guides page
- the guide will keep online until there is very low or no traffic
- when there is very low or no traffic,
  - the guide url will be redirected to a new/other guide
  - the github repo will be renamed to `archived-guide-<projectid>`
  - the cloud-hosted (guided-project) will be removed from the OL SN portal

**Comment by gkwan-ibm** [comment]
close
- the [microprofile-opentracing](https://openliberty.io/guides/microprofile-opentracing.html), [microprofile-opentracing-jaeger](https://openliberty.io/guides/microprofile-opentracing-jaeger.html), and [okd](https://openliberty.io/guides/okd.html) guides was deprecated in the ol.io site
