### ISSUE TITLE
Use .java files for any unit and integration tests

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guides-common#83]
To avoid any more potential issues with Maven picking up `.gitkeep` files and attempting to run them as tests, lets tweak our poms from now on to include everything under the `it` directory that is also a java file.

ie. should be something like this: `it/.../*.java`

**Comment by yeekangc** [comment]
That's what we should do and fix.  Thanks.

**Comment by JunyiSun** [comment]
Added for Config

**Comment by evelinec** [comment]
Added for CDI

**Comment by evelinec** [comment]
@Kubik42 can you verify this is done for all rest-intro, CDI, FT, JWT, Config, Health and Metrics guides, by EOD today? Escalate or fix any that's not done.

**Comment by evelinec** [comment]
Added for FT

**Comment by Kubik42** [comment]
Just checked,

The following guides are missing this change for unit tests in both `start and `finish`:
- CDI
- FT
- config
- metrics
- health

The following guides are missing this change entirely:
- JWT

**Comment by Kubik42** [comment]
Regarding the comment above, unit tests are ok not to have this change.

**Comment by JunyiSun** [comment]
Added for JWT.

**Comment by Kubik42** [comment]
Thanks @JunyiSun
