### ISSUE TITLE
Container guides not working on new Mac architecture

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guides-common#833]
Now Apple are using their own CPU chips (M1/M2) based on ARM architecture our guides no longer work due to not having a container image available for this. There is a work around for Docker use but when testing with Kubernetes we are hitting an issue of the JVM falling over most likely due to architecture differences. The workaround would be `--platform linux/amd64` that pulls down the intel image and Docker does virtualisation to get it running but this is very slow and builds are taking 10x as long.

Here is a link to the feature request: https://github.com/OpenLiberty/ci.docker/issues/241

**Comment by gkwan-ibm** [comment]
close
- OL docker images support ARM architecture
- the guides have no need to do the workaround
