### ISSUE TITLE
Add tool links to key guides

### ISSUE THREAD

**Issue by jgawor** [OpenLiberty/guides-common#834]
On the "Add to an existing application" section on the https://openliberty.io/start/ page, each of the tabs have a link to a corresponding tool guide. That's great, but only one of the guides (Gradle) has a direct link to the GitHub page with more information about that particular tool right in the introduction. It would be good to add a similar links to Maven and Docker guides so that is easier to get the details.

**Comment by gkwan-ibm** [comment]
close
- both guides were updated

**Comment by jgawor** [comment]
@gkwan-ibm thank you!
