### ISSUE TITLE
Update testApp.sh not to log the downloading messages

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#836]
- In the `testApp.sh`, add `-ntp` option into the `mvn` commands that can reduce the downloading messages to make the test log more clear
- some guides use `testXXX.sh`
- some guides need to add `-q` option to the docker pull command(s) as `docker pulll -q ..`
- check` dailyTest.sh` and `dockerImageTest.sh` too

**Comment by gkwan-ibm** [comment]
Work on the following guides:

**Comment by gkwan-ibm** [comment]
Work on the following guides:

**Comment by gkwan-ibm** [comment]
Work on the following guides:

**Comment by gkwan-ibm** [comment]
Work on the following guides: 
abc

**Comment by gkwan-ibm** [comment]
$STRING

**Comment by gkwan-ibm** [comment]
Work on the following guides:
-[ ] arquillian-managed
-[ ] bean-validation
-[ ] cdi-intro
-[ ] cloud-aws
-[ ] cloud-azure
-[ ] cloud-google
-[ ] cloud-ibm
-[ ] cloud-openshift
-[ ] cloud-openshift-operator
-[ ] containerize
-[ ] containerize-podman
-[ ] contract-testing
-[ ] cors
-[ ] docker
-[ ] getting-started
-[ ] gradle-intro
-[ ] graphql-client
-[ ] grpc-intro
-[ ] istio-intro
-[ ] jakarta-websocket
-[ ] jpa-intro
-[ ] kubernetes-intro
-[ ] kubernetes-microprofile-config
-[ ] kubernetes-microprofile-health
-[ ] liberty-deep-dive
-[ ] maven-intro
-[ ] maven-multimodules
-[ ] microprofile-config
-[ ] microprofile-fallback
-[ ] microprofile-graphql
-[ ] microprofile-health
-[ ] microprofile-istio-retry-fallback
-[ ] microprofile-jwt
-[ ] microprofile-metrics
-[ ] microprofile-openapi
-[ ] microprofile-opentracing
-[ ] microprofile-opentracing-jaeger
-[ ] microprofile-reactive-messaging
-[ ] microprofile-reactive-messaging-acknowledgment
-[ ] microprofile-reactive-messaging-rest-integration
-[ ] microprofile-rest-client
-[ ] microprofile-rest-client-async
-[ ] microshed-testing
-[ ] mongodb-intro
-[ ] okd
-[ ] openliberty-operator-intro
-[ ] openliberty-operator-openshift
-[ ] openshift-codeready-containers
-[ ] reactive-messaging-sse
-[ ] reactive-rest-client
-[ ] reactive-service-testing
-[ ] rest-client-angular
-[ ] rest-client-angularjs
-[ ] rest-client-java
-[ ] rest-client-reactjs
-[ ] rest-hateoas
-[ ] rest-intro
-[ ] security-intro
-[ ] sessions
-[ ] social-media-login
-[ ] spring-boot

**Comment by gkwan-ibm** [comment]
Work on the following guides:
- [] guide-arquillian-managed
- [] guide-bean-validation
- [] guide-cdi-intro
- [] guide-cloud-aws
- [] guide-cloud-azure
- [] guide-cloud-google
- [] guide-cloud-ibm
- [] guide-cloud-openshift
- [] guide-cloud-openshift-operator
- [] guide-containerize
- [] guide-containerize-podman
- [] guide-contract-testing
- [] guide-cors
- [] guide-docker
- [] guide-getting-started
- [] guide-gradle-intro
- [] guide-graphql-client
- [] guide-grpc-intro
- [] guide-istio-intro
- [] guide-jakarta-websocket
- [] guide-jpa-intro
- [] guide-kubernetes-intro
- [] guide-kubernetes-microprofile-config
- [] guide-kubernetes-microprofile-health
- [] guide-liberty-deep-dive
- [] guide-maven-intro
- [] guide-maven-multimodules
- [] guide-microprofile-config
- [] guide-microprofile-fallback
- [] guide-microprofile-graphql
- [] guide-microprofile-health
- [] guide-microprofile-istio-retry-fallback
- [] guide-microprofile-jwt
- [] guide-microprofile-metrics
- [] guide-microprofile-openapi
- [] guide-microprofile-opentracing
- [] guide-microprofile-opentracing-jaeger
- [] guide-microprofile-reactive-messaging
- [] guide-microprofile-reactive-messaging-acknowledgment
- [] guide-microprofile-reactive-messaging-rest-integration
- [] guide-microprofile-rest-client
- [] guide-microprofile-rest-client-async
- [] guide-microshed-testing
- [] guide-mongodb-intro
- [] guide-okd
- [] guide-openliberty-operator-intro
- [] guide-openliberty-operator-openshift
- [] guide-openshift-codeready-containers
- [] guide-reactive-messaging-sse
- [] guide-reactive-rest-client
- [] guide-reactive-service-testing
- [] guide-rest-client-angular
- [] guide-rest-client-angularjs
- [] guide-rest-client-java
- [] guide-rest-client-reactjs
- [] guide-rest-hateoas
- [] guide-rest-intro
- [] guide-security-intro
- [] guide-sessions
- [] guide-social-media-login
- [] guide-spring-boot

**Comment by gkwan-ibm** [comment]
- [ ]

**Comment by gkwan-ibm** [comment]
Work on the following guides:
- [x] guide-arquillian-managed
- [x] guide-bean-validation
- [x] guide-cdi-intro
- [x] guide-cloud-aws
- [x] guide-cloud-azure
- [x] guide-cloud-google
- [x] guide-cloud-ibm
- [x] guide-cloud-openshift
- [x] guide-cloud-openshift-operator
- [x] guide-containerize
- [x] guide-containerize-podman
- [x] guide-contract-testing
- [x] guide-cors
- [x] guide-docker
- [x] guide-getting-started
- [x] guide-gradle-intro
- [x] guide-graphql-client
- [x] guide-grpc-intro
- [x] guide-istio-intro
- [x] guide-jakarta-websocket
- [x] guide-jpa-intro
- [x] guide-kubernetes-intro
- [x] guide-kubernetes-microprofile-config
- [x] guide-kubernetes-microprofile-health
- [x] guide-liberty-deep-dive
- [x] guide-maven-intro
- [x] guide-maven-multimodules
- [x] guide-microprofile-config
- [x] guide-microprofile-fallback
- [x] guide-microprofile-graphql
- [x] guide-microprofile-health
- [x] guide-microprofile-istio-retry-fallback
- [x] guide-microprofile-jwt
- [x] guide-microprofile-metrics
- [x] guide-microprofile-openapi
- [x] guide-microprofile-opentracing
- [x] guide-microprofile-opentracing-jaeger
- [x] guide-microprofile-reactive-messaging
- [x] guide-microprofile-reactive-messaging-acknowledgment
- [x] guide-microprofile-reactive-messaging-rest-integration
- [x] guide-microprofile-rest-client
- [x] guide-microprofile-rest-client-async
- [x] guide-microshed-testing
- [x] guide-mongodb-intro
- [x] guide-okd
- [x] guide-openliberty-operator-intro
- [x] guide-openliberty-operator-openshift
- [x] guide-openshift-codeready-containers
- [x] guide-reactive-messaging-sse
- [x] guide-reactive-rest-client
- [x] guide-reactive-service-testing
- [x] guide-rest-client-angular
- [x] guide-rest-client-angularjs
- [x] guide-rest-client-java
- [x] guide-rest-client-reactjs
- [x] guide-rest-hateoas
- [x] guide-rest-intro
- [x] guide-security-intro
- [x] guide-sessions
- [x] guide-social-media-login
- [x] guide-spring-boot

**Comment by ReeceNana** [comment]
### Edited - Needing to be checked and reviewed

### [adding -ntp to maven #151 - OpenLiberty/guide-istio-intro/pull/151](https://github.com/OpenLiberty/guide-istio-intro/pull/151)

### [adding -ntp to maven #194 - OpenLiberty/guide-jpa-intro/pull/194](https://github.com/OpenLiberty/guide-jpa-intro/pull/194)

### [adding -ntp to maven #31 - OpenLiberty/guide-jakarta-websocket/pull/31](https://github.com/OpenLiberty/guide-jakarta-websocket/pull/31)

### [adding -ntp to maven #229 - OpenLiberty/guide-kubernetes-intro/pull/229](https://github.com/OpenLiberty/guide-kubernetes-intro/pull/229)

### [adding -ntp to maven #170 - OpenLiberty/guide-kubernetes-microprofile-config/pull/170](https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/pull/170)

### [adding -ntp to maven #77 - OpenLiberty/guide-microprofile-graphql/pull/77](https://github.com/OpenLiberty/guide-microprofile-graphql/pull/77)

**Comment by ReeceNana** [comment]
### Already checked/compliant - Needs to be reviewed by @gkwan-ibm 

### [guide-grpc-intro](https://github.com/OpenLiberty/guide-grpc-intro/pull/41)
### [guide-kubernetes-microprofile-health](https://github.com/OpenLiberty/guide-kubernetes-microprofile-health/pull/136)
### [guide-maven-intro](https://github.com/OpenLiberty/guide-maven-intro/pull/153)
### [guide-maven-multimodules](https://github.com/OpenLiberty/guide-maven-multimodules/pull/122)
### [guide-microprofile-config](https://github.com/OpenLiberty/guide-microprofile-config/pull/205)
### [guide-microprofile-fallback](https://github.com/OpenLiberty/guide-microprofile-fallback/pull/195)
### [guide-microprofile-health](https://github.com/OpenLiberty/guide-microprofile-health/pull/176)

**Comment by ReeceNana** [comment]
### guide-jakarta-websocket - already done

**Comment by jakub-pomykala** [comment]
### Already checked/compliant - Needs to be reviewed by @gkwan-ibm 

### [guide-graphql-client](https://github.com/OpenLiberty/guide-graphql-client/pull/53)
### [guide-microprofile-istio-retry-fallback](https://github.com/OpenLiberty/guide-microprofile-istio-retry-fallback/pull/105)
### [guide-microprofile-jwt](https://github.com/OpenLiberty/guide-microprofile-jwt/pull/188)
### [guide-microprofile-metrics](https://github.com/OpenLiberty/guide-microprofile-metrics/pull/175)
### [guide-microprofile-openapi](https://github.com/OpenLiberty/guide-microprofile-openapi/pull/157)
### [guide-microprofile-opentracing](https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/164)
### [guide-micrprofile-opentracing-jaeger](https://github.com/OpenLiberty/guide-microprofile-opentracing-jaeger/pull/73)
### [guide-microprofile-reactive-messaging](https://github.com/OpenLiberty/guide-microprofile-reactive-messaging/pull/145)
### [guide-microprofile-rest-client](https://github.com/OpenLiberty/guide-microprofile-rest-client/pull/188)
### [guide-openliberty-operator-intro](https://github.com/OpenLiberty/guide-openliberty-operator-intro/pull/38)
### [guide-openliberty-operator-openshift](https://github.com/OpenLiberty/guide-openliberty-operator-openshift/pull/19)
### [guide-openshift-codeready-containers](https://github.com/OpenLiberty/guide-openshift-codeready-containers/pull/42)
### [guide-reactive-messaging-sse](https://github.com/OpenLiberty/guide-reactive-messaging-sse/pull/85)
### [guide-reactive-rest-client](https://github.com/OpenLiberty/guide-reactive-rest-client/pull/133)
### [guide-reactive-service-testing](https://github.com/OpenLiberty/guide-reactive-service-testing/pull/115)
### [guide-microprofile-reactive-messaging-acknowledgment](https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-acknowledgment/pull/98)
### [guide-microprofile-reactive-messaging-rest-integration](https://github.com/OpenLiberty/guide-microprofile-reactive-messaging-rest-integration/pull/85)
### [guide-microprofile-rest-client-async](https://github.com/OpenLiberty/guide-microprofile-rest-client-async/pull/140)
### [guide-microshed-testing](https://github.com/OpenLiberty/guide-microshed-testing/pull/110)
### [guide-mongodb-intro](https://github.com/OpenLiberty/guide-mongodb-intro/pull/113)
### [guide-okd](https://github.com/OpenLiberty/guide-okd/pull/94)
### [guide-rest-client-angular](https://github.com/OpenLiberty/guide-rest-client-angular/pull/180)
### [guide-rest-client-angularjs](https://github.com/OpenLiberty/guide-rest-client-angularjs/pull/111)
### [guide-rest-client-java](https://github.com/OpenLiberty/guide-rest-client-java/pull/145)
### [guide-rest-client-reactjs](https://github.com/OpenLiberty/guide-rest-client-reactjs/pull/116)
### [guide-rest-hateoas](https://github.com/OpenLiberty/guide-rest-hateoas/pull/105)
### [guide-rest-intro](https://github.com/OpenLiberty/guide-rest-intro/pull/200)
### [guide-security-intro](https://github.com/OpenLiberty/guide-security-intro/pull/142)
### [guide-sessions](https://github.com/OpenLiberty/guide-sessions/pull/162)
### [guide-social-media-login](https://github.com/OpenLiberty/guide-social-media-login/pull/75)

### Failed test initially but fixed
### [guide-spring-boot](https://github.com/OpenLiberty/guide-spring-boot/pull/118)

**Comment by gkwan-ibm** [comment]
close
- all guides were addressed
