### ISSUE TITLE
Verify all naming are correct for MP guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#84]
Ref: https://ibm.ent.box.com/file/281716465645

This include all of projectid, artifactid, related guide, tags, duration, title and abstracts.

**Comment by evelinec** [comment]
@JunyiSun can you pls do this for rest-intro, CDI, FT, JWT, Config, Health, and Metrics guides?

**Comment by evelinec** [comment]
@JunyiSun we need this one to be targeted today. Thanks.

**Comment by JunyiSun** [comment]
@evelinec Okay

**Comment by JunyiSun** [comment]
@evelinec I went over CDI, FT, JWT, Config, Health, and Metrics guides and opened issues accordingly. The rest-intro guide is not in that table so I don't know what to look for.

**Comment by evelinec** [comment]
Great, thanks.
