### ISSUE TITLE
Create a Cloud Foundry Buildpacks to Paketo Buildpack Migration Guide 

### ISSUE THREAD

**Issue by rxu1** [OpenLiberty/guides-common#844]
Migration Topics to include in the guide: 

- Using UBI images
- Installing iFixes
- Installing custom features
- Using different profiles (full, jakarta9, webProfile9, webProfile8, javaee8, microProfile4, microProfile5, kernel)
- Providing server.xml at build time.
- Building from a Liberty Server
- Building from a Packaged Server

**The target date to publish this guide is October 26th.**

**Comment by gkwan-ibm** [comment]
close
- will publish in IBM Cloud doc
