### ISSUE TITLE
Create a guide for React

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#85]
Guide for developing web apps with React running on Open Liberty and connecting to services on Open Liberty.

**Comment by DannyS03** [comment]
- researching/beginning to prototype.
- limited progress due to L3 support.

**Comment by DannyS03** [comment]
- On hold due to issue with ejbdeploy

**Comment by evelinec** [comment]
- can show prototype of both app and guide outline to Gilbert

**Comment by DannyS03** [comment]
- researching/beginning to prototype again.

**Comment by gkwan-ibm** [comment]
- working on an app

**Comment by ankitagrawa** [comment]
Need to review the app with Gilbert.

**Comment by DannyS03** [comment]
- app uses rest client api for getting a list of users
- in the frontend we build a paginated table for showing all list of users coming from rest api

**Comment by gkwan-ibm** [comment]
- sent a prototyped app for dev content review

**Comment by gkwan-ibm** [comment]
- drafting the Readme

**Comment by gkwan-ibm** [comment]
1. need to find out a minimal set of reactjs files
2. put the files into the liberty project (similar to angular guide)
3. instuction to start the app
   - including do something similar to angular guide, i.e. mvn generate-resources
4. approach:
   a. (take this approach) simplest approach: use angular guide scenario, i.e. artists.json
   b. complex approach: convert the reactive sse guide

**Comment by DannyS03** [comment]
- repo created: https://github.com/OpenLiberty/draft-guide-rest-client-reactjs
- application now similar to application found in angular/angularjs/rest-client-java guides.
- `node_modules` accidentally committed and resulted in "large amount of reactjs files" 
- `pom.xml` configured to run `mvn generate-resources` to take care of all npm installation and build.

**Comment by jimmy1wu** [comment]
some suggestions:
https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/issues/2

**Comment by gkwan-ibm** [comment]
- almost complete the draft of Readme

**Comment by gkwan-ibm** [comment]
- ready for dev content review

**Comment by DannyS03** [comment]
https://draft-guides.mybluemix.net/guides/rest-client-reactjs.html

**Comment by gkwan-ibm** [comment]
- dev content review 1
  - https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/issues/3

**Comment by gkwan-ibm** [comment]
- addressing the dev content review 1  feedback

**Comment by gkwan-ibm** [comment]
- addressed the dev content 1 feedback

**Comment by gkwan-ibm** [comment]
- ready for 2nd review

**Comment by ankitagrawa** [comment]
- Need to verify the changes on the dev branch.

**Comment by ankitagrawa** [comment]
- updating the readme

**Comment by gkwan-ibm** [comment]
- made that the React frontend can be run under OL server
- updated README
- ready for dev content review

**Comment by meswan** [comment]
Working on an issue in the start directory.

**Comment by DannyS03** [comment]
#### To date: 
The below has been addressed. Scope of guide has been updated accordingly. Originally, the guide was trying to follow the template for `guide-rest-client-angular` & `guide-rest-client-angularjs` but has been modified to cater the needs of having a single execution on the OL server while using reactjs as the frontend. The guide also does not go into as much detail about the frontend as it used to, and the focus is on the http client/rest client application. 
- https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/issues/3#issuecomment-634813319
- https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/issues/3#issuecomment-635618719
- The backup branch `danny-dev` includes the previous approach. 

Pending dev content review. May need some follow-up discussion and verification. 
- https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/issues/3#issuecomment-637243629

**Comment by DannyS03** [comment]
- **mvn package** not ideal for production. Guide will use **`mvn process-resources`** which is exactly what we want to achieve in terms of building and serving the static content of the frontend.

**Comment by DannyS03** [comment]
Hi @steven1046, it looks like the UI on the OL site isn't liking some of the JavaScript syntax we are using for this guide. We we wondering if you could look into it.  
- https://draft-guides.mybluemix.net/guides/rest-client-reactjs.html
> <img width="777" alt="image" src="https://user-images.githubusercontent.com/25497083/83794272-c7156100-a66b-11ea-938a-bfbbe21933bf.png">
> <img width="775" alt="image" src="https://user-images.githubusercontent.com/25497083/83794314-d5fc1380-a66b-11ea-8988-b6eba57192e4.png">
> <img width="541" alt="image" src="https://user-images.githubusercontent.com/25497083/83794189-a220ee00-a66b-11ea-983c-0c8df866aa90.png">

**Comment by steven1046** [comment]
Hi @DannyS03, i created an issue to fix it in the website repo: https://github.com/OpenLiberty/openliberty.io/issues/1687

**Comment by DannyS03** [comment]
> Hi @DannyS03, i created an issue to fix it in the website repo: [OpenLiberty/openliberty.io#1687](https://github.com/OpenLiberty/openliberty.io/issues/1687)

Thanks!

**Comment by gkwan-ibm** [comment]
- addressed all dev content feedback
- opened an issue for UI about displaying js file incorrectly
- next peer review

**Comment by gkwan-ibm** [comment]
- peer review in progress
  - Mac (Jimmy) - completed with feedback
  - Linux (Darren) - completed with feedback
  - Win (Tiago) - in progress

**Comment by gkwan-ibm** [comment]
- SME review in progress

**Comment by gkwan-ibm** [comment]
- addressed the SME feedback
- next is User review

**Comment by gkwan-ibm** [comment]
- user review in progress

**Comment by gkwan-ibm** [comment]
- ready for the final content review

**Comment by gkwan-ibm** [comment]
- addressing the final content review feedback

**Comment by gkwan-ibm** [comment]
- addressed  final content review
- ready for ID review

**Comment by gkwan-ibm** [comment]
- addressed ID review an wait for approval

**Comment by gkwan-ibm** [comment]
- need end-to-end test with hotspot (Meswan)

**Comment by meswan** [comment]
end-to-end test completed. Works as expected. No issues with hotspots.

**Comment by gkwan-ibm** [comment]
- starting the publish process but the travis test failed

**Comment by gkwan-ibm** [comment]
- the travis test failure was fixed
- need end-to-end quick test on qa branch and lgdev
  - [ ] Mac (Dareen)
  - [ ] Linux (Griffin)
  - [ ] Win (Danny)

**Comment by gkwan-ibm** [comment]
https://openliberty.io/guides/rest-client-reactjs.html
