### ISSUE TITLE
Add a sentence about start folder in mvnbuild adoc

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#88]
YK's feedback: 
For what’s out there, I do think we need to take another look at the `cd start` that was added.  It is better to call out via a sentence to remind the users to ensure they are under start since we won’t know where exactly they may be.

**Comment by evelinec** [comment]
Suggestion: 
To build the application, run the `install` Maven goal from the command line in the `start` directory:

```
cd start
mvn install
```

**Comment by evelinec** [comment]
@yeekangc @Kubik42 @JunyiSun @Ahmad-Ayyoub pls review.

**Comment by evelinec** [comment]
@JunyiSun if you can help facilitate the review and discussion, make the changes when there's a final decision, that'll be great. Thanks.

**Comment by yeekangc** [comment]
`cd start` should be removed.

The suggested change looks fine otherwise.  (It should be Maven `install` goal?)

**Comment by evelinec** [comment]
Closed.
