### ISSUE TITLE
Guide: MicroProfile Telemetry 1.0

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#888]
@fmhwong commented on [Mon Nov 28 2022](https://github.com/OpenLiberty/open-liberty/issues/23509)

Create a new guide for MicroProfile OpenTelemetry 1.0 feature.

---

@fmhwong commented on [Mon Nov 28 2022](https://github.com/OpenLiberty/open-liberty/issues/23509#issuecomment-1329865523)

@gkwan-ibm A new guide is needed.

**Comment by gkwan-ibm** [comment]
hi @fmhwong should the new guide use Jaeger or Zipkin? I don't think we need 2 guides for both. Am I right?

**Comment by fmhwong** [comment]
I'd recommend to start with Jaeger first.  If we have requests for Zipkin from customers in the future, we can consider that again.

**Comment by yeekangc** [comment]
Let us proceed to publish.  Thanks!

**Comment by gkwan-ibm** [comment]
close
- the guide was published
- https://openliberty.io/guides/microprofile-telemetry-jaeger.html
