### ISSUE TITLE
Create a common file for Try what you'll build Section

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/guides-common#91]

**Comment by Kubik42** [comment]
I'm not sure this will work since every "Try what you'll build" section is tailored for each guide.

**Comment by evelinec** [comment]
Perhaps just the heading plus the first two paragraphs, before seeing any results?

**Comment by evelinec** [comment]
Assign to @Ahmad-Ayyoub to work. Create proposal(s) and we'll review them.

**Comment by Ahmad-Ayyoub** [comment]
Here: https://github.com/Ahmad-Ayyoub/guides-common/commit/fc7909401102f48fb840091126ac1b1b6fd1b050

Take a look

**Comment by Ahmad-Ayyoub** [comment]
Already pushed to master. Here is the PR: https://github.com/OpenLiberty/guides-common/pull/105

**Comment by Ahmad-Ayyoub** [comment]
We will start using the new common files for the new guides and we will leave the old guides as they are.
