### ISSUE TITLE
Rewrite REST clients in MP guides to use MP REST Client

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#92]
Fix and rewrite the REST clients used in the MicroProfile guides to use MP Type-safe REST Client in MicroProfile 1.3.

Exception would be guides where we are talking about JAX-RS and JSON-P specifically.

**Comment by evelinec** [comment]
Moved to Icebox, till the REST client guide is developed.

**Comment by evelinec** [comment]
@JunyiSun and @justineechen to work together on this issue for all of the related guides.

**Comment by yeekangc** [comment]
@justineechen, can you please update the issue with the list of guides you will update?  Thank you.

**Comment by justineechen** [comment]
The following guides will be rewritten:
- [ ] guide-microprofile-metrics 
- [ ] guide-microprofile-config 
- [ ] guide-microprofile-fallback 
- [ ] guide-microprofile-health 
- [ ] guide-microprofile-rest-client 
- [ ] guide-microprofile-jwt 
- [ ] guide-microprofile-opentracing 
- [ ] guide-microprofile-openapi
