### ISSUE TITLE
SystemClient propagation to all other guides

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/guides-common#93]
Propagate the fix for SystemClient to all other guides. In InventoryManager.java, make the initialization of SystemClient inside the get() function.

**Comment by evelinec** [comment]
All MP guides using the SystemClient need to be fixed.

**Comment by evelinec** [comment]
FT was fixed.

**Comment by evelinec** [comment]
I think this can be combined with #92.

**Comment by evelinec** [comment]
Dup of #92. Closed.
