### ISSUE TITLE
Provide Subscription guide using Microprofile Graphql

### ISSUE THREAD

**Issue by Kenzku** [OpenLiberty/guides-common#947]
I was looking for references in MicroProfile to implement subscription operation on GraphQL, but I could not find the `@Subscription` or similar, instead, was found in `smallry-graphql-api` that bundle with Open Liberty.

<img width="451" alt="Screenshot 2023-08-05 at 12 38 11" src="https://github.com/eclipse/microprofile-graphql/assets/1387249/ec53885d-4e33-4e57-89fe-0b3f3747d8d9">

<img width="452" alt="Screenshot 2023-08-07 at 17 23 02" src="https://github.com/OpenLiberty/guides-common/assets/1387249/0799a6b9-9687-47a9-ae59-779fb6fd5d31">

Is this as designed?

Could you please provide a graphql Subscription guide using Open Liberty?

**Comment by WhiteCat22** [comment]
Hi @Kenzku,

Currently, the Microprofile GraphQL spec doesn't support Subscriptions. However, we intentionally expose the SmallRye GraphQL APIs that you can use. Please note, that our current version of SmallRye GraphQL is 1.0.26.
