### ISSUE TITLE
Revisit the data model for the inventory app

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#95]
InventoryList
-- could this be replaced by a simple Map?

Refer to background info in https://github.com/OpenLiberty/guide-microprofile-fallback/issues/39

**Comment by yeekangc** [comment]
We can improve the InventoryList -- there is still room for improvements -- but we need an object model for OpenAPI.

**Comment by evelinec** [comment]
Walked through with @andrewdes regarding the current model in the inventory app and advised he look into what's needed for OpenAPI and then see what improvement can be made overall.

**Comment by evelinec** [comment]
@proubatsis can you combine the fix in this issue along with the concurrency issue on the data model. Make the change as you are finding in this PR: https://github.com/OpenLiberty/guide-cdi-intro/pull/48

**Comment by evelinec** [comment]
Resolved.
