### ISSUE TITLE
Consider creating common repo(s) for common app(s)

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#96]
This is so that all MP guides can share the app and have less maintenance work for common code.

**Comment by yeekangc** [comment]
We need to consider if this can and should be done in general and if so, how should it be done.  The impact to user experience must be properly considered.

**Comment by yeekangc** [comment]
@aguibert @proubatsis have some ideas.  Andy, Panagiotis, please chime in.

FYI, @gkwan-ibm.

**Comment by gkwan-ibm** [comment]
close
- I doubt there is a good solution
- it is a low priority issue
