### ISSUE TITLE
Use of HTTP port value in pom.xml property and defaultValue in server.xml is confiusing

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/guides-common#961]
In pom.xml we set:

```xml
    <properties>
        <liberty.var.default.http.port>9080</liberty.var.default.http.port>
        <liberty.var.default.https.port>9443</liberty.var.default.https.port>
    </properties>
```

which we also pass to the test client via failsafe config.

In server.xml we have:

```xml
    <variable name="default.http.port" defaultValue="9080"/>
    <variable name="default.https.port" defaultValue="9443"/>

    <httpEndpoint host="*" httpPort="${default.http.port}" 
        httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>
```

It's natural to think one might be able to change a value in server.xml and see the port change, and it's surprising to learn that this value is overridden by the Liberty variable generated from the pom.xml property.

The defaultValue serves a purpose in the Docker build, since we are not making use of the liberty-maven-plugin-generated values there.

This is a bit of an advanced point and maybe makes the "getting started" sample a bit too confusing, arguably.  

Could we address with a comment?

Would it be just a bit less confusing to rename "default.http.port" => "http.port" ?

This applies to multiple guides too, not just this one.

**Comment by gkwan-ibm** [comment]
This problem should apply to most (51/64) of the guides

**Comment by gkwan-ibm** [comment]
close
- all guides should be updated except deprecated guides and liberty-deep-dive-gradle
